/* Starter Pack — MATHEMATICS part 1 (Number System → Percentages)
   Teaching style (spec §11): Concept → Formula/Rule → Method Recognition →
   Calculation → Practice → Mixed Practice. Every concept teaches from ZERO. */
import { h, p, li, F, NR, E, T, trap, mem, rec, st, note, sub, STARTER_REF } from './_shared.js';
const C = sub('MATH').concept;
const M = sub('MATH').method;
const Q = sub('MATH').q;

export const math1Concepts = [

/* ================= NUMBER SYSTEM ================= */
C('m-ns-placevalue', 'number-system', 'What is a Number? Place Value & Face Value',
  'Numbers are made of digits; place value changes with position.',
  [
    h('1. What is this?'),
    p('A number is a count or a measurement. We write numbers using ten digits: 0, 1, 2, 3, 4, 5, 6, 7, 8, 9.'),
    h('2. Basic idea in simple English'),
    p('In our number system, the VALUE of a digit depends on WHERE it sits. The same digit 3 is worth 3 in one place and 300 in another.'),
    E('Tiny example — the number 5,378', [
      '5 is in the thousands place → 5,000',
      '3 is in the hundreds place → 300',
      '7 is in the tens place → 70',
      '8 is in the units (ones) place → 8',
    ]),
    h('3. Face value vs place value'),
    T(['In 5,378', 'Face value', 'Place value'], [
      ['Digit 3', '3', '300'],
      ['Digit 5', '5', '5,000'],
      ['Digit 8', '8', '8'],
    ]),
    NR('Face value = the digit itself. Place value = digit × value of its position.'),
    E('Solved example — expand 4,206', [
      '4,206 = 4×1000 + 2×100 + 0×10 + 6×1',
      '4,206 = 4,000 + 200 + 0 + 6 = 4,206 ✓',
    ], '4,000 + 200 + 6'),
    h('4. How to recognize this type of question'),
    li([
      'The question says: “What is the place value of 7 in 3,745?”',
      'The question says: “difference between place value and face value of a digit”',
      'The question asks to expand or build a number.',
    ]),
    st([
      'Find the digit they ask about.',
      'Count its position from the right (units, tens, hundreds, thousands…).',
      'Place value = digit × 1, 10, 100, 1000… according to position.',
      'Face value = the digit itself.',
    ]),
    trap('Writing 300 as just 3 for place value. Place value ALWAYS includes the zeros of the position.'),
    mem('Keyword hook', 'PLACE = POSITION → place value depends on position. FACE = the face of the digit → face value is just the digit.'),
    rec('Face value = digit itself. Place value = digit × its position value.'),
  ],
  { text: 'What is the place value of 6 in the number 2,649?', options: ['6', '60', '600', '6,000'], answer: 1,
    steps: ['6 sits in the tens position.', 'Place value = 6 × 10 = 60.'] },
  ['q-ns-1']),

C('m-ns-factors', 'number-system', 'Factors and Multiples',
  'Factors divide a number exactly; multiples are what you get by multiplying.',
  [
    h('1. What is this?'),
    p('A FACTOR of a number divides it exactly (no remainder). A MULTIPLE is the answer when you multiply the number by a whole number.'),
    E('Tiny example — number 12', [
      'Factors of 12: 1, 2, 3, 4, 6, 12 (each divides 12 exactly).',
      'Multiples of 12: 12, 24, 36, 48, 60… (12×1, 12×2, 12×3…).',
    ]),
    NR('Factor = divides the number. Multiple = is divisible by the number. Remember: factor is smaller or equal, multiple is bigger or equal.'),
    h('2. Key facts'),
    li([
      '1 is a factor of every number.',
      'Every number is a factor and a multiple of itself.',
      'A number has LIMITED factors but UNLIMITED multiples.',
      'Factors of 12 in pairs: (1,12), (2,6), (3,4).',
    ]),
    E('Solved example — find all factors of 18', [
      'Divide 18 by 1, 2, 3… and keep the exact divisors.',
      '18 ÷ 1 = 18 ✓, 18 ÷ 2 = 9 ✓, 18 ÷ 3 = 6 ✓, 18 ÷ 4 ✗',
      'Factors of 18 = 1, 2, 3, 6, 9, 18.',
    ], '1, 2, 3, 6, 9, 18'),
    h('3. How to recognize this question'),
    li(['“Find the number of factors of …”', '“Which of these is NOT a factor of …”', '“How many factors does 36 have?”']),
    st(['Test divisibility from 1 upward in pairs.', 'Stop when the pair repeats (e.g., 4×4 for 16).']),
    trap('Forgetting the number itself and 1 as factors — they are always factors.'),
    mem('Contrast pair', 'Factor DIVIDES IN. Multiple COMES OUT of multiplication. In = smaller side, Out = bigger side.'),
    rec('Factor divides exactly; multiple is the product table of the number.'),
  ],
  { text: 'Which of these is a factor of 30?', options: ['4', '5', '7', '9'], answer: 1,
    steps: ['Test each: 30÷4 = 7.5 ✗', '30÷5 = 6 exactly ✓', 'So 5 is a factor.'] },
  ['q-ns-2']),

C('m-ns-divisibility', 'number-system', 'Divisibility Rules (Quick Checks)',
  'Test if a number divides another WITHOUT dividing.',
  [
    h('1. What is this?'),
    p('Divisibility rules are shortcuts. They tell you quickly if a number can be divided by 2, 3, 4, 5, 6, 8, 9, 10 or 11 with no remainder.'),
    h('2. The rules'),
    T(['Divide by', 'Rule', 'Example'], [
      ['2', 'Last digit is even (0,2,4,6,8)', '4712 → yes'],
      ['3', 'Sum of digits is divisible by 3', '471 → 4+7+1=12 → yes'],
      ['4', 'Last TWO digits divisible by 4', '316 → 16÷4 → yes'],
      ['5', 'Last digit is 0 or 5', '875 → yes'],
      ['6', 'Divisible by BOTH 2 and 3', '432 → even, 4+3+2=9 → yes'],
      ['8', 'Last THREE digits divisible by 8', '2312 → 312÷8=39 → yes'],
      ['9', 'Sum of digits divisible by 9', '726 → 7+2+6=15 → no'],
      ['10', 'Last digit is 0', '940 → yes'],
      ['11', 'Alternating sum of digits is 0 or a multiple of 11', '2728 → (8+7)−(2+2)=11 → yes'],
    ]),
    NR('These are rules, not formulas. Use the table above — it is enough for the exam.'),
    E('Solved example — is 4,27,531 divisible by 3?', [
      'Add the digits: 4+2+7+5+3+1 = 22.',
      '22 is not divisible by 3.',
      'So 4,27,531 is NOT divisible by 3.',
    ], 'No'),
    h('3. How to recognize this question'),
    li(['“Is 5,328 divisible by 6?”', '“Which of the following numbers is divisible by 9?”', '“The number 83P2 is divisible by 4 — find P.”']),
    trap('Confusing 4 and 8 rules (2 digits vs 3 digits), and mixing 3 with 9 (both use digit sum, but 9 needs the sum to divide by 9).'),
    mem('Story ladder', '2-1 digit, 4-2 digits, 8-3 digits: the rule DOUBLES and so does the digits you check. 3 and 9 are brothers (digit sum). 6 is the child of 2 and 3 (both must say yes).'),
    rec('2 even · 3 digit-sum · 4 last two · 5 ends 0/5 · 6 = 2&3 · 8 last three · 9 digit-sum by 9 · 10 ends 0 · 11 alternating sum.'),
  ],
  { text: 'Is the number 2,728 divisible by 11?', options: ['Yes', 'No', 'Only if it is even', 'Cannot be checked'], answer: 0,
    steps: ['Alternating sum from the right: (8 + 7) − (2 + 2)', '= 15 − 4 = 11', '11 is a multiple of 11 → yes, divisible.'] },
  ['q-ns-3'], { generators: ['g-ns-div'] }),

C('m-ns-primes', 'number-system', 'Prime, Composite and Even-Odd Numbers',
  'Prime = exactly 2 factors. Composite = more. 1 is neither.',
  [
    h('1. What is this?'),
    p('A PRIME number has exactly two factors: 1 and itself. A COMPOSITE number has more than two factors. The number 1 is NEITHER — it has only one factor.'),
    E('Tiny example', [
      '7 → factors 1, 7 → prime.',
      '9 → factors 1, 3, 9 → composite.',
      '1 → only factor 1 → neither prime nor composite.',
    ]),
    NR('Prime = only 2 factors. Composite = more than 2 factors. 1 is neither.'),
    h('2. Facts the exam loves'),
    li([
      '2 is the ONLY even prime number.',
      '2 is the smallest prime; 3 is the smallest odd prime.',
      'Primes up to 50: 2, 3, 5, 7, 11, 13, 17, 19, 23, 29, 31, 37, 41, 43, 47.',
      '51 = 3×17, 57 = 3×19, 91 = 7×13 — these LOOK prime but are NOT.',
      'Every even number > 2 is composite.',
    ]),
    E('Solved example — is 91 prime?', [
      'Test primes up to √91 ≈ 9.5 → test 2, 3, 5, 7.',
      '91 is odd, digit sum 10 (not ÷3), does not end in 0/5.',
      '91 ÷ 7 = 13 exactly → composite (7 × 13).',
    ], 'Not prime — 91 = 7 × 13'),
    h('3. How to recognize this question'),
    li(['“Which of the following is a prime number?”', '“The smallest prime number is …”', '“How many primes are there between 20 and 40?”']),
    st(['Check divisibility by 2, 3, 5, 7, 11… up to the square root of the number.', 'If nothing divides it, it is prime.']),
    trap('Trap numbers that look prime: 51, 57, 87, 91, 119 (7×17), 133 (7×19).'),
    mem('Funny association', 'Prime numbers are “selfish loners” — they only hang out with 1 and themselves. 2 is the only loner that is also even.'),
    rec('Prime = 2 factors only. 2 = smallest & only even prime. 91 = 7×13, NOT prime.'),
  ],
  { text: 'Which of the following is a prime number?', options: ['51', '53', '57', '91'], answer: 1,
    steps: ['51 = 3 × 17 → not prime.', '57 = 3 × 19 → not prime.', '91 = 7 × 13 → not prime.', '53 has no divisor up to 7 (53 ÷ 7 = 7.57) → prime.'] },
  ['q-ns-4'], { generators: ['g-ns-prime'] }),

/* ================= BODMAS ================= */
C('m-bodmas-1', 'bodmas', 'BODMAS — Order of Operations',
  'Simplify in the order: Brackets → Of/Orders → Division → Multiplication → Addition → Subtraction.',
  [
    h('1. What is this?'),
    p('When one line has many operations (＋ − × ÷), you cannot solve left to right. There is a fixed ORDER. BODMAS gives it.'),
    F('B → O → D → M → A → S', [
      ['B', 'Brackets ( ) first — innermost first'],
      ['O', 'Of / Orders (powers, square roots, “of” means multiply)'],
      ['D', 'Division (left to right)'],
      ['M', 'Multiplication (left to right)'],
      ['A', 'Addition (left to right)'],
      ['S', 'Subtraction (left to right)'],
    ], 'D and M have EQUAL power — solve them left to right. Same for A and S.'),
    E('Tiny example — 8 + 4 × 3', [
      'Multiplication first: 4 × 3 = 12.',
      'Then addition: 8 + 12 = 20. NOT 12×3=36 or (8+4)×3.',
    ]),
    E('Solved example — 12 ÷ 4 + 16 × 2 − 10', [
      'Division: 12 ÷ 4 = 3.',
      'Multiplication: 16 × 2 = 32.',
      'Now addition/subtraction left to right: 3 + 32 − 10 = 25.',
    ], '25'),
    h('2. How to recognize this question'),
    li(['A long arithmetic line with mixed + − × ÷ and brackets asks “simplify”.', '“Find the value of 6 + 8 ÷ 4 × (3 − 1)”']),
    st(['Solve inside brackets first.', 'Handle ÷ and × from left to right.', 'Handle + and − from left to right last.']),
    trap('Doing addition before multiplication (8+4×3 = 36 ✗). Multiplication ALWAYS comes before addition.'),
    mem('Word hook', 'BODMAS sounds like “Bod-maas”. Say it as one word — the letters themselves ARE the order.'),
    rec('Brackets → Of/powers → ÷× (left→right) → +− (left→right).'),
  ],
  { text: 'Simplify: 20 − 6 ÷ 2 + 4 × 3', options: ['23', '29', '61', '11'], answer: 1,
    steps: ['÷ first: 6 ÷ 2 = 3 → the line becomes 20 − 3 + 4 × 3', '× next: 4 × 3 = 12 → the line becomes 20 − 3 + 12', '+ and − left to right: 20 − 3 = 17, then 17 + 12 = 29'] },
  ['q-bo-1'], { generators: ['g-bodmas'] }),

/* ================= DECIMALS ================= */
C('m-dec-1', 'decimals', 'Decimals — Place Value Beyond Zero',
  'A decimal is another way to write a fraction with 10, 100, 1000… below.',
  [
    h('1. What is this?'),
    p('A decimal number has a point. Digits after the point are parts of 10, 100, 1000… So 0.7 means 7 tenths = 7/10.'),
    E('Tiny example', ['0.25 = 25/100 = 1/4 (one quarter).', '0.6 = 6/10 = 3/5.']),
    F('0.1 = 1/10    0.01 = 1/100    0.001 = 1/1000', [
      ['0.1', 'one tenth'],
      ['0.01', 'one hundredth'],
      ['0.001', 'one thousandth'],
    ]),
    h('2. Adding and subtracting decimals'),
    NR('No formula needed — use this rule: keep the points in one column, then add/subtract as normal numbers.'),
    E('Solved example — 2.5 + 0.75', [
      'Line up the points: 2.50',
      '                    +0.75',
      'Add normally: 3.25.',
    ], '3.25'),
    h('3. Multiplying decimals'),
    li(['Multiply ignoring the points: 3 × 2 = 6.', 'Count decimal places in BOTH numbers: 0.3 (1 place) × 0.2 (1 place) = 2 places.', 'Place the point so the answer has that many places: 0.06.']),
    h('4. How to recognize this question'),
    li(['“Convert 0.35 into a fraction”', '“3.05 + 0.7 = ?”', '“0.4 × 0.05 = ?”']),
    trap('0.3 × 0.2 = 0.6 is WRONG. Count the decimal places: answer is 0.06 (two places).'),
    mem('Visual association', 'The decimal point is a magnet: in add/subtract it lines up vertically; in multiply it moves LEFT by the total number of decimal places.'),
    rec('Add: line up points. Multiply: count decimal places and move the point left.'),
  ],
  { text: '0.4 × 0.05 = ?', options: ['0.2', '0.02', '0.002', '2'], answer: 1,
    steps: ['4 × 5 = 20 (ignore the points).', '0.4 has 1 decimal place, 0.05 has 2 → total 3 places.', '20 → 0.020 = 0.02.'] },
  ['q-de-1'], { generators: ['g-dec-add'] }),

/* ================= FRACTIONS ================= */
C('m-fr-1', 'fractions', 'What is a Fraction? Types',
  'A fraction is a part of a whole: numerator/denominator.',
  [
    h('1. What is this?'),
    p('A fraction shows a PART of a whole. In 3/4, the bottom (denominator) says the whole is cut into 4 equal parts; the top (numerator) says we take 3 of them.'),
    E('Tiny example', ['You cut a dosa into 4 equal pieces and eat 3 → you ate 3/4 of the dosa.']),
    h('2. Types of fractions'),
    T(['Type', 'Meaning', 'Example'], [
      ['Proper', 'Top < bottom (value < 1)', '3/4'],
      ['Improper', 'Top ≥ bottom (value ≥ 1)', '7/4'],
      ['Mixed', 'Whole number + proper fraction', '1 3/4 (= 7/4)'],
      ['Like', 'Same denominators', '2/9 and 5/9'],
      ['Unlike', 'Different denominators', '2/3 and 3/5'],
      ['Equivalent', 'Same value, different form', '1/2 = 2/4 = 5/10'],
    ]),
    NR('No formula needed — use this rule: proper = part smaller than whole; improper = whole or bigger; mixed = improper written with a full number.'),
    h('3. Improper ↔ mixed conversion'),
    E('Solved example — write 11/4 as mixed', [
      'Divide: 11 ÷ 4 = 2 remainder 3.',
      'Answer: 2 3/4 (quotient whole, remainder on top, same bottom).',
    ], '2 3/4'),
    h('4. How to recognize this question'),
    li(['“Which is an improper fraction?”', '“Convert 2 1/3 into an improper fraction” (2×3+1 = 7 → 7/3)']),
    trap('In mixed conversion, keeping the OLD denominator of a different fraction. The denominator stays the SAME as the improper fraction.'),
    mem('Keyword hook', 'Numerator = “how Many you take”. Denominator = “the size of the Dice/cut” (D = Down, N = Number on top).'),
    rec('Top = taken, bottom = total parts. Improper ≥ 1. Mixed: quotient + remainder/top.'),
  ],
  { text: 'Convert 2 1/3 into an improper fraction.', options: ['6/3', '7/3', '5/3', '8/3'], answer: 1,
    steps: ['Whole × denominator = 2 × 3 = 6.', 'Add numerator: 6 + 1 = 7.', 'Keep denominator: 7/3.'] },
  ['q-fr-1']),

C('m-fr-2', 'fractions', 'Equivalent Fractions and Simplification',
  'Multiply or divide top and bottom by the same number — value stays same.',
  [
    h('1. What is this?'),
    p('Equivalent fractions look different but have the same value: 1/2 = 2/4 = 50/100. Simplifying (reducing) brings a fraction to its smallest form.'),
    NR('No formula needed — use this rule: whatever you do to the top, do the SAME to the bottom (multiply or divide only).'),
    E('Solved example — simplify 36/48', [
      'Both divisible by 12: 36÷12 = 3, 48÷12 = 4.',
      'So 36/48 = 3/4. (Dividing by the HCF 12 in one step, or by 2,2,3 step by step.)',
    ], '3/4'),
    h('2. Comparing fractions'),
    st([
      'Make denominators equal using LCM, OR',
      'Cross-multiply: compare 3/4 and 5/7 → 3×7 = 21 and 4×5 = 20. Since 21 > 20, 3/4 > 5/7.',
    ]),
    h('3. How to recognize this question'),
    li(['“Which fraction is bigger?”', '“Reduce 42/56 to lowest terms”', '“Which is equivalent to 2/5?”']),
    trap('Adding the same number to top and bottom does NOT keep the value (1/2 ≠ 2/3). Only MULTIPLY/DIVIDE keeps equivalence.'),
    mem('If X, then Y', 'If you double the top, you must double the bottom. If you halve the bottom, halve the top. Breaking this changes the value.'),
    rec('Same operation on top and bottom → equivalent. Simplify by dividing by common factors.'),
  ],
  { text: 'Which of these is equal to 2/5?', options: ['4/15', '6/15', '8/15', '6/10'], answer: 1,
    steps: ['2/5 × 3/3 = 6/15.', 'Others do not come from multiplying top and bottom by the same number.'] },
  ['q-fr-2']),

C('m-fr-3', 'fractions', 'Adding and Subtracting Fractions',
  'Same bottoms → just add tops. Different bottoms → make them equal first (LCM).',
  [
    h('1. What is this?'),
    p('Fractions with the same denominator (like fractions) add directly. Unlike fractions must first be converted using the LCM of the denominators.'),
    NR('No formula needed — use this rule: same bottom → add tops, keep bottom. Different bottoms → replace both with LCM first.'),
    E('Solved example — 3/4 + 1/6', [
      'LCM of 4 and 6 = 12.',
      '3/4 = 9/12 and 1/6 = 2/12.',
      'Add: 9/12 + 2/12 = 11/12.',
    ], '11/12'),
    h('2. Method'),
    st(['Find LCM of denominators.', 'Convert each fraction to the LCM denominator.', 'Add/subtract the numerators only.', 'Simplify if possible.']),
    h('3. How to recognize this question'),
    li(['“1/2 + 1/3 + 1/6 = ?”', '“7/8 − 3/4 = ?”']),
    trap('Adding denominators: 1/2 + 1/3 is NOT 2/5. It is 5/6.'),
    mem('Visual association', 'You cannot add 2 apples and 3 oranges until you call them all “fruit”. You cannot add 1/2 and 1/3 until you call them both twelfths.'),
    rec('Different bottoms → LCM first → add tops only.'),
  ],
  { text: '1/2 + 1/3 = ?', options: ['2/5', '2/6', '5/6', '3/5'], answer: 2,
    steps: ['LCM of 2 and 3 = 6.', '1/2 = 3/6, 1/3 = 2/6.', '3/6 + 2/6 = 5/6.'] },
  ['q-fr-3'], { generators: ['g-fr-add'] }),

/* ================= LCM ================= */
C('m-lcm-1', 'lcm', 'LCM — Least Common Multiple',
  'The smallest number that two (or more) numbers can divide exactly.',
  [
    h('1. What is this?'),
    p('The LCM of two numbers is the smallest number that appears in the multiplication table of BOTH numbers. LCM of 4 and 6: multiples of 4 = 4,8,12…; of 6 = 6,12… → 12.'),
    F('LCM(a, b) = (a × b) ÷ HCF(a, b)', [
      ['a, b', 'the two numbers'],
      ['HCF', 'highest common factor of a and b'],
    ], 'Quick formula when you already know the HCF.'),
    E('Solved example — LCM of 12 and 18', [
      'Prime factors: 12 = 2×2×3, 18 = 2×3×3.',
      'LCM = take every prime the MOST times it appears = 2×2×3×3 = 36.',
      'Check: 36÷12 = 3 ✓, 36÷18 = 2 ✓.',
    ], '36'),
    h('2. How to recognize this question'),
    li([
      '“Bells ring every 6 and 8 seconds — when do they ring together?” → LCM.',
      '“Smallest number divisible by 12, 15 and 20”.',
      'Two runners on a circular track meet at the start again → LCM of lap times.',
    ]),
    st(['Break each number into prime factors.', 'Take each prime the maximum number of times it appears.', 'Multiply them.']),
    trap('LCM is NOT the product (12×18 = 216) unless the numbers are co-prime (no common factor). For co-prime numbers like 4 and 9, LCM = 36 = 4×9.'),
    mem('Keyword hook', 'LCM = “Least Common Multiple” → think “the Least COMMON meeting point” — where both multiplication tables MEET first.'),
    rec('LCM = smallest common multiple. Prime factors, take the MAX of each.'),
  ],
  { text: 'Two bells ring every 6 seconds and every 8 seconds. If they ring together now, after how many seconds will they ring together again?', options: ['14', '24', '48', '12'], answer: 1,
    steps: ['This is an LCM question (common multiple).', 'Multiples of 6: 6,12,18,24… Multiples of 8: 8,16,24…', 'First common = 24 seconds.'] },
  ['q-lcm-1'], { generators: ['g-lcm'] }),

/* ================= HCF ================= */
C('m-hcf-1', 'hcf', 'HCF — Highest Common Factor',
  'The biggest number that divides two (or more) numbers exactly.',
  [
    h('1. What is this?'),
    p('The HCF is the LARGEST number that divides both numbers with no remainder. HCF of 12 and 18: factors of 12 = {1,2,3,4,6,12}, of 18 = {1,2,3,6,18} → common {1,2,3,6} → HCF = 6.'),
    F('HCF(a, b) = (a × b) ÷ LCM(a, b)', [['a, b', 'the two numbers'], ['LCM', 'least common multiple']],
      'Partner formula of the LCM formula — both come from a×b = LCM × HCF.'),
    E('Solved example — HCF of 24 and 36', [
      'Prime factors: 24 = 2×2×2×3, 36 = 2×2×3×3.',
      'HCF = take every prime the FEWEST times it appears in both = 2×2×3 = 12.',
      'Check: 24÷12 = 2 ✓, 36÷12 = 3 ✓.',
    ], '12'),
    h('2. How to recognize this question'),
    li([
      '“Greatest number that divides 48 and 60 exactly” → HCF.',
      '“Largest tile size that covers a 12 m × 18 m floor exactly” → HCF.',
      '“Maximum number of equal groups from two piles” → HCF.',
    ]),
    st(['Break into prime factors.', 'Take each prime the MINIMUM times it appears in both.', 'Multiply.']),
    T(['', 'LCM', 'HCF'], [
      ['Take primes', 'MAX times', 'MIN times'],
      ['Answer size', 'bigger than or equal to numbers', 'smaller than or equal to numbers'],
      ['Question style', 'ring together / smallest divisible', 'greatest that divides'],
    ]),
    trap('Mixing up MIN and MAX. Memory: HCF = Hidden small (take minimum), LCM = Large common (take maximum).'),
    mem('Contrast pair', 'HCF divides IN (factors are inside), LCM is divided BY (multiples are outside).'),
    rec('HCF = biggest common factor, primes MIN. LCM = smallest common multiple, primes MAX.'),
  ],
  { text: 'Find the HCF of 24 and 36.', options: ['6', '12', '18', '24'], answer: 1,
    steps: ['24 = 2×2×2×3, 36 = 2×2×3×3.', 'Common primes, minimum times: 2×2×3 = 12.'] },
  ['q-hcf-1'], { generators: ['g-hcf'] }),

/* ================= RATIO AND PROPORTION ================= */
C('m-rp-1', 'ratio-proportion', 'Ratio — Comparing Quantities',
  'Ratio compares two quantities in the same unit, like 2 : 3.',
  [
    h('1. What is this?'),
    p('A ratio compares two amounts of the SAME kind. If a mixture has 2 parts milk and 3 parts water, the ratio milk : water = 2 : 3.'),
    F('Share of A = (A’s parts ÷ total parts) × total amount', [
      ['A’s parts', 'the first number of the ratio'],
      ['total parts', 'sum of ALL parts'],
      ['total amount', 'the whole quantity being divided'],
    ]),
    E('Solved example — divide ₹500 in ratio 2 : 3', [
      'Total parts = 2 + 3 = 5.',
      'One part = 500 ÷ 5 = ₹100.',
      'First share = 2 × 100 = ₹200, second = 3 × 100 = ₹300.',
    ], '₹200 and ₹300'),
    h('2. How to recognize this question'),
    li(['“Divide ₹720 between A and B in the ratio 4 : 5”', '“Incomes are in ratio 3 : 4 and their sum is …”', '“Mixture contains milk and water in ratio …”']),
    st(['Add the ratio parts → total parts.', 'Divide the amount by total parts → value of one part.', 'Multiply by each ratio number.']),
    trap('Dividing by a ratio number instead of TOTAL parts. Always add the parts first (2:3 → divide by 5, not 2 or 3).'),
    mem('Formula pattern', 'Total → parts → one part → each share. “Cut the cake into parts first, then give slices.”'),
    rec('One part = total ÷ (sum of ratio). Each share = ratio × one part.'),
  ],
  { text: '₹720 is divided between A and B in the ratio 4 : 5. Find B’s share.', options: ['₹320', '₹400', '₹360', '₹450'], answer: 1,
    steps: ['Total parts = 4 + 5 = 9.', 'One part = 720 ÷ 9 = ₹80.', 'B = 5 × 80 = ₹400.'] },
  ['q-rp-1'], { generators: ['g-ratio'] }),

C('m-rp-2', 'ratio-proportion', 'Proportion — Two Equal Ratios',
  'If a : b = c : d, then ad = bc (cross multiplication).',
  [
    h('1. What is this?'),
    p('Two ratios are in PROPORTION when they are equal. 2 : 3 and 4 : 6 are in proportion because 2/3 = 4/6.'),
    F('a : b :: c : d  ⟹  a × d = b × c', [
      ['a, b, c, d', 'the four terms (d is the fourth proportional you usually find)'],
    ], 'This is called the “rule of cross multiplication”.'),
    E('Solved example — find x if 6 : 9 :: 10 : x', [
      'Cross multiply: 6 × x = 9 × 10.',
      '6x = 90 → x = 15.',
    ], 'x = 15'),
    h('2. How to recognize this question'),
    li(['“Find the fourth proportional to 6, 9, 10”', '“If 8 pens cost ₹40, what do 12 pens cost?” (direct proportion)']),
    st(['Write the ratios equal to each other.', 'Cross multiply.', 'Solve the simple equation.']),
    trap('Multiplying straight across (6×10 = 60) instead of cross multiplying. Multiply ACROSS the equals sign.'),
    mem('Butterfly visual', 'Draw butterfly wings connecting a→d and b→c across the equals sign; the products of the wings are equal.'),
    rec('a:b :: c:d → ad = bc. Cross multiply, then solve.'),
  ],
  { text: 'If 8 pens cost ₹40, what do 12 pens cost?', options: ['₹48', '₹60', '₹56', '₹72'], answer: 1,
    steps: ['Cost per pen = 40 ÷ 8 = ₹5 (proportion: 8:40 :: 12:x).', '8 × x = 40 × 12 → 8x = 480.', 'x = ₹60.'] },
  ['q-rp-2']),

/* ================= PERCENTAGES — foundation concepts ================= */
C('m-pct-1', 'percentages', 'What is Percentage? (Start From Zero)',
  'Percent means “out of 100”. 25% = 25/100 = 1/4.',
  [
    h('1. What is this?'),
    p('“Percent” means “per hundred”. 40% simply means 40 out of every 100. It is just a special fraction whose bottom is always 100.'),
    F('x% of N = (x ÷ 100) × N', [
      ['x%', 'the percentage rate'],
      ['N', 'the number you are taking the percentage OF'],
    ]),
    E('Tiny example', [
      '50% of 40 = (50/100) × 40 = half of 40 = 20.',
      '10% of 450 = (10/100) × 450 = 45.',
    ]),
    h('2. Percentage ↔ fraction table (learn this — it saves minutes)'),
    T(['Fraction', 'Percent', 'Fraction', 'Percent'], [
      ['1/2', '50%', '1/3', '33⅓%'],
      ['1/4', '25%', '2/3', '66⅔%'],
      ['1/5', '20%', '1/8', '12.5%'],
      ['1/10', '10%', '3/8', '37.5%'],
      ['1/20', '5%', '1/25', '4%'],
      ['1/50', '2%', '1/100', '1%'],
    ]),
    h('3. The 10% building block (genuine shortcut)'),
    p('10% of a number = move the decimal one step LEFT. 10% of 480 = 48. From this: 5% = half of 10% (24), 20% = double 10% (96), 30% = 48+96 = 144. Most exam percentages can be built from 10%, 5% and 1%.'),
    E('Solved example — find 35% of 240 without long division', [
      '10% of 240 = 24.',
      '30% = 24 × 3 = 72.',
      '5% = 12 (half of 24).',
      '35% = 72 + 12 = 84.',
    ], '84'),
    h('4. How to recognize this question'),
    li(['“Find 45% of 600”', '“What is 12% of 250?”', 'Any question where a rate per hundred is applied to a quantity.']),
    st(['See the % number as building blocks (10s, 5s, 1s) or use x/100 × N directly.', 'Compute.', 'Sanity-check: 50% should be about half.']),
    trap('40% of 50 is the same as 50% of 40 (= 20) — fine — but students freeze on “% of what?”. Always identify N: the number AFTER the word “of”.'),
    mem('Meaning hook', 'PER-CENT literally = “for every hundred” (cent = 100, like century). 7% = 7 for every 100.'),
    rec('x% of N = x/100 × N. 10% = decimal moves one step left.'),
  ],
  { text: 'What is 25% of 80?', options: ['15', '20', '25', '40'], answer: 1,
    steps: ['25% = 1/4.', '1/4 of 80 = 80 ÷ 4 = 20.'] },
  ['q-pct-1', 'q-pct-2']),

C('m-pct-2', 'percentages', 'Percentage Change — Increase and Decrease',
  'Change% = (change ÷ ORIGINAL) × 100.',
  [
    h('1. What is this?'),
    p('When a value goes up or down, the exam asks “by what percent did it change?” The change is ALWAYS compared with the ORIGINAL (old) value.'),
    F('% change = (New − Old) ÷ Old × 100', [
      ['New', 'value after the change'],
      ['Old', 'ORIGINAL value before the change'],
      ['New − Old', 'the amount of change (negative if decrease)'],
    ]),
    E('Solved example — price rises from ₹250 to ₹300', [
      'Change = 300 − 250 = ₹50.',
      'Compare with ORIGINAL: 50/250 × 100 = 20% increase.',
    ], '20% increase'),
    h('2. Fast multipliers (very useful)'),
    li([
      'Increase by r% → multiply by (100 + r)/100. +20% → ×1.2',
      'Decrease by r% → multiply by (100 − r)/100. −20% → ×0.8',
      'Example: ₹500 with 20% increase → 500 × 1.2 = ₹600.',
    ]),
    h('3. How to recognize this question'),
    li(['“The price increased from … to … — find the percentage increase”', '“Salary reduced by 10%…”', '“Population fell from …”']),
    st(['Find the change (New − Old).', 'Divide by the OLD value — always the original.', '× 100.']),
    trap('Dividing by the NEW value. Percentage change is always relative to the ORIGINAL number.'),
    mem('If X, then Y', 'If the question gives you an OLD value, that OLD value is your divisor. “Change compares to where you came FROM.”'),
    rec('Change ÷ ORIGINAL × 100. +r% → ×(100+r)/100.'),
  ],
  { text: 'The price of an item rises from ₹250 to ₹300. What is the percentage increase?', options: ['16.67%', '20%', '25%', '50%'], answer: 1,
    steps: ['Change = 300 − 250 = 50.', 'Original = 250.', '50/250 × 100 = 20%.'] },
  ['q-pct-3']),
];

/* ================= METHODS (Maths Method Trainer models) ================= */
export const math1Methods = [
M('pct-of', 'percentages', 'Model 1: Find x% of a number',
  'Directly apply the percentage to a quantity.',
  'x% of N = (x ÷ 100) × N',
  'Question asks “find / what is x% of a number”. The number follows the word “of”.',
  { text: 'Find 15% of 400.', steps: ['15% = 15/100.', '15/100 × 400 = 60.'], answer: '60' }),

M('pct-increase', 'percentages', 'Model 2: Percentage increase',
  'A value goes UP by a rate — find the NEW value.',
  'New = Old × (100 + r) ÷ 100',
  'Words like “increases by”, “rises by”, “grows by” + a %. Example: a price is ₹500 and increases by 20% → find the new price.',
  { text: 'A price is ₹500 and increases by 20%. Find the new price.', steps: ['New = 500 × 120/100', '= 500 × 1.2 = ₹600.'], answer: '₹600' }),

M('pct-decrease', 'percentages', 'Model 3: Percentage decrease',
  'A value goes DOWN by a rate — find the NEW value.',
  'New = Old × (100 − r) ÷ 100',
  'Words like “decreases by”, “falls by”, “reduced by”, “discount of” + a %.',
  { text: 'A salary of ₹8,000 is reduced by 15%. Find the new salary.', steps: ['New = 8000 × 85/100', '= 8000 × 0.85 = ₹6,800.'], answer: '₹6,800' }),

M('pct-reverse', 'percentages', 'Model 4: Reverse percentage',
  'You know the value AFTER the change — find the ORIGINAL.',
  'Original = New × 100 ÷ (100 ± r)   (+ if it increased, − if decreased)',
  'Phrases like “after a 20% increase the price became ₹600” or “a number increased by 25% gives 500 — find the number”. You are going BACKWARDS.',
  { text: 'After a 20% increase, a price became ₹600. What was the original price?', steps: ['Original = 600 × 100/120', '= 600 ÷ 1.2 = ₹500.'], answer: '₹500' }),

M('pct-successive', 'percentages', 'Model 5: Successive percentage',
  'Two (or more) changes one after the other.',
  'Net % = a + b + (a × b) ÷ 100',
  '“Increased by 20% and then by 10%”, “a discount of 10% followed by 20%”, “population grows 10% first year and 5% next year”.',
  { text: 'A value increases by 20% and then by 10%. What is the net change?', steps: ['Net = 20 + 10 + (20×10)/100', '= 30 + 2 = 32% increase.'], answer: '32% increase' }),

M('pct-compare', 'percentages', 'Model 6: Percentage comparison',
  'Compare two quantities as a percentage of each other.',
  'A as % of B = (A ÷ B) × 100',
  '“A is what percent of B?”, “B is how much % more than A?”, “express A as a percentage of B”.',
  { text: 'A scores 45 out of 60. What is his percentage?', steps: ['(45 ÷ 60) × 100', '= 75%.'], answer: '75%' }),

M('pct-error', 'percentages', 'Model 7: Error percentage',
  'A mistake is measured against the TRUE value.',
  'Error % = |Wrong − Correct| ÷ Correct × 100',
  '“While copying, a student wrote 54 instead of 45 — find the % error”, exam answer-key style questions.',
  { text: 'The correct number is 500. A student wrote 450. Find the error percentage.', steps: ['Error = |450 − 500| = 50.', 'Error% = 50/500 × 100 = 10%.'], answer: '10%' }),
];

/* ================= STATIC QUESTIONS (math part 1) ================= */
export const math1Questions = [
Q('q-ns-1', 'number-system', { conceptId: 'm-ns-placevalue', text: 'What is the DIFFERENCE between the place value and the face value of 7 in 7,482?', options: ['7,000', '6,993', '700', '0'], answer: 1, difficulty: 2,
  tests: 'Place value vs face value of a digit.', solution: ['Place value of 7 (thousands) = 7,000.', 'Face value = 7.', 'Difference = 7,000 − 7 = 6,993.'],
  wrongWhy: ['This is the place value itself, not the difference.', 'Correct: 7,000 − 7 = 6,993.', 'This would be if 7 sat in the hundreds place.', 'Difference is not zero because place value ≠ face value here.'],
  trap: 'Reading the position wrongly. From the right: units, tens, hundreds, thousands.', memory: { tech: 'Keyword hook', x: 'PLACE = position × digit; FACE = the digit alone.' }, recall: 'Place value − face value = digit × (position value − 1).' }),

Q('q-ns-2', 'number-system', { conceptId: 'm-ns-factors', text: 'How many factors does 36 have?', options: ['6', '8', '9', '12'], answer: 2, difficulty: 2,
  tests: 'Counting factors of a number.', solution: ['36 = 2² × 3².', 'Number of factors = (2+1)(2+1) = 9.', 'They are 1,2,3,4,6,9,12,18,36.'],
  wrongWhy: ['You may have counted only 1,2,3,4,6,9.', 'Count again — 12, 18 and 36 are also factors.', 'Correct: 9 factors.', 'Too many.'],
  trap: 'Forgetting the number itself and 1.', memory: { tech: 'Formula pattern', x: 'Prime factor exponents +1, multiplied: (a+1)(b+1).' }, recall: '36 → 2²3² → (3)(3) = 9 factors.' }),

Q('q-ns-3', 'number-system', { conceptId: 'm-ns-divisibility', text: 'The number 4,52,116 is divisible by which of the following?', options: ['3', '4', '9', '11'], answer: 1, difficulty: 2,
  tests: 'Divisibility rules for 3, 4, 9 and 11.', solution: ['Digit sum = 4+5+2+1+1+6 = 19 → not divisible by 3 (so also not by 9).', 'Last two digits = 16, and 16 ÷ 4 = 4 → divisible by 4 ✓.', 'Alternating sum = 4−5+2−1+1−6 = −5 → not a multiple of 11.', 'Answer: 4.'],
  wrongWhy: ['Digit sum 19 is not a multiple of 3.', 'Correct: last two digits 16 divide by 4.', '19 is not a multiple of 9.', 'Alternating sum −5 is not a multiple of 11.'],
  trap: 'For 4, check ONLY the last two digits. For 3 and 9, check the digit sum.', memory: { tech: 'Brother rule', x: '3 and 9 use digit sum; 4 uses last TWO digits; 8 uses last THREE.' }, recall: '4 → last two digits; 3/9 → digit sum; 11 → alternating sum.' }),

Q('q-ns-4', 'number-system', { conceptId: 'm-ns-primes', text: 'Which of the following is NOT a prime number?', options: ['61', '71', '81', '97'], answer: 2, difficulty: 1,
  tests: 'Prime identification.', solution: ['61 is prime.', '71 is prime.', '81 = 9 × 9 = 3⁴ → NOT prime.', '97 is prime.'],
  wrongWhy: ['61 has no factors except 1 and 61.', '71 is prime.', 'Correct: 81 = 3⁴.', '97 is prime (no divisor up to 9).'],
  trap: 'Odd numbers ending in 1 can look prime. Always test 3 and 7.', memory: { tech: 'Square trap', x: '81 = 3⁴ is the classic fake prime; 91 = 7×13 is another.' }, recall: 'Test divisibility by primes up to the square root.' }),

Q('q-bo-1', 'bodmas', { conceptId: 'm-bodmas-1', text: 'Simplify: 15 − 3 × 2 + 8 ÷ 4', options: ['10', '11', '17.5', '20'], answer: 1, difficulty: 1,
  tests: 'Order of operations.', solution: ['× and ÷ first: 3 × 2 = 6, 8 ÷ 4 = 2.', 'Now the line is 15 − 6 + 2.', 'Left to right: 15 − 6 = 9, then 9 + 2 = 11.'],
  wrongWhy: ['10 comes from 15 − (6 + 2) — wrong grouping; same-priority work goes left to right.', 'Correct: 15 − 6 + 2 = 11.', 'Misplaced division.', 'Added before subtracting wrongly.'],
  trap: '15 − 6 + 2 is NOT 15 − 8. Same-priority operations go LEFT TO RIGHT.', memory: { tech: 'Word hook', x: 'BODMAS order itself is the memory method.' }, recall: '× ÷ before + −, then left to right.' }),

Q('q-de-1', 'decimals', { conceptId: 'm-dec-1', text: 'Convert the decimal 0.35 into a fraction in lowest terms.', options: ['35/100', '7/20', '7/25', '5/7'], answer: 1, difficulty: 1,
  tests: 'Decimal to fraction conversion.', solution: ['0.35 = 35/100.', 'Divide top and bottom by 5: 7/20.'],
  wrongWhy: ['This is correct but NOT in lowest terms.', 'Correct.', '7/25 = 0.28.', 'Reversed nonsense.'],
  trap: 'Stopping at 35/100 without simplifying.', memory: { tech: 'If X then Y', x: 'If two decimal places, bottom is 100; then simplify by common factors.' }, recall: 'Two places → /100 → simplify.' }),

Q('q-fr-1', 'fractions', { conceptId: 'm-fr-1', text: 'Which of the following is an improper fraction?', options: ['3/4', '7/8', '9/5', '1/2'], answer: 2, difficulty: 1,
  tests: 'Types of fractions.', solution: ['Improper = numerator ≥ denominator.', '9/5 has top (9) bigger than bottom (5).'],
  wrongWhy: ['Proper — top smaller.', 'Proper.', 'Correct: 9 ≥ 5.', 'Proper.'],
  trap: 'None — just know the definition.', memory: { tech: 'Keyword hook', x: 'Improper = “top-heavy” fraction, like an overloaded plate.' }, recall: 'Improper: top ≥ bottom.' }),

Q('q-fr-2', 'fractions', { conceptId: 'm-fr-2', text: 'Which fraction is the LARGEST: 2/3, 3/5, 5/8, 11/16?', options: ['2/3', '3/5', '5/8', '11/16'], answer: 3, difficulty: 3,
  tests: 'Comparing unlike fractions.', solution: ['Cross-compare pairs: 2/3 vs 11/16 → 2×16 = 32 and 3×11 = 33. Since 32 < 33, 2/3 < 11/16.', '3/5 vs 11/16 → 3×16 = 48 and 5×11 = 55 → 3/5 < 11/16.', '5/8 = 10/16 < 11/16.', 'So the largest is 11/16 (= 0.6875).'],
  wrongWhy: ['2/3 ≈ 0.667 — close, but 11/16 = 0.6875 is bigger.', '0.6 — the smallest here.', '0.625.', 'Correct: 0.6875 is the largest.'],
  trap: 'Guessing by look. Use cross multiplication to compare two fractions at a time.', memory: { tech: 'Ladder method', x: 'Make all bottoms the same (sixteenths here), then just compare tops.' }, recall: 'Cross-multiply pairs: bigger product wins.' }),

Q('q-fr-3', 'fractions', { conceptId: 'm-fr-3', text: '7/8 − 3/4 = ?', options: ['4/4', '1/8', '1/4', '5/8'], answer: 1, difficulty: 1,
  tests: 'Subtracting unlike fractions.', solution: ['3/4 = 6/8.', '7/8 − 6/8 = 1/8.'],
  wrongWhy: ['Subtracted bottoms too.', 'Correct.', '1/4 = 2/8 — too big.', '5/8 = 7/8 − 2/8.'],
  trap: 'Subtracting denominators.', memory: { tech: 'Visual association', x: 'Same-size slices only — convert to eighths first.' }, recall: 'Make bottoms equal, subtract tops.' }),

Q('q-lcm-1', 'lcm', { conceptId: 'm-lcm-1', text: 'Find the LCM of 8, 12 and 15.', options: ['60', '120', '240', '360'], answer: 1, difficulty: 2,
  tests: 'LCM of three numbers.', solution: ['8 = 2³, 12 = 2²×3, 15 = 3×5.', 'LCM = 2³ × 3 × 5 = 8 × 15 = 120.'],
  wrongWhy: ['60 is not divisible by 8.', 'Correct.', 'Works but is not the LEAST.', 'Too big.'],
  trap: 'Forgetting a prime that appears in only one number (the 5 here).', memory: { tech: 'Max rule', x: 'LCM: take each prime its MAX times.' }, recall: '2³×3×5 = 120.' }),

Q('q-hcf-1', 'hcf', { conceptId: 'm-hcf-1', text: 'Find the HCF of 36 and 48.', options: ['6', '12', '18', '24'], answer: 1, difficulty: 1,
  tests: 'HCF by prime factors.', solution: ['36 = 2²×3², 48 = 2⁴×3.', 'HCF = 2²×3 = 12.'],
  wrongWhy: ['6 is A common factor but not the HIGHEST.', 'Correct.', '18 does not divide 48.', '24 does not divide 36.'],
  trap: 'Choosing a common factor instead of the highest.', memory: { tech: 'Min rule', x: 'HCF: each prime its MIN times.' }, recall: '2²×3 = 12.' }),

Q('q-rp-1', 'ratio-proportion', { conceptId: 'm-rp-1', text: 'Two numbers are in the ratio 3 : 5 and their sum is 64. Find the numbers.', options: ['21 and 43', '24 and 40', '18 and 46', '27 and 37'], answer: 1, difficulty: 2,
  tests: 'Dividing a quantity in a ratio.', solution: ['Total parts = 3 + 5 = 8.', 'One part = 64 ÷ 8 = 8.', 'Numbers: 3×8 = 24 and 5×8 = 40.'],
  wrongWhy: ['24 + 43 ≠ 64 pattern broken.', 'Correct.', 'Ratio of 18:46 is 9:23, not 3:5.', '27:37 is not 3:5.'],
  trap: 'Dividing 64 by 5 or by 3 instead of 8.', memory: { tech: 'Formula pattern', x: 'Sum → parts → one part → shares.' }, recall: 'One part = sum ÷ total parts.' }),

Q('q-rp-2', 'ratio-proportion', { conceptId: 'm-rp-2', text: 'If 6 workers can paint a wall in 10 days, how long will 15 workers take (same speed)?', options: ['4 days', '6 days', '25 days', '5 days'], answer: 0, difficulty: 2,
  tests: 'Inverse proportion.', solution: ['Work = 6 × 10 = 60 worker-days.', 'With 15 workers: 60 ÷ 15 = 4 days.'],
  wrongWhy: ['Correct.', 'Direct-proportion mistake.', 'More workers cannot take MORE days.', 'Misdivision.'],
  trap: 'Treating it as direct proportion. More workers → FEWER days.', memory: { tech: 'If X then Y', x: 'If workers multiply, days divide — inverse.' }, recall: 'Workers × days = constant work.' }),

Q('q-pct-1', 'percentages', { conceptId: 'm-pct-1', methodId: 'pct-of', text: 'What is 45% of 600?', options: ['250', '270', '275', '300'], answer: 1, difficulty: 1,
  tests: 'Model 1 — x% of a number.', solution: ['10% of 600 = 60 → 40% = 240.', '5% = 30.', '45% = 240 + 30 = 270.'],
  wrongWhy: ['Rough guess.', 'Correct.', 'Arithmetic slip.', 'That is 50%.'],
  trap: 'Doing 45 × 600 = 27,000 and forgetting ÷100.', memory: { tech: '10% blocks', x: 'Build 45% from 4×10% + 5%.' }, recall: 'x% of N = x/100 × N.' }),

Q('q-pct-2', 'percentages', { conceptId: 'm-pct-1', text: '0.8 expressed as a percentage is:', options: ['8%', '80%', '0.08%', '800%'], answer: 1, difficulty: 1,
  tests: 'Decimal ↔ percentage conversion.', solution: ['×100: 0.8 × 100 = 80%.'],
  wrongWhy: ['Moved the point the wrong way.', 'Correct.', 'Wrong direction.', 'Too big.'],
  trap: 'Dividing by 100 instead of multiplying.', memory: { tech: 'If X then Y', x: 'If decimal → percent, move the point RIGHT two steps.' }, recall: 'Decimal → % : ×100.' }),

Q('q-pct-3', 'percentages', { conceptId: 'm-pct-2', methodId: 'pct-increase', text: 'A price is ₹500 and increases by 20%. Find the new price.', options: ['₹520', '₹600', '₹625', '₹700'], answer: 1, difficulty: 1,
  tests: 'Model 2 — percentage increase.', solution: ['New = 500 × (100+20)/100 = 500 × 1.2', '= ₹600.'],
  wrongWhy: ['Added ₹20 instead of 20% of 500.', 'Correct.', 'Used 1.25 multiplier.', 'Used 1.4.'],
  trap: 'Adding the rate number itself (20) instead of the percentage value (100).', memory: { tech: 'Multiplier', x: '+20% means ×1.2, like switching on a 1.2x speed.' }, recall: 'New = Old × (100+r)/100.' }),
];
