/* Starter Pack — GENERAL AWARENESS (STATIC GK only).
   Teaching style (spec §11, §27): Fact → Context → Why it matters →
   Association → Recall → spaced revision.
   CURRENT AFFAIRS is deliberately NOT filled here: per spec §27, current
   affairs must come only from a current-affairs source the user imports. */
import { h, p, li, F, NR, E, T, trap, mem, rec, st, note, sub, STARTER_REF } from './_shared.js';
const C = sub('GA').concept;
const Q = sub('GA').q;

const GK_REF = 'Starter Pack static GK — standard, well-established facts (NOT from an uploaded guide; not current affairs).';

export const gkConcepts = [

/* -------- Science and Technology -------- */
C('g-st-space', 'science-technology', 'Indian Space Programme — Key Firsts',
  'ISRO 1969; Aryabhata 1975; Chandrayaan-3 near the lunar south pole, 2023.',
  [
    h('1. The facts'),
    T(['Fact', 'Detail'], [
      ['ISRO founded', '1969 (father of the Indian space programme: Dr Vikram Sarabhai)'],
      ['First Indian satellite', 'Aryabhata, 1975'],
      ['First Indian in space', 'Rakesh Sharma, 1984 (Soviet Soyuz)'],
      ['Chandrayaan-3', 'soft-landed near the lunar SOUTH POLE, 23 August 2023'],
      ['PSLV / GSLV', 'ISRO’s workhorse / heavy-lift launch vehicles'],
    ]),
    h('2. Context'),
    p('ISRO began with a rocket-parts unit in Thumba carried on bicycles. Aryabhata was named after the ancient mathematician.'),
    h('3. Why it matters'),
    p('Space achievements are a favourite GA area — and they link persons (Sarabhai, Kalam, Rakesh Sharma), dates and technology in one question.'),
    h('4. Association map'),
    li(['Sarabhai → ISRO founder (1969)', 'Kalam → SLV/missile programme (Missile Man)', 'Rakesh Sharma → “Saare Jahan Se Achha” reply from space', 'Chandrayaan-3 → Vikram lander + Pragyan rover']),
    trap('Aryabhata (first SATELLITE, 1975) vs Rakesh Sharma (first MAN in space, 1984) — the classic swap.'),
    mem('Bicycle-to-Moon story', 'From parts carried on bicycles (Thumba) to landing near the Moon’s south pole — one story chain carries ISRO 1969 → Aryabhata 1975 → Chandrayaan-3 2023.'),
    rec('ISRO 1969 · Aryabhata 1975 · Rakesh Sharma 1984 · Chandrayaan-3 south pole 2023.'),
  ],
  { text: 'India’s first satellite, launched in 1975, was named:', options: ['Bhaskara', 'Aryabhata', 'INSAT', 'Rohini'], answer: 1,
    steps: ['Aryabhata (1975) — named after the mathematician.'] },
  ['q-gk-1']),

/* -------- Sports -------- */
C('g-sp-olympic', 'sports', 'Olympics and India — Core Facts',
  'Modern Olympics 1896 Athens; 4-year cycle; India’s hockey legacy.',
  [
    h('1. The facts'),
    T(['Fact', 'Detail'], [
      ['First modern Olympics', '1896, Athens, Greece'],
      ['Cycle', 'every 4 years'],
      ['Olympic rings', '5 rings = 5 continents'],
      ['India’s hockey golds', '8 Olympic golds (first 1928, the era of Dhyan Chand)'],
      ['National Sports Day', '29 August (Major Dhyan Chand’s birthday)'],
      ['First individual gold (India)', 'Abhinav Bindra, shooting, Beijing 2008'],
    ]),
    h('2. Honest note'),
    p('Hockey is POPULARLY called India’s national game, but the Government of India has clarified (RTI, 2012) that it has NOT officially declared any national game.'),
    h('3. Why it matters'),
    p('Sports GA is mostly stable: Olympics history, hockey legacy, famous winners. Current tournaments belong to current affairs — import a CA source for those.'),
    h('4. Association map'),
    li(['Dhyan Chand → hockey wizard → 29 Aug Sports Day', 'Abhinav Bindra → shooting → first individual gold', 'P.V. Sindhu → badminton → two Olympic medals (silver 2016, bronze 2020)']),
    trap('1896 Athens (first MODERN games) vs ancient Greece games — the exam asks “modern”.'),
    mem('Dhyan Chand date hook', 'Hockey wizard’s birthday = Sports Day = 29 August. One date, two facts.'),
    rec('1896 Athens · 4-year cycle · 8 hockey golds · Bindra 2008.'),
  ],
  { text: 'The modern Olympic Games were first held in:', options: ['1896, Athens', '1900, Paris', '1924, Paris', '776 BC, Olympia'], answer: 0,
    steps: ['Athens 1896 — the first MODERN Olympics (ancient games were much older).'] },
  ['q-gk-2']),

/* -------- Culture -------- */
C('g-cu-dance', 'culture', 'Classical Dances of India',
  'Eight classical dances — match each to its state.',
  [
    h('1. The facts'),
    T(['Dance', 'State'], [
      ['Bharatanatyam', 'Tamil Nadu'],
      ['Kathak', 'Uttar Pradesh (North India tradition)'],
      ['Kathakali', 'Kerala'],
      ['Mohiniyattam', 'Kerala'],
      ['Kuchipudi', 'Andhra Pradesh'],
      ['Odissi', 'Odisha'],
      ['Manipuri', 'Manipur'],
      ['Sattriya', 'Assam'],
    ]),
    h('2. Context'),
    p('These eight are recognised as CLASSICAL by the Sangeet Natak Akademi. Each grew around temples or court traditions and has its own music and costume grammar.'),
    h('3. Why it matters'),
    p('“Match the dance to the state” is a guaranteed one-mark pattern in railway and SSC exams.'),
    h('4. Association map'),
    li(['Kerala pair → Kathakali (male-dominant, green face) + Mohiniyattam (graceful, white-and-gold)', 'Eastern pair → Manipuri + Sattriya (Assam)', 'Odissi → Odisha (both start with “O”!)']),
    trap('Kathak (UP) vs Kathakali (Kerala) — two letters change the state entirely.'),
    mem('Odissi-Odisha rule', 'Odissi–Odisha share “O”. KathakALI wears heavy ALI-green face paint → Kerala. Mohini (enchantress) dances by Kerala’s backwaters.'),
    rec('TN Bharatanatyam · UP Kathak · Kerala Kathakali/Mohiniyattam · AP Kuchipudi · Odisha Odissi · Manipur · Assam Sattriya.'),
  ],
  { text: 'Kuchipudi, a classical dance form, comes from:', options: ['Kerala', 'Andhra Pradesh', 'Odisha', 'Tamil Nadu'], answer: 1,
    steps: ['Kuchipudi = Andhra Pradesh.', 'Kerala = Kathakali & Mohiniyattam; Odisha = Odissi; TN = Bharatanatyam.'] },
  ['q-gk-3']),

C('g-cu-fest', 'culture', 'Festivals and States',
  'Pongal–TN, Onam–Kerala, Bihu–Assam, Baisakhi–Punjab.',
  [
    h('1. The facts'),
    T(['Festival', 'State / people'], [
      ['Pongal', 'Tamil Nadu (harvest, 4 days, January)'],
      ['Onam', 'Kerala (harvest; legend of King Mahabali)'],
      ['Bihu', 'Assam (harvest, April)'],
      ['Baisakhi', 'Punjab (harvest + Khalsa founding, 1699)'],
      ['Durga Puja', 'West Bengal'],
      ['Ganesh Chaturthi', 'Maharashtra'],
      ['Hornbill Festival', 'Nagaland'],
    ]),
    h('2. Context'),
    p('Harvest festivals are the exam’s favourite cluster: Pongal, Onam, Bihu, Baisakhi all thank nature at harvest time but sit in four different corners of India.'),
    h('3. Why it matters'),
    p('Festival–state matching appears constantly in the Culture section of GA.'),
    h('4. Association map'),
    li(['Pongal → pongal pot boiling over in a Tamil home', 'Onam → pookalam flower carpet in Kerala', 'Bihu → Bihu dance in Assam’s fields', 'Baisakhi → bhangra in Punjab’s wheat fields']),
    trap('Onam–Kerala vs Pongal–Tamil Nadu — the most-swapped neighbours.'),
    mem('Boiling pot geography', 'Going down the map: Punjab Baisakhi → Assam Bihu → TN Pongal → Kerala Onam. Four corners, four harvests.'),
    rec('Pongal TN · Onam Kerala · Bihu Assam · Baisakhi Punjab.'),
  ],
  { text: 'Onam is the main harvest festival of:', options: ['Tamil Nadu', 'Karnataka', 'Kerala', 'Andhra Pradesh'], answer: 2,
    steps: ['Onam = Kerala (Mahabali legend, pookalam).', 'Pongal = Tamil Nadu.'] },
  ['q-gk-4']),

/* -------- Personalities -------- */
C('g-pe-nobel', 'personalities', 'Indian Nobel Personalities',
  'Raman 1930, Tagore 1913, Mother Teresa 1979, Kailash Satyarthi 2014.',
  [
    h('1. The facts'),
    T(['Person', 'Nobel (year)', 'Field'], [
      ['Rabindranath Tagore', '1913', 'Literature (Gitanjali) — first Indian Nobel'],
      ['C.V. Raman', '1930', 'Physics (Raman effect)'],
      ['Mother Teresa', '1979', 'Peace'],
      ['Amartya Sen', '1998', 'Economics'],
      ['Kailash Satyarthi', '2014', 'Peace (with Malala Yousafzai)'],
      ['Har Gobind Khorana', '1968', 'Medicine (genetic code; Indian-born)'],
    ]),
    h('2. Context'),
    p('C.V. Raman discovered the Raman effect (light scattering) — 28 February is celebrated as National Science Day for it.'),
    h('3. Why it matters'),
    p('“First Indian Nobel laureate” (Tagore) and “first Indian SCIENCE Nobel” (Raman) are two different questions — exams test exactly that difference.'),
    h('4. Association map'),
    li(['Tagore 1913 → also wrote the national anthem', 'Raman 1930 → 28 Feb National Science Day', 'Satyarthi 2014 → shared with Malala']),
    trap('First Indian Nobel = Tagore (1913, literature) — NOT Raman. Raman = first in the SCIENCES.'),
    mem('Anthem→Nobel chain', 'The man who wrote the anthem (Tagore) won the first Nobel; the light-scatterer (Raman) won the science one — 1913 vs 1930.'),
    rec('Tagore 1913 lit · Raman 1930 physics · Teresa 1979 peace · Sen 1998 economics.'),
  ],
  { text: 'Who was the first Indian to receive a Nobel Prize?', options: ['C.V. Raman', 'Rabindranath Tagore', 'Mother Teresa', 'S. Chandrasekhar'], answer: 1,
    steps: ['Tagore won Literature in 1913 for Gitanjali.', 'Raman (1930) was first in the sciences.'] },
  ['q-gk-5']),

/* -------- Economics -------- */
C('g-ec-rbi', 'economics', 'RBI and Banking Basics',
  'RBI est. 1935; currency authority; repo rate is its key tool.',
  [
    h('1. The facts'),
    T(['Fact', 'Detail'], [
      ['RBI established', '1 April 1935 (Hilton Young Commission); nationalised 1949'],
      ['RBI headquarter', 'Mumbai'],
      ['Currency notes', 'issued by RBI (₹1 note by Government of India)'],
      ['Repo rate', 'rate at which RBI lends to banks (key policy rate)'],
      ['GST', 'launched 1 July 2017 (“one nation, one tax”)'],
      ['Union Budget', 'presented on 1 February'],
    ]),
    h('2. Context'),
    p('The RBI is the central bank: it issues currency, manages government accounts, controls money supply and supervises all banks.'),
    h('3. Why it matters'),
    p('Banking basics (RBI, repo, GST dates) are stable GA questions that do not change from year to year — high return on memory.'),
    h('4. Association map'),
    li(['1935 RBI born → 1949 nationalised', 'Repo = RBI lends to banks (remember “rePO = RBI gives”)', 'Fiscal year 1 April–31 March; Budget 1 February']),
    trap('Repo (RBI lends to banks) vs Reverse repo (RBI borrows from banks) — direction is everything.'),
    mem('RePO direction', '“Repo — RBI Provides.” Reverse repo — RBI Receives. P for provides, R for receives.'),
    rec('RBI 1935 Mumbai · ₹ notes by RBI · GST 1 July 2017 · Budget 1 Feb.'),
  ],
  { text: 'The Reserve Bank of India was established in:', options: ['1947', '1935', '1949', '1950'], answer: 1,
    steps: ['RBI was set up in 1935 and nationalised in 1949.'] },
  ['q-gk-6']),

/* -------- Politics -------- */
C('g-po-const', 'politics', 'Constitution of India — Core Facts',
  'Adopted 26 Nov 1949; in force 26 Jan 1950; Ambedkar chaired drafting.',
  [
    h('1. The facts'),
    T(['Fact', 'Detail'], [
      ['Adopted', '26 November 1949'],
      ['Came into force', '26 January 1950'],
      ['Drafting Committee chairman', 'Dr B.R. Ambedkar'],
      ['Length', 'longest written constitution of any sovereign country'],
      ['Borrowed ideas', 'UK (parliamentary), US (fundamental rights), Ireland (directive principles), Canada (strong centre)'],
      ['Voting age', '18 (61st Amendment, 1989)'],
    ]),
    h('2. Context'),
    p('The Constituent Assembly took 2 years, 11 months, 18 days. 26 November is celebrated as Constitution Day (Samvidhan Divas).'),
    h('3. Why it matters'),
    p('Dates, chairmen and borrowed features are the three most repeated polity questions in RRB exams.'),
    h('4. Association map'),
    li(['26 Nov 1949 adopted → 26 Jan 1950 force (Republic Day)', 'Ambedkar → “Father of the Indian Constitution”', '61st Amendment → 18 years voting age']),
    trap('Adopted (26 Nov 1949) vs in force (26 Jan 1950) — a two-month gap the exam loves.'),
    mem('Nov→Jan chain', 'Signed in November winter, born on January Republic morning — 1949 adopted, 1950 alive.'),
    rec('26 Nov 1949 adopted · 26 Jan 1950 force · Ambedkar chairman.'),
  ],
  { text: 'The Constitution of India came into force on:', options: ['15 August 1947', '26 November 1949', '26 January 1950', '2 October 1950'], answer: 2,
    steps: ['Adopted 26 Nov 1949; came into FORCE 26 Jan 1950 (Republic Day).'] },
  ['q-gk-7']),

/* -------- Other important: national symbols -------- */
C('g-ot-symbols', 'other-important', 'National Symbols of India',
  'Tiger, peacock, lotus, mango, banyan — one mark, must-know.',
  [
    h('1. The facts'),
    T(['Symbol', 'Item'], [
      ['National animal', 'Royal Bengal Tiger'],
      ['National bird', 'Indian Peacock (Peafowl)'],
      ['National flower', 'Lotus'],
      ['National fruit', 'Mango'],
      ['National tree', 'Banyan'],
      ['National anthem', 'Jana Gana Mana — Rabindranath Tagore (~52 seconds)'],
      ['National song', 'Vande Mataram — Bankim Chandra Chattopadhyay'],
      ['National aquatic animal', 'Ganges River Dolphin'],
      ['National heritage animal', 'Elephant'],
      ['Flag designer', 'Pingali Venkayya'],
    ]),
    h('2. Context'),
    p('The anthem was adopted in its Hindi version by the Constituent Assembly on 24 January 1950, alongside the song Vande Mataram.'),
    h('3. Why it matters'),
    p('This is the single most reliable GA cluster — pure recall, no logic needed.'),
    h('4. Association map'),
    li(['Anthem AND first Nobel literature — Tagore did both', 'Vande Mataram → from Bankim’s novel Anandamath', 'River dolphin → also “national aquatic animal” of the Ganga story']),
    trap('Anthem (Jana Gana Mana, Tagore) vs National SONG (Vande Mataram, Bankim) — the classic swap.'),
    mem('Temple pond picture', 'One pond: lotus floating, peacock drinking at the edge, tiger behind the banyan, mangoes fallen under it — one image, six symbols.'),
    rec('Tiger · peacock · lotus · mango · banyan · dolphin(aquatic) · elephant(heritage).'),
  ],
  { text: 'The national flower of India is the:', options: ['Rose', 'Lotus', 'Jasmine', 'Sunflower'], answer: 1,
    steps: ['Lotus is the national flower.'] },
  ['q-gk-8']),

C('g-ot-days', 'other-important', 'Important Days — The Exam Dozen',
  'Fixed-date days that appear again and again.',
  [
    h('1. The facts'),
    T(['Date', 'Day'], [
      ['26 January', 'Republic Day'],
      ['2 October', 'Gandhi Jayanti'],
      ['14 November', 'Children’s Day (Nehru’s birthday)'],
      ['5 September', 'Teachers’ Day (Dr S. Radhakrishnan)'],
      ['29 August', 'National Sports Day (Dhyan Chand)'],
      ['21 June', 'International Yoga Day'],
      ['10 December', 'Human Rights Day'],
      ['5 June', 'World Environment Day'],
      ['8 March', 'International Women’s Day'],
      ['15 September', 'Engineers’ Day (M. Visvesvaraya)'],
    ]),
    h('2. Context'),
    p('Most “important days” are birthdays of great Indians: Nehru → Children’s Day, Radhakrishnan → Teachers’ Day, Dhyan Chand → Sports Day, Visvesvaraya → Engineers’ Day.'),
    h('3. Why it matters'),
    p('One direct question in most GA sections. The birthday logic halves the memorisation.'),
    h('4. Association map'),
    li(['Nehru = Chacha → Children', 'Radhakrishnan = teacher-president → Teachers', 'Dhyan Chand = hockey wizard → Sports', 'Visvesvaraya = engineer of dams → Engineers']),
    trap('5 September (Teachers) vs 14 November (Children) — both Nehru-family-adjacent days.'),
    mem('Birthday ladder', 'Chacha Nehru loved children (14 Nov); his teacher-president friend Radhakrishnan took 5 Sep; the hockey wizard took 29 Aug.'),
    rec('26 Jan, 2 Oct, 14 Nov, 5 Sep, 29 Aug, 21 Jun, 10 Dec.'),
  ],
  { text: 'National Sports Day in India is celebrated on:', options: ['5 September', '29 August', '21 June', '2 October'], answer: 1,
    steps: ['29 August — Major Dhyan Chand’s birthday.'] },
  ['q-gk-9']),

C('g-ot-firsts', 'other-important', 'First in India — Persons',
  'First President, first woman PM, first Indian in space.',
  [
    h('1. The facts'),
    T(['First…', 'Person'], [
      ['President of India', 'Dr Rajendra Prasad'],
      ['Prime Minister', 'Jawaharlal Nehru'],
      ['Woman Prime Minister', 'Indira Gandhi'],
      ['Indian in space', 'Rakesh Sharma (1984)'],
      ['Indian woman in space (Indian-born)', 'Kalpana Chawla'],
      ['Field Marshal', 'Sam Manekshaw'],
      ['Nobel laureate', 'Rabindranath Tagore'],
      ['Woman President', 'Pratibha Patil'],
      ['Home Minister', 'Sardar Vallabhbhai Patel'],
    ]),
    h('2. Context'),
    p('These “firsts” cover the freedom-era leadership and modern achievements — two high-frequency clusters in one table.'),
    h('3. Why it matters'),
    p('Direct one-mark questions with zero calculation — pure memory ROI.'),
    h('4. Association map'),
    li(['Prasad = first President (P-P)', 'Patil = first WOMAN President (also P!)', 'Kalpana Chawla → NASA, Space Shuttle Columbia']),
    trap('First President (Rajendra Prasad) vs first WOMAN President (Pratibha Patil, 2007) — the qualifier is the question.'),
    mem('Double-P trick', 'Prasad and Patil — the two P-presidents: Prasad first overall, Patil first woman.'),
    rec('Prasad 1st President · Nehru 1st PM · Indira 1st woman PM · Rakesh Sharma 1st in space.'),
  ],
  { text: 'Who was the first President of India?', options: ['Jawaharlal Nehru', 'Dr Rajendra Prasad', 'S. Radhakrishnan', 'Dr B.R. Ambedkar'], answer: 1,
    steps: ['Dr Rajendra Prasad was the first President (served 1950–1962).', 'Nehru was the first PRIME MINISTER.'] },
  ['q-gk-10']),

C('g-ot-books', 'other-important', 'Books and Authors — Frequent Five',
  'Discovery of India, Gitanjali, Wings of Fire, My Experiments with Truth.',
  [
    h('1. The facts'),
    T(['Book', 'Author'], [
      ['Discovery of India', 'Jawaharlal Nehru'],
      ['Gitanjali', 'Rabindranath Tagore'],
      ['Wings of Fire', 'A.P.J. Abdul Kalam (autobiography)'],
      ['The Story of My Experiments with Truth', 'M.K. Gandhi (autobiography)'],
      ['Anandamath', 'Bankim Chandra Chattopadhyay (contains Vande Mataram)'],
    ]),
    h('2. Context'),
    p('Freedom-era writing is the core cluster: two autobiographies (Gandhi, Kalam), one Nobel poetry collection, one history classic.'),
    h('3. Why it matters'),
    p('Book–author matching is a stable, repeating GA question type.'),
    h('4. Association map'),
    li(['Nehru wrote Discovery from jail', 'Tagore’s Gitanjali won the 1913 Nobel', 'Kalam the rocket scientist has “Wings” of fire', 'Anandamath gave the national song']),
    trap('Wings of Fire = KALAM. Gandhi’s autobiography has the long name with “Experiments”.'),
    mem('Wings/rocket hook', 'Rocket man writes about WINGS; the Mahatma writes about EXPERIMENTS with truth.'),
    rec('Discovery–Nehru · Gitanjali–Tagore · Wings–Kalam · Experiments–Gandhi.'),
  ],
  { text: '“Wings of Fire” is the autobiography of:', options: ['Mahatma Gandhi', 'A.P.J. Abdul Kalam', 'Jawaharlal Nehru', 'Rabindranath Tagore'], answer: 1,
    steps: ['Wings of Fire = Dr A.P.J. Abdul Kalam.'] },
  ['q-gk-11']),
];

export const gkQuestions = [
Q('q-gk-1', 'science-technology', { conceptId: 'g-st-space', text: 'ISRO was established in the year:', options: ['1947', '1962', '1969', '1975'], answer: 2, difficulty: 1,
  tests: 'ISRO founding year.', solution: ['ISRO was founded in 1969 under Dr Vikram Sarabhai.', '1975 = Aryabhata satellite.'],
  wrongWhy: ['Independence year.', 'INCOSPAR year (1962) — close but not ISRO.', 'Correct.', 'Aryabhata year.'],
  trap: '1962 INCOSPAR vs 1969 ISRO.', memory: { tech: 'Moon-landing year hook', x: 'ISRO 1969 — the same year humans first walked on the Moon.' }, recall: 'ISRO 1969.' }),

Q('q-gk-2', 'sports', { conceptId: 'g-sp-olympic', text: 'India has won the most Olympic gold medals in which sport?', options: ['Cricket', 'Hockey', 'Shooting', 'Wrestling'], answer: 1, difficulty: 1,
  tests: 'India’s hockey legacy.', solution: ['India has 8 Olympic hockey golds (first in 1928).'],
  wrongWhy: ['Cricket is not an Olympic medal sport for India.', 'Correct.', 'One gold (Bindra 2008).', 'No golds in wrestling.'],
  trap: 'Hockey, not cricket, is India’s Olympic story.', memory: { tech: 'Dhyan Chand era', x: '1928–1956 golden hockey run.' }, recall: '8 hockey golds, first 1928.' }),

Q('q-gk-3', 'culture', { conceptId: 'g-cu-dance', text: 'Kathakali is a classical dance form of:', options: ['Kerala', 'Tamil Nadu', 'Karnataka', 'Assam'], answer: 0, difficulty: 1,
  tests: 'Dance–state matching.', solution: ['Kathakali = Kerala (along with Mohiniyattam).'],
  wrongWhy: ['Correct.', 'TN = Bharatanatyam.', 'Karnataka = Yakshagana (not classical list).', 'Assam = Sattriya.'],
  trap: 'Kathak (UP) vs Kathakali (Kerala).', memory: { tech: 'Green-face hook', x: 'KathakALI’s green ALI paint → Kerala.' }, recall: 'Kathakali–Kerala.' }),

Q('q-gk-4', 'culture', { conceptId: 'g-cu-fest', text: 'Bihu, the harvest festival, is celebrated in:', options: ['Punjab', 'Assam', 'Kerala', 'Gujarat'], answer: 1, difficulty: 1,
  tests: 'Festival–state matching.', solution: ['Bihu = Assam (April).'],
  wrongWhy: ['Punjab = Baisakhi.', 'Correct.', 'Kerala = Onam.', 'Gujarat = Navratri.'],
  trap: 'Bihu (Assam) vs Baisakhi (Punjab) — both April harvests.', memory: { tech: 'B-map', x: 'Baisakhi west (Punjab), Bihu east (Assam).' }, recall: 'Bihu–Assam.' }),

Q('q-gk-5', 'personalities', { conceptId: 'g-pe-nobel', text: 'C.V. Raman received the Nobel Prize in 1930 for his work in:', options: ['Literature', 'Peace', 'Physics', 'Medicine'], answer: 2, difficulty: 1,
  tests: 'Nobel fields.', solution: ['Raman effect (light scattering) → Physics, 1930.'],
  wrongWhy: ['Tagore won literature.', 'Mother Teresa won peace.', 'Correct.', 'No Indian medicine Nobel in 1930.'],
  trap: 'Raman = Physics; Tagore = Literature.', memory: { tech: 'Light scatter hook', x: 'Raman scattered LIGHT, won PHYSICS.' }, recall: 'Raman 1930 physics.' }),

Q('q-gk-6', 'economics', { conceptId: 'g-ec-rbi', text: 'The repo rate is the rate at which:', options: ['banks lend to customers', 'RBI lends money to banks', 'RBI borrows from banks', 'government borrows from RBI'], answer: 1, difficulty: 2,
  tests: 'Repo rate definition.', solution: ['Repo = RBI lends to commercial banks against securities.', 'Reverse repo = RBI borrows.'],
  wrongWhy: ['That is bank lending rate (linked, but not repo).', 'Correct.', 'That is reverse repo.', 'That describes government borrowing (G-secs).'],
  trap: 'Repo direction: RBI → banks.', memory: { tech: 'RePO direction', x: 'Repo — RBI Provides.' }, recall: 'Repo: RBI lends to banks.' }),

Q('q-gk-7', 'politics', { conceptId: 'g-po-const', text: 'Who chaired the Drafting Committee of the Indian Constitution?', options: ['Jawaharlal Nehru', 'Dr B.R. Ambedkar', 'Rajendra Prasad', 'Sardar Patel'], answer: 1, difficulty: 1,
  tests: 'Constitution makers.', solution: ['Dr B.R. Ambedkar chaired the Drafting Committee.', 'Rajendra Prasad presided over the Constituent Assembly.'],
  wrongWhy: ['Nehru headed other committees.', 'Correct.', 'Prasad was Assembly President.', 'Patel handled integration/provincial committees.'],
  trap: 'Assembly President (Prasad) vs Drafting chairman (Ambedkar).', memory: { tech: 'Architect label', x: 'Ambedkar = chief architect of the Constitution.' }, recall: 'Ambedkar — drafting chairman.' }),

Q('q-gk-8', 'other-important', { conceptId: 'g-ot-symbols', text: 'The national aquatic animal of India is the:', options: ['Blue whale', 'Ganges river dolphin', 'Olive Ridley turtle', 'King cobra'], answer: 1, difficulty: 2,
  tests: 'National symbols.', solution: ['Ganges River Dolphin — declared national aquatic animal (2009/2010 decisions).'],
  wrongWhy: ['Not chosen.', 'Correct.', 'Sea turtle, but not the pick.', 'Reptile, not aquatic animal choice.'],
  trap: 'Aquatic (dolphin) vs heritage (elephant) animal.', memory: { tech: 'Ganga pair', x: 'Ganga’s dolphin = national aquatic animal.' }, recall: 'River dolphin.' }),

Q('q-gk-9', 'other-important', { conceptId: 'g-ot-days', text: 'International Yoga Day is celebrated on:', options: ['21 June', '5 June', '10 December', '8 March'], answer: 0, difficulty: 1,
  tests: 'Important days.', solution: ['21 June — the summer solstice, adopted by the UN in 2014 (first celebrated 2015).'],
  wrongWhy: ['Correct.', '5 June = Environment Day.', '10 Dec = Human Rights Day.', '8 March = Women’s Day.'],
  trap: '5 June (environment) vs 21 June (yoga).', memory: { tech: 'Longest-day hook', x: 'Yoga on the longest day of light — 21 June.' }, recall: 'Yoga 21 June.' }),

Q('q-gk-10', 'other-important', { conceptId: 'g-ot-firsts', text: 'The first Indian to travel into space was:', options: ['Kalpana Chawla', 'Rakesh Sharma', 'Sunita Williams', 'Vikram Sarabhai'], answer: 1, difficulty: 1,
  tests: 'First in India — space.', solution: ['Rakesh Sharma, 1984, aboard the Soviet Soyuz T-11.'],
  wrongWhy: ['Chawla went later (1997).', 'Correct.', 'Sunita Williams is Indian-American, later still.', 'Sarabhai was the founder, not an astronaut.'],
  trap: 'Rakesh Sharma (1984, Indian) vs Kalpana Chawla (Indian-born American astronaut).', memory: { tech: 'Saare Jahan reply', x: '“Saare Jahan Se Achha” — Rakesh Sharma’s famous reply from space.' }, recall: 'Rakesh Sharma 1984.' }),

Q('q-gk-11', 'other-important', { conceptId: 'g-ot-books', text: '“Anandamath”, the novel that contains the song Vande Mataram, was written by:', options: ['Rabindranath Tagore', 'Bankim Chandra Chattopadhyay', 'Sarat Chandra Chatterjee', 'Premchand'], answer: 1, difficulty: 2,
  tests: 'Books and authors.', solution: ['Bankim Chandra Chattopadhyay wrote Anandamath (1882).'],
  wrongWhy: ['Tagore wrote Gitanjali.', 'Correct.', 'Different Bengali novelist.', 'Hindi novelist.'],
  trap: 'National song source = Anandamath, not Tagore.', memory: { tech: 'Song-source link', x: 'Vande Mataram lives INSIDE Anandamath — Bankim wrote both.' }, recall: 'Anandamath — Bankim Chandra.' }),
];
