/* Starter Pack — MATHEMATICS part 2 (Mensuration → Pipes and Cistern) */
import { h, p, li, F, NR, E, T, trap, mem, rec, st, note, sub, STARTER_REF } from './_shared.js';
const C = sub('MATH').concept;
const M = sub('MATH').method;
const Q = sub('MATH').q;

export const math2Concepts = [

/* ================= MENSURATION ================= */
C('m-me-1', 'mensuration', 'Perimeter and Area of Simple Shapes',
  'Perimeter = border length. Area = space inside.',
  [
    h('1. What is this?'),
    p('Mensuration is measuring shapes. PERIMETER is the distance around the border (fencing a field). AREA is the space inside (tiles or carpet needed).'),
    F('Square:  Area = a²     Perimeter = 4a\nRectangle: Area = l × b     Perimeter = 2(l + b)\nTriangle: Area = ½ × base × height\nCircle: Area = πr²     Circumference = 2πr', [
      ['a', 'side of the square'],
      ['l, b', 'length and breadth of the rectangle'],
      ['base, height', 'triangle base and the perpendicular height'],
      ['r', 'radius of the circle'],
      ['π', '22/7 ≈ 3.14'],
    ]),
    E('Solved example — a room is 6 m long and 4 m wide', [
      'Area = 6 × 4 = 24 m² (floor space).',
      'Perimeter = 2(6 + 4) = 20 m (skirting/wire needed).',
    ], 'Area 24 m², perimeter 20 m'),
    h('2. How to recognize this question'),
    li(['“Find the area / perimeter of …”', '“How much fencing does a field need?” → perimeter', '“How many tiles / how much carpet?” → area', '“A path runs around a park …” → subtract inner from outer area.']),
    st(['Identify the shape.', 'Write the formula (do not mix area and perimeter formulas).', 'Put in the values with correct units.', 'Area units are SQUARE (m², cm²); perimeter units are plain (m, cm).']),
    trap('Saying “area 20 m” or “perimeter 24 m²”. Area is always squared units; perimeter is never squared.'),
    mem('Visual association', 'Perimeter = you walk AROUND the shape. Area = you PAINT INSIDE the shape.'),
    rec('Square a², 4a · Rect lb, 2(l+b) · Triangle ½bh · Circle πr², 2πr.'),
  ],
  { text: 'A square garden has a side of 7 m. Find its area.', options: ['14 m²', '28 m²', '49 m²', '44 m²'], answer: 2,
    steps: ['Area of square = a²', '= 7 × 7 = 49 m².'] },
  ['q-me-1'], { generators: ['g-me-rect'] }),

C('m-me-2', 'mensuration', 'Volume of Solids (Cube, Cuboid, Cylinder)',
  'Volume = 3D space inside; measured in cubic units.',
  [
    h('1. What is this?'),
    p('Volume is how much a 3D solid can hold — water in a tank, sand in a box.'),
    F('Cube: V = a³\nCuboid: V = l × b × h\nCylinder: V = πr²h', [
      ['a', 'edge of the cube'],
      ['l, b, h', 'length, breadth, height of the cuboid'],
      ['r, h', 'radius and height of the cylinder'],
    ]),
    E('Solved example — a tank 5 m × 4 m × 3 m', [
      'V = 5 × 4 × 3 = 60 m³.',
      '1 m³ = 1000 litres → the tank holds 60,000 litres.',
    ], '60 m³ = 60,000 L'),
    h('2. Unit ladder (genuine time saver)'),
    li(['1 m³ = 1000 litres', '1 litre = 1000 cm³', '1 cm³ = 1 mL']),
    h('3. How to recognize this question'),
    li(['“How much water does a tank hold?”', '“Find the volume of a box…”', '“How many cubes of side 2 cm fit in a box…” → big volume ÷ small volume.']),
    trap('Using an area formula (l×b) for volume. Volume needs THREE lengths multiplied.'),
    mem('If X, then Y', 'If the question says “how much does it HOLD” → volume (3 lengths). If “how much surface” → area (2 lengths).'),
    rec('Cube a³, cuboid lbh, cylinder πr²h. 1 m³ = 1000 L.'),
  ],
  { text: 'Find the volume of a cuboid 8 cm × 5 cm × 2 cm.', options: ['15 cm³', '26 cm³', '40 cm³', '80 cm³'], answer: 3,
    steps: ['V = l × b × h', '= 8 × 5 × 2 = 80 cm³.'] },
  ['q-me-2']),

/* ================= TIME AND WORK ================= */
C('m-tw-1', 'time-work', 'Time and Work — One Day’s Work Method',
  'Turn days into rates: 12 days = 1/12 work per day.',
  [
    h('1. What is this?'),
    p('If a person finishes a job in 12 days, in ONE day they do 1/12 of the job. Rates of work ADD when people work together.'),
    F('Time = n days  ⟹  one day’s work = 1/n', [
      ['n', 'days one person alone needs for the whole job'],
      ['1/n', 'fraction of the job done per day'],
    ], 'Together: (1/a + 1/b + …) per day. Total time = 1 ÷ (sum of rates).'),
    E('Solved example — A does a job in 10 days, B in 15 days. Together?', [
      'A per day = 1/10, B per day = 1/15.',
      'Together per day = 1/10 + 1/15 = 3/30 + 2/30 = 5/30 = 1/6.',
      'So together they need 6 days.',
    ], '6 days'),
    h('2. How to recognize this question'),
    li(['“A can do a work in 12 days, B in 18 days. Together?”', '“A and B together in 8 days, A alone in 12 — B alone?” (subtract rates)']),
    st(['Convert each person’s time to a rate (1/days).', 'Add the rates (or subtract, if removing someone).', 'Flip the total rate to get days.']),
    trap('Adding the DAYS (12 + 18 = 30 ✗). Always convert to rates first, add rates, then flip.'),
    mem('LMD rule (Tanglish)', '“LLast Munnadi Divide” — 1/days first, then Merge, then Divide-flip: 1/10+1/15 = 1/6 → 6 days.'),
    rec('Time n → rate 1/n. Add rates. Answer = 1 ÷ total rate.'),
  ],
  { text: 'A can finish a work in 12 days and B in 18 days. Working together, how many days will they take?', options: ['7.2 days', '7.5 days', '15 days', '30 days'], answer: 0,
    steps: ['Rates: 1/12 + 1/18 = 3/36 + 2/36 = 5/36 per day.', 'Time = 36/5 = 7.2 days.'] },
  ['q-tw-1'], { generators: ['g-tw'] }),

/* ================= TIME AND DISTANCE ================= */
C('m-td-1', 'time-distance', 'Speed, Time and Distance',
  'Speed = Distance ÷ Time. Fix the units first.',
  [
    h('1. What is this?'),
    p('The three quantities distance, speed and time are tied by one formula. Most mistakes happen only in UNITS.'),
    F('Speed = Distance ÷ Time\nDistance = Speed × Time\nTime = Distance ÷ Speed', [
      ['Distance', 'in km or m'],
      ['Speed', 'km/h (kmph) or m/s'],
      ['Time', 'hours or seconds'],
    ]),
    E('Tiny example — 180 km at 60 km/h', ['Time = 180 ÷ 60 = 3 hours.']),
    F('km/h → m/s: multiply by 5/18\nm/s → km/h: multiply by 18/5', [
      ['5/18', 'use when converting km/h INTO m/s'],
    ], '60 km/h = 60 × 5/18 = 16.67 m/s.'),
    h('2. Average speed'),
    p('Average speed = TOTAL distance ÷ TOTAL time — NOT the average of the two speeds.'),
    E('Solved example — 120 km at 60 km/h, then 120 km at 40 km/h', [
      'Times: 120/60 = 2 h and 120/40 = 3 h.',
      'Total: 240 km in 5 h.',
      'Average = 240 ÷ 5 = 48 km/h (not (60+40)/2 = 50).',
    ], '48 km/h'),
    h('3. How to recognize this question'),
    li(['“A train covers 240 km in 4 hours — speed?”', '“Convert 90 km/h into m/s.”', '“A man walks at 5 km/h for 30 minutes — distance?”']),
    trap('Averaging the two speeds when distances are equal — wrong; use total ÷ total. Also: 30 minutes is 0.5 hour, not 30!'),
    mem('Triangle trick', 'Draw a triangle: D on top, S and T below. Cover the one you want: D = S×T, S = D/T, T = D/S.'),
    rec('D = S × T. km/h → m/s × 5/18. Average = total ÷ total.'),
  ],
  { text: 'A train runs at 72 km/h. What is its speed in m/s?', options: ['18 m/s', '20 m/s', '25.2 m/s', '36 m/s'], answer: 1,
    steps: ['72 × 5/18 = 72 × 5 ÷ 18', '= 360 ÷ 18 = 20 m/s.'] },
  ['q-td-1'], { generators: ['g-td'] }),

/* ================= SIMPLE INTEREST ================= */
C('m-si-1', 'simple-interest', 'Simple Interest (SI)',
  'Rent money on the original amount only.',
  [
    h('1. What is this?'),
    p('When you borrow money, you pay EXTRA for the time you keep it. In SIMPLE interest, that extra is calculated on the ORIGINAL amount every year — it does not grow.'),
    F('SI = (P × R × T) ÷ 100', [
      ['P', 'Principal — the money borrowed/deposited'],
      ['R', 'Rate percent per year'],
      ['T', 'Time in YEARS'],
      ['SI', 'the interest (extra money)'],
      ['Amount', 'P + SI (what you pay back in total)'],
    ]),
    E('Solved example — ₹5,000 at 6% per year for 2 years', [
      'SI = 5000 × 6 × 2 ÷ 100',
      '= 5000 × 12 ÷ 100 = ₹600.',
      'Amount = 5000 + 600 = ₹5,600.',
    ], 'SI ₹600, Amount ₹5,600'),
    h('2. How to recognize this question'),
    li(['“Find the simple interest on ₹… at …% for … years”', '“In how many years will a sum double at 8% p.a.?” (need SI = P → T = 100/R)']),
    st(['Write P, R, T from the question (convert months to years: 6 months = 0.5).', 'Apply SI = PRT/100.', 'If asked “amount”, add P back.']),
    trap('Forgetting to convert months into years, and forgetting to add P for the final amount.'),
    mem('PRT story', '“Pandi Ran Two” laps — P, R, T multiplied, divided by 100. Pandi = Principal, Ran = Rate, Two = Time.'),
    rec('SI = PRT/100. Amount = P + SI.'),
  ],
  { text: 'Find the simple interest on ₹8,000 at 5% per year for 3 years.', options: ['₹1,200', '₹1,250', '₹1,2000', '₹400'], answer: 0,
    steps: ['SI = 8000 × 5 × 3 / 100', '= 8000 × 15/100 = ₹1,200.'] },
  ['q-si-1'], { generators: ['g-si'] }),

/* ================= COMPOUND INTEREST ================= */
C('m-ci-1', 'compound-interest', 'Compound Interest (CI)',
  'Interest on interest — the amount grows every year.',
  [
    h('1. What is this?'),
    p('In COMPOUND interest, each year’s interest is added to the pot, and next year’s interest is calculated on the bigger pot. The debt/savings grow faster.'),
    F('Amount A = P × (1 + R/100)ᵀ\nCI = A − P', [
      ['P', 'principal'],
      ['R', 'rate % per compounding period'],
      ['T', 'number of periods (years if yearly)'],
      ['A', 'final amount'],
    ]),
    E('Solved example — ₹10,000 at 10% for 2 years (yearly)', [
      'Year 1: 10,000 → 11,000.',
      'Year 2: 11,000 → 12,100.',
      'A = 12,100, CI = 2,100 (SI would be only 2,000).',
    ], 'CI ₹2,100'),
    h('2. Two-year shortcut (genuinely useful)'),
    F('Effective 2-year rate for r% yearly = r + r + r²/100', [['r', 'yearly rate %']],
      'Example: 10% → 10 + 10 + 1 = 21% total in 2 years.'),
    h('3. How to recognize this question'),
    li(['“compounded annually / half-yearly”', '“A sum doubles in 8 years at CI — in how many years 4 times?” (2× time → 16 years)']),
    trap('Half-yearly compounding: R must be halved and T doubled before using the formula.'),
    mem('Snowball visual', 'SI = a ladder (same step each year). CI = a snowball (each year’s ball is bigger, so the added layer is thicker).'),
    rec('A = P(1+R/100)ᵀ; CI = A − P. 2-year shortcut: r+r+r²/100.'),
  ],
  { text: 'Find the compound interest on ₹10,000 at 10% per year for 2 years.', options: ['₹2,000', '₹2,100', '₹1,000', '₹2,200'], answer: 1,
    steps: ['A = 10,000 × (1.1)² = 10,000 × 1.21 = 12,100.', 'CI = 12,100 − 10,000 = ₹2,100.'] },
  ['q-ci-1'], { generators: ['g-ci'] }),

/* ================= PROFIT AND LOSS ================= */
C('m-pl-1', 'profit-loss', 'Profit and Loss Basics',
  'Profit = SP − CP; always compare with CP.',
  [
    h('1. What is this?'),
    p('CP = cost price (what the shopkeeper paid). SP = selling price (what they sold it for). SP > CP → profit; SP < CP → loss.'),
    F('Profit % = (SP − CP) ÷ CP × 100\nLoss % = (CP − SP) ÷ CP × 100', [
      ['CP', 'cost price'],
      ['SP', 'selling price'],
      ['Profit/Loss %', 'ALWAYS on CP'],
    ]),
    E('Solved example — CP ₹400, SP ₹500', [
      'Profit = 500 − 400 = ₹100.',
      'Profit % = 100/400 × 100 = 25%.',
    ], '25% profit'),
    h('2. How to recognize this question'),
    li(['“A shopkeeper buys at … and sells at … — profit %?”', '“Sells at a loss of 12% — find SP.”', '“Two items sold at the same price, one at 20% profit and one at 20% loss” → always a LOSS of (20×20)/100 = 4% (same-SP trap).']),
    st(['Identify CP and SP.', 'Find profit/loss value.', 'Divide by CP (never SP) and ×100.']),
    trap('Calculating profit % on SP. The base is ALWAYS cost price. Same-SP trap: equal +x% and −x% gives net loss x²/100 %.'),
    mem('Cause → effect', 'Buying causes the cost → all comparisons start from CP. “Loss lives where the money LEFT (CP).”'),
    rec('P% = (SP−CP)/CP × 100. Same SP ±x% → loss x²/100.'),
  ],
  { text: 'An item is bought for ₹800 and sold for ₹720. Find the loss percentage.', options: ['8%', '10%', '11.11%', '80%'], answer: 1,
    steps: ['Loss = 800 − 720 = ₹80.', 'Loss % = 80/800 × 100 = 10%.'] },
  ['q-pl-1'], { generators: ['g-pl'] }),

/* ================= ALGEBRA ================= */
C('m-al-1', 'algebra', 'Simple Equations — Finding the Unknown',
  'An equation is a balance; do the same on both sides.',
  [
    h('1. What is this?'),
    p('A letter like x stands for an unknown number. Solving an equation means finding the x that makes both sides EQUAL — like a balance scale.'),
    NR('No formula needed — use this rule: whatever you do to one side, do the SAME to the other side. Undo operations in reverse order (undo + before ×).'),
    E('Solved example — solve 3x + 5 = 20', [
      'Remove +5 from both sides: 3x = 15.',
      'Divide both sides by 3: x = 5.',
      'Check: 3(5) + 5 = 20 ✓.',
    ], 'x = 5'),
    h('2. Two identities worth memorising'),
    F('(a + b)² = a² + 2ab + b²\n(a − b)² = a² − 2ab + b²\na² − b² = (a+b)(a−b)', [['a, b', 'any numbers']], 'These appear directly in exams.'),
    h('3. How to recognize this question'),
    li(['“If 2x − 7 = 11, find x.”', '“Solve for x …”', '“If x + y = 10 and x − y = 4, find x.” (add the two lines: 2x = 14 → x = 7)']),
    st(['Move number terms away from x first (+/−).', 'Then remove multipliers/dividers on x.', 'Always verify by substituting back.']),
    trap('Forgetting to do the operation on BOTH sides — the scale tips and the answer is wrong.'),
    mem('Balance visual', 'Equation = see-saw. Remove the same weight from both seats, or divide both seats equally.'),
    rec('Undo in reverse order; check by substitution.'),
  ],
  { text: 'Solve: 2x − 7 = 11', options: ['x = 2', 'x = 9', 'x = 7', 'x = 12'], answer: 1,
    steps: ['2x = 11 + 7 = 18.', 'x = 18 ÷ 2 = 9.'] },
  ['q-al-1'], { generators: ['g-al'] }),

/* ================= GEOMETRY ================= */
C('m-ge-1', 'geometry', 'Angles and Triangles — The 180° Family',
  'Angles on a line = 180°; in a triangle = 180°.',
  [
    h('1. What is this?'),
    p('An angle measures turning. A full turn = 360°, half turn (straight line) = 180°, quarter turn (right angle) = 90°.'),
    li(['Acute: less than 90° · Right: exactly 90° · Obtuse: between 90° and 180° · Straight: 180° · Reflex: more than 180°']),
    F('Triangle: A + B + C = 180°\nAngles on a straight line: sum = 180°\nAround a point: sum = 360°', [['A, B, C', 'the three interior angles of any triangle']]),
    E('Solved example — two angles of a triangle are 50° and 60°', [
      'Third = 180 − 50 − 60',
      '= 70°.',
    ], '70°'),
    h('2. Triangle types'),
    T(['Type', 'Property'], [
      ['Equilateral', 'All 3 sides equal; all angles 60°'],
      ['Isosceles', 'Two sides equal; two angles equal'],
      ['Scalene', 'No equal sides'],
      ['Right triangle', 'One angle 90° (Pythagoras: a² + b² = c²)'],
    ]),
    h('3. How to recognize this question'),
    li(['“Two angles of a triangle are … find the third.”', '“Angles on a line …”', 'Pythagoras: sides 3-4-5, 5-12-13.']),
    trap('Using 360° instead of 180° for a triangle. Only angles AROUND A POINT make 360°.'),
    mem('Association', 'Triangle = TRINITY = 3 angles sharing one flat roti of 180°. A straight line is the same roti uncut.'),
    rec('Triangle 180°, line 180°, point 360°, right angle 90°.'),
  ],
  { text: 'Two angles of a triangle are 45° and 55°. Find the third angle.', options: ['80°', '90°', '100°', '260°'], answer: 0,
    steps: ['Sum = 180°.', 'Third = 180 − 45 − 55 = 80°.'] },
  ['q-ge-1'], { generators: ['g-ge-tri'] }),

/* ================= TRIGONOMETRY ================= */
C('m-tr-1', 'trigonometry', 'Trigonometry — sin, cos, tan from Zero',
  'Ratios of sides in a RIGHT triangle.',
  [
    h('1. What is this?'),
    p('In a right-angled triangle, the sides have names: OPPOSITE (facing the angle), ADJACENT (next to it) and HYPOTENUSE (the longest side, opposite the 90°). Trigonometry is just ratios of these sides.'),
    F('sin θ = Opposite ÷ Hypotenuse\ncos θ = Adjacent ÷ Hypotenuse\ntan θ = Opposite ÷ Adjacent', [
      ['θ', 'the angle you are working with'],
      ['Opposite', 'side across from θ'],
      ['Adjacent', 'side touching θ (not the hypotenuse)'],
    ]),
    E('Tiny example — a 3-4-5 right triangle, angle at the 3-side corner', [
      'For that corner: opposite = 4? No — take angle between the 3 side and the 5 side: opposite = 3, adjacent = 4, hypotenuse = 5.',
      'sin = 3/5, cos = 4/5, tan = 3/4.',
    ]),
    h('2. Standard values (memorise)'),
    T(['Angle', 'sin', 'cos', 'tan'], [
      ['0°', '0', '1', '0'],
      ['30°', '1/2', '√3/2', '1/√3'],
      ['45°', '1/√2', '1/√2', '1'],
      ['60°', '√3/2', '1/2', '√3'],
      ['90°', '1', '0', 'not defined'],
    ]),
    h('3. How to recognize this question'),
    li(['“Find the value of sin 30° + cos 60°.” (= 1/2 + 1/2 = 1)', '“In a right triangle, sides … find tan θ.”']),
    trap('Mixing up which side is opposite. Always mark the angle FIRST, then name the sides.'),
    mem('SOH-CAH-TOA', 'S-O-H: Sin = Opp/Hyp. C-A-H: Cos = Adj/Hyp. T-O-A: Tan = Opp/Adj. Say “soh-ka-toe-ah” three times — it sticks.'),
    rec('SOH CAH TOA. sin30 = cos60 = 1/2. tan45 = 1.'),
  ],
  { text: 'Find the value of sin 30° + cos 60°.', options: ['1/2', '1', '√3/2', '0'], answer: 1,
    steps: ['sin 30° = 1/2.', 'cos 60° = 1/2.', '1/2 + 1/2 = 1.'] },
  ['q-tr-1']),

/* ================= STATISTICS ================= */
C('m-st-1', 'statistics', 'Mean, Median, Mode — Average Family',
  'Mean = share equally. Median = middle. Mode = most repeated.',
  [
    h('1. What is this?'),
    p('These three numbers each describe a list of data with ONE number.'),
    F('Mean (average) = Sum of values ÷ Count\nMedian = middle value after sorting\nMode = the most frequent value\nRange = Largest − Smallest', [
      ['Mean', 'equal-share average'],
      ['Median', 'the physical middle of the SORTED list'],
      ['Mode', 'value appearing most often'],
    ]),
    E('Solved example — data: 4, 8, 6, 10, 2', [
      'Mean = (4+8+6+10+2) ÷ 5 = 30 ÷ 5 = 6.',
      'Sort: 2, 4, 6, 8, 10 → middle = 6 (median).',
      'All values appear once → no mode.',
      'Range = 10 − 2 = 8.',
    ], 'Mean 6, Median 6'),
    h('2. Even count? Median = average of the two middle numbers'),
    E('Example — 1, 3, 5, 9', ['Middle two are 3 and 5 → median = (3+5)/2 = 4.'], 'Median 4'),
    h('3. How to recognize this question'),
    li(['“Find the mean of …”', '“The median of 7, 3, 9, 1 is …”', '“Find the mode of 2, 3, 3, 5, 2, 3 …” (mode 3)']),
    trap('Finding the median WITHOUT sorting the list first. Median always needs the sorted order.'),
    mem('Contrast trio', 'Mean = Money shared equally. Median = the man standing in the MIDDLE of a queue. Mode = the MOST popular item (mode = fashion!).'),
    rec('Mean sum÷count · Median middle of sorted · Mode most repeated · Range max−min.'),
  ],
  { text: 'Find the median of: 7, 3, 9, 1, 5', options: ['5', '7', '25', '3'], answer: 0,
    steps: ['Sort: 1, 3, 5, 7, 9.', 'Middle value = 5.'] },
  ['q-st-1', 'q-st-2'], { generators: ['g-st-mean', 'g-st-median'] }),

/* ================= SQUARE ROOT ================= */
C('m-sr-1', 'square-root', 'Squares and Square Roots',
  'Square = n×n. Square root = which number squared.',
  [
    h('1. What is this?'),
    p('Squaring multiplies a number by itself (7² = 49). The square root UNDOES it (√49 = 7).'),
    F('√(a×b) = √a × √b\n√(n²) = n', [['a, b', 'any non-negative numbers']]),
    h('2. Squares you MUST know (1 → 20)'),
    T(['n', 'n²', 'n', 'n²'], [
      ['1', '1', '11', '121'],
      ['2', '4', '12', '144'],
      ['3', '9', '13', '169'],
      ['4', '16', '14', '196'],
      ['5', '25', '15', '225'],
      ['6', '36', '16', '256'],
      ['7', '49', '17', '289'],
      ['8', '64', '18', '324'],
      ['9', '81', '19', '361'],
      ['10', '100', '20', '400'],
    ]),
    E('Solved example — √1296', [
      'Split into pairs from the right: 12 | 96.',
      'Largest square ≤ 12 is 9 (3²) → first digit 3.',
      'You need a number ending so that (30+u)×u ends in 96… quick check instead: 36² = 1296 ✓ (memorised squares).',
    ], '36'),
    h('3. How to recognize this question'),
    li(['“Find √2025” (45² = 2025)', '“√0.0081 = ?” (0.09 — two decimal places in, one out)']),
    trap('√(a+b) is NOT √a + √b. Roots do not distribute over addition.'),
    mem('Ending trick', 'Squares end only in 0,1,4,5,6,9 (never 2,3,7,8). If an option ends in 3 or 7, kill it instantly.'),
    rec('Learn squares to 20: … 35²=1225, 45²=2025, 36²=1296, 44²=1936.'),
  ],
  { text: 'Find the value of √0.0081.', options: ['0.9', '0.09', '0.009', '9'], answer: 1,
    steps: ['√81 = 9.', '0.0081 has 4 decimal places → root has 2 → 0.09.'] },
  ['q-sr-1'], { generators: ['g-sr'] }),

/* ================= AGE CALCULATIONS ================= */
C('m-age-1', 'age-calculations', 'Age Problems — Present Age = x',
  'Put present ages in x, translate sentences into equations.',
  [
    h('1. What is this?'),
    p('Age questions are just simple equations wearing a story. The one trick: time moves for EVERYONE. In 5 years, BOTH ages get +5.'),
    NR('No formula needed — use this rule: fix the PRESENT ages first (x and whatever the relation gives), then add/subtract the same years on BOTH sides of the story.'),
    E('Solved example — a father is 3 times his son. In 12 years he will be twice. Find present ages.', [
      'Son now = x, father now = 3x.',
      'In 12 years: 3x + 12 = 2(x + 12).',
      '3x + 12 = 2x + 24 → x = 12.',
      'Son 12, father 36. Check: in 12 years → 24 and 48 = twice ✓.',
    ], 'Son 12, Father 36'),
    h('2. How to recognize this question'),
    li(['“Ravi’s age after 8 years will be …”', '“The ratio of ages is 4 : 5; five years ago …”']),
    st(['Give the smallest present age the letter x.', 'Write other ages using the ratio/times given.', 'Build ONE equation from the “after n years” sentence.', 'Solve and CHECK in the story.']),
    trap('Adding years to only one person. Time passes for both father AND son.'),
    mem('Time train', 'Everyone boards the same time train — when the story says +12 years, EVERY age gets +12.'),
    rec('Present = x. Future adds to all. Check the answer inside the story.'),
  ],
  { text: 'A father is 30 years old and his son is 6. After how many years will the father be twice as old as his son?', options: ['6 years', '12 years', '18 years', '24 years'], answer: 2,
    steps: ['After y years: 30 + y = 2(6 + y).', '30 + y = 12 + 2y.', 'y = 18. Check: 48 vs 24 ✓.'] },
  ['q-age-1'], { generators: ['g-age'] }),

/* ================= CALENDAR AND CLOCK ================= */
C('m-cal-1', 'calendar-clock', 'Calendar — Odd Days and Leap Years',
  'Odd days = extra days beyond full weeks.',
  [
    h('1. What is this?'),
    p('A normal year has 365 days = 52 weeks + 1 extra day. That ONE extra day is the “odd day”. It makes the same date shift one weekday forward each normal year.'),
    li([
      'Normal year → 1 odd day. Leap year (366) → 2 odd days.',
      'Leap year: divisible by 4; century years must be divisible by 400 (2000 ✓, 1900 ✗).',
      'Century = 100 years = 76 normal + 24 leap = 124 odd days = 17 weeks + 5 odd days → 5.',
    ]),
    h('2. Month codes trick (last-digit pattern)'),
    p('Odd days per month: Jan 3 (31=4w+3), Feb 0/1, Mar 3, Apr 2, May 3, Jun 2, Jul 3, Aug 3, Sep 2, Oct 3, Nov 2, Dec 3.'),
    E('Solved example — if 1 Jan 2025 is a Wednesday, what day is 1 Jan 2026?', [
      '2025 is not a leap year → 1 odd day.',
      'Same date next year shifts by 1 weekday.',
      '1 Jan 2026 = Thursday.',
    ], 'Thursday'),
    h('3. How to recognize this question'),
    li(['“What day of the week was …?”', '“Which year will have the same calendar as …?”', '“How many odd days in …?”']),
    trap('Forgetting the February rule: in a leap year Feb has 29 days — crossing Feb 29 adds an extra odd day.'),
    mem('Odd-days story', 'Odd days are “leftover chutney” after packing full weeks (thali boxes). Leftovers decide the next weekday.'),
    rec('Normal = 1 odd, leap = 2. Same date shifts +1 (+2 after Feb 29).'),
  ],
  { text: 'The year 2024 is a leap year. How many odd days does it have?', options: ['1', '2', '0', '4'], answer: 1,
    steps: ['366 days = 52 weeks + 2 days.', 'So 2 odd days.'] },
  ['q-cal-1']),

C('m-clk-1', 'calendar-clock', 'Clock — Angle Between Hands',
  'Hour hand 0.5°/min, minute hand 6°/min.',
  [
    h('1. What is this?'),
    p('The clock hands move at different speeds. The exam asks the angle between them at a given time.'),
    F('Angle = |30H − 5.5M|', [
      ['H', 'hour (use the hour number, e.g. 3 for 3:30)'],
      ['M', 'minutes'],
      ['30H', 'degrees the hour hand is past 12 (30° per hour)'],
      ['5.5M', 'degrees of the minute hand (6°/min) MINUS the hour hand’s creep (0.5°/min)'],
    ], 'If the answer is > 180°, take 360 − answer (exams want the smaller angle).'),
    E('Solved example — angle at 3:30', [
      '30H = 30 × 3 = 90.',
      '5.5M = 5.5 × 30 = 165.',
      'Angle = |90 − 165| = 75°.',
    ], '75°'),
    h('2. How to recognize this question'),
    li(['“Find the angle between the hands at 4:20.”', '“At what time between 2 and 3 are the hands together?”']),
    trap('Using H as a fraction (3.5). Keep H as the whole hour and let the 5.5M term handle the creep of the minute hand — formula already includes it.'),
    mem('Speed pair', 'Minute hand = 6°/min (fast cyclist), hour hand = 0.5°/min (slow walker). Their gap changes 5.5° every minute — that is the 5.5 in the formula.'),
    rec('Angle = |30H − 5.5M|; if >180°, use 360 − it.'),
  ],
  { text: 'Find the angle between the hands of a clock at 4:20.', options: ['10°', '20°', '30°', '0°'], answer: 0,
    steps: ['30H = 120.', '5.5M = 110.', '|120 − 110| = 10°.'] },
  ['q-clk-1'], { generators: ['g-clk'] }),

/* ================= PIPES AND CISTERN ================= */
C('m-pc-1', 'pipes-cistern', 'Pipes and Cisterns — Fill and Empty',
  'Same as time & work; outlet pipes are negative work.',
  [
    h('1. What is this?'),
    p('A filling pipe does positive work; a draining pipe (or leak) does NEGATIVE work. Everything else is the one-day-work method.'),
    F('Fill pipe in a hours → +1/a tank per hour\nDrain pipe in b hours → −1/b tank per hour\nTogether: 1/a − 1/b per hour', [
      ['a', 'hours one inlet alone takes to FILL'],
      ['b', 'hours one outlet alone takes to EMPTY'],
    ], 'Total time = 1 ÷ (net rate).'),
    E('Solved example — pipe A fills in 12 h, drain C empties in 24 h, both open', [
      'Net rate = 1/12 − 1/24 = 2/24 − 1/24 = 1/24 per hour.',
      'Time to fill = 24 hours.',
    ], '24 hours'),
    h('2. How to recognize this question'),
    li(['“Pipe A fills a tank in …, pipe B empties it in …”', '“A leak can empty a full tank in …”', '“Two pipes fill, one drains …”']),
    st(['Convert each pipe to a rate (1/hours).', 'Inlets +, outlets −.', 'Add. Flip the net rate for the time.']),
    trap('Adding the drain’s rate instead of subtracting. OUTLET is negative work — it removes water.'),
    mem('Tanglish hook', '“Vaa pipe veesum, pora pipe pogaum” — the pipe that fills POURS (+), the pipe that drains GOES (−). Sign the pipes by direction.'),
    rec('Fill +1/a, drain −1/b, net rate → flip for time.'),
  ],
  { text: 'Pipe A fills a tank in 10 hours and pipe B fills it in 15 hours. How long together?', options: ['5 hours', '6 hours', '12.5 hours', '25 hours'], answer: 1,
    steps: ['1/10 + 1/15 = 3/30 + 2/30 = 5/30 = 1/6.', 'Time = 6 hours.'] },
  ['q-pc-1'], { generators: ['g-pc'] }),
];

export const math2Methods = [
M('si-basic', 'simple-interest', 'Model: Find SI / Rate / Time',
  'Direct use or rearrangement of SI = PRT/100.',
  'SI = P×R×T ÷ 100   ·   R = SI×100/(P×T)   ·   T = SI×100/(P×R)',
  '“Find the simple interest / rate / time” with P, R, T clearly available.',
  { text: '₹6,000 at 4% for 2.5 years → SI?', steps: ['SI = 6000×4×2.5/100', '= ₹600.'], answer: '₹600' }),
M('pl-basic', 'profit-loss', 'Model: Profit/Loss percent',
  'Compare SP with CP and divide by CP.',
  'P% = (SP−CP)/CP × 100',
  'A buy-sell story asking for percent profit or loss.',
  { text: 'CP ₹250, SP ₹300 → profit %?', steps: ['Profit 50.', '50/250 × 100 = 20%.'], answer: '20%' }),
];

export const math2Questions = [
Q('q-me-1', 'mensuration', { conceptId: 'm-me-1', text: 'A rectangular park is 30 m long and 20 m wide. A man runs around it once. How far does he run?', options: ['50 m', '100 m', '600 m', '120 m'], answer: 1, difficulty: 1,
  tests: 'Perimeter of a rectangle.', solution: ['Running around = perimeter = 2(l + b).', '= 2(30 + 20) = 100 m.'],
  wrongWhy: ['That is l + b only.', 'Correct.', 'That is the AREA.', 'Double the perimeter.'],
  trap: '“Around” = perimeter; “inside/cover” = area.', memory: { tech: 'Walk around vs paint inside', x: 'Around the border → perimeter.' }, recall: '2(l+b).' }),

Q('q-me-2', 'mensuration', { conceptId: 'm-me-2', text: 'How many litres of water fit in a cubical tank of edge 2 m?', options: ['8 litres', '800 litres', '8,000 litres', '80 litres'], answer: 2, difficulty: 2,
  tests: 'Volume + unit conversion.', solution: ['V = 2³ = 8 m³.', '1 m³ = 1000 L → 8,000 litres.'],
  wrongWhy: ['Volume in m³, not litres.', 'Missed a zero.', 'Correct.', 'Wrong conversion.'],
  trap: 'Stopping at m³ when the question asks litres.', memory: { tech: 'If X then Y', x: 'If the question says litres, convert: ×1000 per m³.' }, recall: 'V = a³; 1 m³ = 1000 L.' }),

Q('q-tw-1', 'time-work', { conceptId: 'm-tw-1', text: 'A can do a piece of work in 8 days and B in 12 days. Working together, they finish in:', options: ['4.8 days', '5 days', '6 days', '10 days'], answer: 0, difficulty: 2,
  tests: 'One-day work method.', solution: ['1/8 + 1/12 = 3/24 + 2/24 = 5/24 per day.', 'Time = 24/5 = 4.8 days.'],
  wrongWhy: ['Correct.', 'Rounding error.', 'That is the average of 8 and 12 — wrong method.', 'That is adding days.'],
  trap: 'Never average the days; add the RATES.', memory: { tech: 'Tanglish LMD', x: 'Last Munnadi Divide: rates add, then flip.' }, recall: 'Together = ab/(a+b) = 96/20 = 4.8.' }),

Q('q-td-1', 'time-distance', { conceptId: 'm-td-1', text: 'A bus covers 225 km in 4 hours 30 minutes. Its average speed is:', options: ['45 km/h', '50 km/h', '55 km/h', '60 km/h'], answer: 1, difficulty: 2,
  tests: 'Speed with time conversion.', solution: ['4 h 30 min = 4.5 hours.', 'Speed = 225 ÷ 4.5 = 50 km/h.'],
  wrongWhy: ['Used 5 hours.', 'Correct.', 'Used 4.09 hours.', 'Wrong division.'],
  trap: '30 minutes = 0.5 hour — convert before dividing.', memory: { tech: 'If X then Y', x: 'If minutes appear, convert to a decimal hour FIRST.' }, recall: 'S = D/T with T in hours.' }),

Q('q-si-1', 'simple-interest', { conceptId: 'm-si-1', methodId: 'si-basic', text: 'At what rate of simple interest per year will ₹2,000 become ₹2,400 in 4 years?', options: ['4%', '5%', '6%', '8%'], answer: 1, difficulty: 2,
  tests: 'Rearranging SI = PRT/100.', solution: ['SI = 2400 − 2000 = ₹400.', 'R = SI×100/(P×T) = 400×100/(2000×4).', '= 40000/8000 = 5%.'],
  wrongWhy: ['Misplaced 100.', 'Correct.', 'Used T = 3.', 'Divided by P only.'],
  trap: 'Amount ≠ SI. First subtract the principal.', memory: { tech: 'Formula pattern', x: 'R = 100×SI/(P×T) — the formula wheel.' }, recall: 'SI = A − P first, then R = 100SI/PT.' }),

Q('q-ci-1', 'compound-interest', { conceptId: 'm-ci-1', text: 'The difference between CI and SI on a sum at 10% for 2 years is ₹50. Find the sum.', options: ['₹2,500', '₹5,000', '₹4,000', '₹1,000'], answer: 1, difficulty: 3,
  tests: 'CI−SI difference shortcut.', solution: ['2-year difference = P(r/100)² = P(0.1)².', '0.01P = 50 → P = ₹5,000.'],
  wrongWhy: ['Check: 2500×0.01 = 25 ≠ 50.', 'Correct: 0.01 × 5000 = 50 ✓.', '40 ≠ 50.', '10 ≠ 50.'],
  trap: 'Trying to compute both interests fully — learn the shortcut P(r/100)².', memory: { tech: 'Formula pattern', x: 'CI−SI (2 yrs) = P(r/100)².' }, recall: 'Difference 2 years = P(r/100)².' }),

Q('q-pl-1', 'profit-loss', { conceptId: 'm-pl-1', methodId: 'pl-basic', text: 'A shopkeeper sells two fans at ₹1,200 each — one at 20% profit and one at 20% loss. Overall result?', options: ['No profit no loss', '4% loss', '4% profit', '2% loss'], answer: 1, difficulty: 3,
  tests: 'Same-SP trap.', solution: ['Same SP with +x% and −x% always gives a loss.', 'Loss % = x²/100 = 400/100 = 4%.'],
  wrongWhy: ['Trap! They do NOT cancel.', 'Correct: 20²/100 = 4% loss.', 'Loss never flips to profit here.', 'Formula is x²/100, not x/2.'],
  trap: 'Thinking profit and loss cancel out. They never do at the same SP.', memory: { tech: 'If X then Y', x: 'If same SP with equal +x% and −x%, then ALWAYS loss of x²/100 %.' }, recall: 'x²/100 = 4% loss.' }),

Q('q-al-1', 'algebra', { conceptId: 'm-al-1', text: 'If x + y = 12 and x − y = 4, then x² − y² = ?', options: ['24', '48', '96', '144'], answer: 1, difficulty: 2,
  tests: 'Identity a² − b² = (a+b)(a−b).', solution: ['x² − y² = (x+y)(x−y) = 12 × 4 = 48.'],
  wrongWhy: ['Half.', 'Correct.', 'Doubled.', 'That is (x+y)².'],
  trap: 'Solving for x and y the long way — spot the identity instead.', memory: { tech: 'Identity hook', x: 'See x²−y²? Instantly write (x+y)(x−y).' }, recall: 'a²−b² = (a+b)(a−b).' }),

Q('q-ge-1', 'geometry', { conceptId: 'm-ge-1', text: 'In a right-angled triangle, the two smaller angles are 35° and 55°. The third angle is:', options: ['45°', '90°', '100°', '35°'], answer: 1, difficulty: 1,
  tests: 'Angle sum in a triangle.', solution: ['Sum = 180°.', 'Third = 180 − 35 − 55 = 90° (it IS the right angle).'],
  wrongWhy: ['No.', 'Correct.', 'Exceeds the sum rule with the other two.', 'That is a given angle.'],
  trap: 'Not noticing “right-angled” was already hinted.', memory: { tech: 'Trinity 180', x: 'All three angles share one 180° roti.' }, recall: 'Triangle angles total 180°.' }),

Q('q-tr-1', 'trigonometry', { conceptId: 'm-tr-1', text: 'The value of tan 45° is:', options: ['0', '1/2', '1', '√3'], answer: 2, difficulty: 1,
  tests: 'Standard trig values.', solution: ['tan 45° = opposite/adjacent in a 45-45-90 triangle — the legs are equal → ratio 1.'],
  wrongWhy: ['That is tan 0°.', 'That is sin 30°.', 'Correct.', 'That is tan 60°.'],
  trap: 'Mixing the 30/60/45 column values.', memory: { tech: 'Table chant', x: 'tan: 0, 1/√3, 1, √3, — (for 0°,30°,45°,60°,90°).' }, recall: 'tan 45° = 1.' }),

Q('q-st-1', 'statistics', { conceptId: 'm-st-1', text: 'Find the mean of the first five natural numbers.', options: ['2', '3', '4', '5'], answer: 1, difficulty: 1,
  tests: 'Mean calculation.', solution: ['Numbers: 1, 2, 3, 4, 5.', 'Mean = 15 ÷ 5 = 3.'],
  wrongWhy: ['That is the median of 1..3.', 'Correct.', 'Not the mean.', 'That is the largest number.'],
  trap: 'Including 0 (natural numbers start at 1).', memory: { tech: 'Equal share', x: 'Mean = share the total equally.' }, recall: 'Sum ÷ count = 15/5 = 3.' }),

Q('q-st-2', 'statistics', { conceptId: 'm-st-1', text: 'Find the mode of: 3, 7, 2, 7, 5, 7, 2, 3', options: ['2', '3', '7', '5'], answer: 2, difficulty: 1,
  tests: 'Mode = most frequent.', solution: ['7 appears three times — more than any other value.'],
  wrongWhy: ['2 appears twice.', '3 appears twice.', 'Correct.', '5 appears once.'],
  trap: 'Confusing mode with the largest value.', memory: { tech: 'Fashion hook', x: 'Mode = Most in fashion (most repeated).' }, recall: 'Most frequent value.' }),

Q('q-sr-1', 'square-root', { conceptId: 'm-sr-1', text: 'Find √2025.', options: ['35', '43', '45', '55'], answer: 2, difficulty: 2,
  tests: 'Perfect squares.', solution: ['45² = 2025 (or: 2025 ends in 5 → root must end in 5 → 45²).'],
  wrongWhy: ['35² = 1225.', '43² = 1849.', 'Correct.', '55² = 3025.'],
  trap: 'Not using the “ends in 5” filter.', memory: { tech: 'Ending trick', x: 'Number ends in 25 → root ends in 5.' }, recall: '45² = 2025.' }),

Q('q-age-1', 'age-calculations', { conceptId: 'm-age-1', text: 'The present age of a mother is 4 times her daughter’s age. After 10 years she will be twice as old. The daughter’s present age is:', options: ['5 years', '8 years', '10 years', '12 years'], answer: 0, difficulty: 2,
  tests: 'Age equations.', solution: ['Daughter = x, mother = 4x.', '4x + 10 = 2(x + 10) → 4x + 10 = 2x + 20.', '2x = 10 → x = 5. Check: 5 & 20; after 10 years 15 & 30 ✓.'],
  wrongWhy: ['Correct.', 'Check: 8 & 32 → after 10: 18 & 42 — not twice.', '10 & 40 → 20 & 50 — not twice.', '12 & 48 → 22 & 58 — not twice.'],
  trap: 'Adding 10 only to the mother’s age.', memory: { tech: 'Time train', x: '+10 years boards everyone.' }, recall: 'Both ages move forward.' }),

Q('q-cal-1', 'calendar-clock', { conceptId: 'm-cal-1', text: 'Which of the following years is a leap year?', options: ['1900', '1996', '2002', '2010'], answer: 1, difficulty: 2,
  tests: 'Leap year rule.', solution: ['1996 ÷ 4 = 499 exact ✓.', '1900 is a century NOT divisible by 400 → not leap.'],
  wrongWhy: ['Century years need ÷400; 1900 fails.', 'Correct.', 'Not divisible by 4.', 'Not divisible by 4.'],
  trap: 'Every 4th year EXCEPT centuries not divisible by 400.', memory: { tech: 'Century gate', x: 'Century years knock on the 400 door: 2000 enters, 1900 is refused.' }, recall: '÷4, but centuries ÷400.' }),

Q('q-clk-1', 'calendar-clock', { conceptId: 'm-clk-1', text: 'Find the angle between the clock hands at 2:40.', options: ['160°', '140°', '100°', '180°'], answer: 0, difficulty: 2,
  tests: 'Clock angle formula.', solution: ['30H = 60.', '5.5M = 220.', '|60 − 220| = 160° (≤ 180, keep it).'],
  wrongWhy: ['Correct.', 'Subtraction slip.', 'Half.', 'Only if exactly opposite — check 180 vs 160.'],
  trap: 'Forgetting the 0.5°/min creep of the hour hand.', memory: { tech: 'Speed pair', x: 'Gap changes 5.5°/min.' }, recall: '|30H − 5.5M|.' }),

Q('q-pc-1', 'pipes-cistern', { conceptId: 'm-pc-1', text: 'Pipe A fills a tank in 6 hours. Pipe B empties the full tank in 9 hours. Both are open. The tank fills in:', options: ['15 hours', '18 hours', '3.6 hours', '7.5 hours'], answer: 1, difficulty: 2,
  tests: 'Fill minus drain.', solution: ['Net rate = 1/6 − 1/9 = 3/18 − 2/18 = 1/18 per hour.', 'Time = 18 hours.'],
  wrongWhy: ['Added instead of subtracted.', 'Correct.', 'Subtracted wrongly.', 'Average mistake.'],
  trap: 'Outlet = negative work.', memory: { tech: 'Tanglish sign', x: 'Vaa (+) pora (−) — sign by direction.' }, recall: '1/6 − 1/9 = 1/18 → 18 h.' }),
];
