/* Starter Pack — GENERAL INTELLIGENCE & REASONING.
   Teaching style (spec §11): Concept → Pattern → How to identify the pattern →
   Solving method → Different patterns → Mixed practice. */
import { h, p, li, F, NR, E, T, trap, mem, rec, st, note, sub, STARTER_REF } from './_shared.js';
const C = sub('REASONING').concept;
const Q = sub('REASONING').q;

export const reasoningConcepts = [

C('r-an-1', 'analogies', 'Analogies — “A is to B as C is to ?”',
  'Find the relationship in the first pair, apply it to the third word.',
  [
    h('1. What is this?'),
    p('An analogy compares two things by a hidden relationship, then gives you a third thing and asks for the fourth. Format: A : B :: C : ?'),
    h('2. The pattern'),
    p('Step one is ALWAYS the same: name the relationship inside the FIRST pair. Only then look at the options.'),
    E('Tiny example — Doctor : Hospital :: Teacher : ?', [
      'Doctor works in a hospital.',
      'Teacher works in … a school.',
    ]),
    h('3. How to identify the relationship (common types)'),
    T(['Relationship', 'Example'], [
      ['Worker : workplace', 'Chef : Kitchen'],
      ['Letter shift', 'CAT : FDW (each letter +3)'],
      ['Number rule', '4 : 16 (square), 8 : 72 (n×(n+1))'],
      ['Part : whole', 'Wheel : Car'],
      ['Tool : user', 'Stethoscope : Doctor'],
      ['Cause : effect', 'Rain : Flood'],
      ['Degree', 'Warm : Hot'],
    ]),
    h('4. Solving method'),
    st(['Read the first pair and SAY the relationship in words.', 'Apply the same sentence to the third word.', 'Test each option against that sentence.', 'For letter pairs, write A=1 … Z=26 and convert.']),
    h('5. Different patterns you will see'),
    li(['Word analogies (meanings)', 'Letter analogies (+n/−n shifts, reversals)', 'Number analogies (×k, k², n(n+1), digits reversed)']),
    trap('Choosing an option that is true in real life but uses a DIFFERENT relationship. The relationship must match the first pair exactly.'),
    mem('Sentence frame', 'Always force the relationship into one sentence: “A ____ B”. If you cannot say it simply, you have not found it yet.'),
    rec('First pair → say the relation → apply → check options.'),
  ],
  { text: 'CAT : FDW :: DOG : ?', options: ['GRJ', 'EPI', 'GQI', 'FRJ'], answer: 0,
    steps: ['C→F, A→D, T→W: every letter moves +3.', 'D+3 = G, O+3 = R, G+3 = J → GRJ.'] },
  ['q-an-1'], { generators: ['g-r-analogy'] }),

C('r-al-1', 'alphabetical-series', 'Alphabetical (Letter) Series',
  'Letter positions: A=1 … Z=26. Watch the jump size.',
  [
    h('1. What is this?'),
    p('A sequence of letters with a hidden jump pattern, e.g. A, D, G, J, ? — each letter jumps +3.'),
    F('A=1, B=2, C=3 … Z=26', [['Position', 'the letter’s number in the alphabet']], 'EJOTY trick: E=5, J=10, O=15, T=20, Y=25 — five anchor points to count fast.'),
    h('2. The pattern types'),
    T(['Type', 'Example', 'Rule'], [
      ['Constant jump', 'A, D, G, J, ? → M', '+3 each time'],
      ['Increasing jump', 'A, C, F, J, ? → O', '+2, +3, +4, +5'],
      ['Alternating', 'A, Z, C, X, E, ? → V', 'forward +2, backward −2'],
      ['Skip same letter', 'AZ, BY, CX → DW', 'pair from both ends'],
    ]),
    h('3. How to identify the pattern'),
    st(['Write position numbers under the letters.', 'Find the differences between positions.', 'Spot the pattern in the differences (constant, growing, alternating).', 'Apply it to find the next position, then convert back to a letter.']),
    trap('Counting letters on your fingers and miscounting past 13 (M). Use the EJOTY anchors instead.'),
    mem('EJOTY anchors', 'E-J-O-T-Y = 5-10-15-20-25. To find letter 17: T=20, so 17 = 3 before T = Q. Faster than counting from A.'),
    rec('Letters → numbers → differences → extend → back to letters.'),
  ],
  { text: 'Find the next letter: B, E, H, K, ?', options: ['L', 'M', 'N', 'O'], answer: 2,
    steps: ['Positions: 2, 5, 8, 11 — jumping +3.', 'Next = 11 + 3 = 14 → N.'] },
  ['q-al-1'], { generators: ['g-r-letseries'] }),

C('r-ns-1', 'number-series', 'Number Series — Spot the Rule',
  'Check differences, then ratios, then squares/alternating.',
  [
    h('1. What is this?'),
    p('A row of numbers that follow a hidden rule. You find the next (or wrong) number.'),
    h('2. The pattern checklist (try in this order)'),
    T(['Pattern', 'Looks like', 'Example'], [
      ['Constant difference', '+k each step', '2, 6, 10, 14 → +4'],
      ['Growing difference', '+2, +4, +6, +8', '2, 3, 5, 8, 12, 17'],
      ['Constant ratio', '×k each step', '3, 9, 27, 81'],
      ['Squares / cubes', '1, 4, 9, 16, 25', 'or n²±k'],
      ['Alternating', 'two rules in turns', '1, 4, 2, 8, 3, 12'],
      ['Fibonacci', 'each = sum of previous two', '1, 1, 2, 3, 5, 8'],
    ]),
    h('3. Solving method'),
    st(['Write the differences between neighbours.', 'If differences are not constant, check differences OF differences.', 'If numbers grow fast, check ratios.', 'Check squares/cubes ± small numbers.', 'Verify your rule on EVERY given term, not just two.']),
    trap('Finding a rule that fits the last two numbers only. The rule must fit the whole series.'),
    mem('D-R-S ladder', 'Differences first, Rat second, Squares third. Climb the ladder only when the step below fails.'),
    rec('Differences → double differences → ratios → squares.'),
  ],
  { text: 'Find the next number: 2, 6, 12, 20, 30, ?', options: ['40', '42', '44', '36'], answer: 1,
    steps: ['Differences: +4, +6, +8, +10.', 'Next difference: +12.', '30 + 12 = 42.'] },
  ['q-nsr-1', 'q-nsr-2'], { generators: ['g-r-numseries'] }),

C('r-cd-1', 'coding-decoding', 'Coding and Decoding',
  'The code follows a fixed rule — find it with one word, apply to the next.',
  [
    h('1. What is this?'),
    p('A word is written in a secret code. You are shown one example; from it you find the rule and code a new word.'),
    h('2. Common code patterns'),
    T(['Pattern', 'Example', 'Rule'], [
      ['Shift code', 'CAT → DBU', 'every letter +1'],
      ['Reverse word', 'CAT → TAC', 'read backwards'],
      ['Reverse alphabet', 'MADAM → NZWZN', 'A↔Z, B↔Y (position n → 27−n)'],
      ['Number code', 'CAB → 312', 'letter positions'],
      ['Skip letters', 'A→C, B→D', 'letter +2 (odd/even positions)'],
    ]),
    h('3. Solving method'),
    st(['Write the original word and its code one under the other.', 'Mark each letter’s change (+1, −2, reverse…).', 'Confirm the SAME rule on every letter.', 'Apply the rule to the asked word.']),
    h('4. How to identify the pattern fast'),
    li(['If the code is the same length → shift or reverse rule.', 'If first letter of word codes to last letter of code → reversal.', 'If numbers appear → positions (A=1).']),
    trap('Assuming +1 shift from the first letter only — check ALL letters; some codes mix (+1, −1, +1, −1).'),
    mem('Mirror trick', 'Reverse alphabet: think of a mirror between M and N. A↔Z, B↔Y, C↔X… position n becomes 27−n.'),
    rec('One example → extract rule → verify on all letters → apply.'),
  ],
  { text: 'If LOVE is coded as MPWF, how is HATE coded?', options: ['IBUF', 'GZSD', 'IBVF', 'JBUF'], answer: 0,
    steps: ['L→M (+1), O→P (+1), V→W (+1), E→F (+1).', 'H+1 = I, A+1 = B, T+1 = U, E+1 = F → IBUF.'] },
  ['q-cd-1'], { generators: ['g-r-coding'] }),

C('r-mo-1', 'mathematical-operations', 'Mathematical Operations — Sign Swapping',
  'Replace the fake signs with real ones, then use BODMAS.',
  [
    h('1. What is this?'),
    p('Symbols swap meanings: “+” means “×”, “÷” means “−” and so on. You must evaluate using the NEW meanings.'),
    NR('No formula needed — use this rule: FIRST swap every symbol, THEN solve with BODMAS. Never solve and swap at the same time.'),
    E('Tiny example — if + means × and − means ÷:  6 + 4 − 2', [
      'Swap: 6 × 4 ÷ 2.',
      'BODMAS: 24 ÷ 2 = 12.',
    ]),
    h('2. Solving method'),
    st(['Rewrite the whole expression with the true meanings.', 'Apply BODMAS to the new expression.', 'Re-read the question — sometimes it asks which interchange makes the equation TRUE.']),
    trap('Solving with the original meanings out of habit. ALWAYS rewrite first.'),
    mem('Two-pass rule', 'Pass 1: swap. Pass 2: solve. Two clean passes, zero confusion.'),
    rec('Swap everything first, then BODMAS.'),
  ],
  { text: 'If “+” means “×” and “−” means “÷”, evaluate: 8 + 2 − 4', options: ['4', '10', '6', '5'], answer: 0,
    steps: ['Swap the signs: 8 × 2 ÷ 4.', 'BODMAS: 16 ÷ 4 = 4.'] },
  ['q-mo-1'], { generators: ['g-r-mathops'] }),

C('r-br-1', 'relationships', 'Blood Relations — Draw, Don’t Imagine',
  'Draw a small family tree with +/− and arrows.',
  [
    h('1. What is this?'),
    p('A statement chain tells you how people are related. You must answer the final relation without getting tangled.'),
    h('2. The pattern (symbols that save you)'),
    li([
      'Male: +  Female: −  (write inside a circle)',
      'Marriage: ⇔  (horizontal double line)',
      'Children: a vertical line DOWN from the marriage line',
      'Generation: each row = one generation — draw TOP to BOTTOM',
    ]),
    E('Solved example — “He is the son of my grandfather’s only son”', [
      'Speaker’s grandfather → his only son = speaker’s father.',
      'Father’s son = the speaker’s brother.',
      'Answer: brother.',
    ]),
    h('3. How to identify the question type'),
    li(['Pointing/photo style: start from the SPEAKER.', 'Symbol style: “A + B means A is the mother of B” — build a dictionary first.', 'Family tree style: draw it.']),
    st(['Read once, draw as you read.', 'Never solve relations in your head beyond 2 levels.', 'Answer from the drawing, not memory.']),
    trap('“Grandfather’s only son” — students read “grandfather” and guess “father”. The “only son” phrase is doing the real work: it means father (no uncles).'),
    mem('Only-son lock', '“Only son/daughter” LOCKS that person to exactly one role. Grandfather’s only son = your father. Locked.'),
    rec('Draw +/− circles, marriage lines, vertical children.'),
  ],
  { text: 'Pointing to a man, Rita said, “He is the son of my grandfather’s only son.” How is the man related to Rita?', options: ['Father', 'Brother', 'Uncle', 'Cousin'], answer: 1,
    steps: ['Grandfather’s only son = Rita’s father.', 'Father’s son = Rita’s brother.'] },
  ['q-br-1']),

C('r-sy-1', 'syllogism', 'Syllogism — Draw the Venn',
  'Draw circles for “All/Some/No”, then read conclusions only from the drawing.',
  [
    h('1. What is this?'),
    p('Two statements are given as TRUE. You test which conclusion MUST follow — not what is probably true.'),
    h('2. The patterns'),
    T(['Statement', 'Drawing'], [
      ['All A are B', 'circle A fully inside circle B'],
      ['Some A are B', 'A and B overlap a little'],
      ['No A is B', 'A and B separate, not touching'],
      ['Some A are not B', 'part of A outside B'],
    ]),
    h('3. Solving method'),
    st(['Draw the statements as circles — start with the universal (“All/No”) statements.', 'Test each conclusion against the drawing.', 'A conclusion follows only if it is true in EVERY possible drawing.']),
    E('Example — All cats are animals. Some animals are dogs.', [
      'Cats ⊂ animals; dogs overlaps animals only.',
      '“Some cats are dogs” — NOT certain (the overlap may avoid the cats circle).',
      '“Some animals are cats” — certain ✓.',
    ]),
    trap('Using real-world knowledge (“dogs and cats are both pets, so…”). Only the two statements matter.'),
    mem('MUST rule', 'A conclusion follows only if it MUST be true in every possible diagram — not if it CAN be true in one.'),
    rec('All = inside. Some = overlap. No = apart. Conclusions need “must”.'),
  ],
  { text: 'Statements: All pens are books. Some books are costly.\nWhich conclusion definitely follows?', options: ['All pens are costly', 'Some pens are costly', 'Some books are pens', 'No pen is costly'], answer: 2,
    steps: ['Pens ⊂ books; “costly” overlaps books somewhere.', 'The overlap may or may not touch pens → options 1, 2, 4 are not certain.', '“All pens are books” means pens are inside books, so some books ARE pens ✓.'] },
  ['q-sy-1']),

C('r-ju-1', 'jumbling', 'Jumbling — Put Things in Order',
  'Words or sentences that must be rearranged logically.',
  [
    h('1. What is this?'),
    p('Either letters of a word are jumbled, or events/steps are given out of order. You restore the natural order.'),
    h('2. The patterns'),
    li(['Word jumble: arrange letters into a real word (usually a theme word — railway, exam-related).', 'Ordering: life stages, sizes, dates, process steps.', 'Sentence order: pronouns (he/she) refer back — a sentence starting with a pronoun is rarely first.']),
    E('Solved example — order: 1. Infant 2. Old age 3. Child 4. Youth 5. Adult', [
      'Life order: Infant → Child → Youth → Adult → Old age.',
      'Answer: 1, 3, 4, 5, 2.',
    ]),
    h('3. Solving method'),
    st(['Find the natural starting point (birth, smallest, first step).', 'Chain each item to the next by logic.', 'Check the full chain once before answering.']),
    trap('Ordering by grammar flow instead of logic. Test the chain — each link must be forced.'),
    mem('Chain test', 'Every neighbour pair must be forced: Infant MUST come before child. If any pair is debatable, your order is wrong.'),
    rec('Find the forced start; chain the rest; verify every link.'),
  ],
  { text: 'Arrange in logical order: 1. Seed 2. Fruit 3. Flower 4. Plant', options: ['1, 4, 3, 2', '1, 3, 4, 2', '4, 1, 3, 2', '1, 4, 2, 3'], answer: 0,
    steps: ['Seed grows into a plant.', 'Plant flowers.', 'Flower becomes fruit.', '1, 4, 3, 2.'] },
  ['q-ju-1']),

C('r-vd-1', 'venn-diagram', 'Venn Diagrams — Regions of Overlap',
  'Circles that overlap show shared members.',
  [
    h('1. What is this?'),
    p('A Venn diagram shows sets as circles. Overlapping areas = members common to both sets.'),
    h('2. The patterns'),
    li(['One inside another: “All cats are animals” — cat circle inside animal circle.', 'Partly overlapping: “Some doctors are women”.', 'Separate circles: “No reptile is a mammal”.', 'Three circles: combos like Doctors–Men–Fathers.']),
    E('Solved example — Lions, Tigers, Carnivores', [
      'Both lions and tigers ARE carnivores.',
      'Draw one big circle (carnivores), with two non-touching circles inside (lions, tigers).',
    ]),
    h('3. Solving method'),
    st(['Write each group as a circle.', 'Ask pair by pair: inside, overlapping, or separate?', 'Pick the diagram that matches ALL relations.']),
    trap('Two circles inside one big circle need not overlap each other. Inside ≠ overlapping each other.'),
    mem('Nesting doll', '“Is a” → nested dolls (one inside the other). “Some are” → partial overlap. “Is not” → separate islands.'),
    rec('Is-a → contain; some → overlap; no → separate.'),
  ],
  { text: 'Which Venn diagram best represents Men, Fathers, Doctors?', options: ['Three circles fully separate', 'Fathers inside Men; Doctors overlapping both', 'Men inside Fathers', 'All three identical'], answer: 1,
    steps: ['Every father is a man → Fathers circle inside Men.', 'Doctors can be men or women and fathers or not → overlaps both.', 'So: Fathers inside Men, Doctors overlapping.'] },
  ['q-vd-1']),

C('r-di-1', 'data-interpretation', 'Data Interpretation — Read the Table',
  'Find the right row and column first, then calculate.',
  [
    h('1. What is this?'),
    p('A small table, bar chart or pie chart gives data. Questions ask totals, differences, percentages and ratios — the MATHS is easy; the READING is the test.'),
    h('2. Solving method'),
    st(['Read the titles and units FIRST (what, who, in what units).', 'Locate the exact row × column you need.', 'Do only the asked calculation.', 'In pie charts: whole = 360° = 100%.']),
    E('Tiny example — pie chart: Railways 25% of a budget of ₹400 crore', [
      'Railways share = 25% of 400 = ₹100 crore.',
      'Degrees = 25% of 360° = 90°.',
    ]),
    trap('Answering the wrong column (e.g., 2023 instead of 2024) or missing “in thousands” in the unit line.'),
    mem('Title-then-cell', 'Two seconds on the title saves two minutes of wrong calculation.'),
    rec('Title → units → exact cell → then calculate.'),
  ],
  { text: 'A shop sold 12, 15 and 18 items on Mon, Tue, Wed. Average items per day =?', options: ['15', '16', '14', '17'], answer: 0,
    steps: ['Total = 12 + 15 + 18 = 45.', '45 ÷ 3 = 15.'] },
  ['q-di-1'], { generators: ['g-r-di'] }),

C('r-ds-1', 'data-sufficiency', 'Data Sufficiency — Do You Have Enough?',
  'Test each statement alone, then together. Never over-calculate.',
  [
    h('1. What is this?'),
    p('A question + two statements. You decide whether the statements give enough data — you usually do NOT need the final answer.'),
    h('2. The standard options'),
    li(['I alone is sufficient', 'II alone is sufficient', 'Both together are needed', 'Even both together are not enough', 'Either one alone is sufficient']),
    h('3. Solving method'),
    st(['Hide statement II. Can you answer with I alone?', 'Hide statement I. Can you answer with II alone?', 'Only if both fail alone, use them TOGETHER.', 'Stop as soon as you know sufficiency — no need to finish the arithmetic.']),
    trap('Solving the whole problem. The exam asks “is the data enough”, not “what is the answer”. Save your time.'),
    mem('Blindfold test', 'Blindfold one statement at a time. If the open one already answers the question, the blindfolded one is useless.'),
    rec('Each alone → together → not enough. Stop early.'),
  ],
  { text: 'What is Ravi’s age?\nI. Ravi is 5 years older than Meena.  II. Meena is 15 years old.', options: ['Statement I alone is sufficient', 'Statement II alone is sufficient', 'Both together are needed', 'Both together are not enough'], answer: 2,
    steps: ['I alone: Ravi = Meena + 5 — but Meena is unknown. Not sufficient.', 'II alone: Meena = 15 — but no link to Ravi. Not sufficient.', 'Together: Ravi = 15 + 5 = 20 ✓.'] },
  ['q-ds-1']),

C('r-cd2-1', 'conclusions-decision', 'Conclusions and Decision Making',
  'Apply the given rule exactly — no extra assumptions.',
  [
    h('1. What is this?'),
    p('A rule/notice is given. You must decide what it logically requires for a specific case.'),
    NR('No formula needed — use this rule: apply ONLY what the notice says. Do not add real-life shortcuts.'),
    E('Solved example — Rule: Distinction = marks above 60% AND attendance above 75%. Priya: 63% marks, 80% attendance.', [
      'Marks above 60? Yes (63).',
      'Attendance above 75? Yes (80).',
      'Both conditions met → Priya gets the distinction.',
    ]),
    h('2. Solving method'),
    st(['List the conditions as checkboxes.', 'Tick each against the person’s data.', 'ALL conditions must pass; if any fails, the answer is no.']),
    trap('Passing a candidate because one strong condition passed. AND means ALL must pass.'),
    mem('AND-gate', 'Think like an electric circuit: conditions in SERIES. One break = no current = no admission/award.'),
    rec('Checklist every condition; AND needs all ticks.'),
  ],
  { text: 'Rule: A student gets a certificate if marks ≥ 80 and attendance ≥ 90%. Arun has 82 marks and 85% attendance. Does Arun get the certificate?', options: ['Yes — marks condition is met', 'Yes — he is close to both', 'No — attendance condition fails', 'Cannot be determined'], answer: 2,
    steps: ['Marks 82 ≥ 80 ✓.', 'Attendance 85% < 90% ✗.', 'AND rule → one fail means NO certificate.'] },
  ['q-cd2-1']),

C('r-sd-1', 'similarities-differences', 'Similarities and Differences',
  'Find the pair with the SAME relationship as the given pair.',
  [
    h('1. What is this?'),
    p('You are given a pair; you must find another pair that shares the same kind of relationship.'),
    E('Tiny example — Ophthalmologist : Eye', [
      'The relation: specialist doctor : body part.',
      'Matching pair: Cardiologist : Heart.',
    ]),
    h('2. Solving method'),
    st(['Name the relationship of the given pair in one sentence.', 'Test each option against that exact sentence.', 'Reject pairs that are related but differently (Nurse : Hospital is a workplace link, not specialist : part).']),
    trap('Picking a pair connected to the same TOPIC instead of the same RELATIONSHIP.'),
    mem('Relation lock', 'Lock the sentence, not the subject. “Specialist : organ he treats” — any topic, same lock.'),
    rec('Name the relation → test options → same lock only.'),
  ],
  { text: 'Pen : Writer :: which pair has the same relationship?', options: ['Book : Library', 'Needle : Tailor', 'Chalk : Blackboard', 'Paper : File'], answer: 1,
    steps: ['Relation: tool : professional who uses it.', 'Needle is the tool a tailor uses ✓.', 'Library/file are places/objects, not professionals.'] },
  ['q-sd-1']),

C('r-ar-1', 'analytical-reasoning', 'Analytical Reasoning — Ranking and Ordering',
  'Line people up; use the fixed facts first.',
  [
    h('1. What is this?'),
    p('People/objects in a row or order. Some clues fix positions exactly; others give relative info. Combine them.'),
    F('From left: position = given\nFrom right: position = (Total + 1) − position_from_left', [
      ['Total', 'number of people in the row'],
    ], 'The +1 trick: positions from both ends always add to Total + 1.'),
    E('Solved example — Ram is 12th from the left in a row of 40. His position from the right?', [
      'From right = 40 + 1 − 12 = 29th.',
    ]),
    h('2. Solving method'),
    st(['Place all EXACT positions first (fixed seats).', 'Then place relative clues (A is to the right of B).', 'Draw the row — never hold it in your head.', 'Count carefully from the correct end.']),
    trap('Counting the person themselves twice in “how many between” questions — between excludes both ends.'),
    mem('Total+1', 'Left position + right position = Total + 1. The +1 is the anchor — forgetting it is the #1 error.'),
    rec('Fixed first, relative next, draw the row.'),
  ],
  { text: 'In a row of 40 students, Ram is 12th from the left end. What is his position from the right end?', options: ['28th', '29th', '27th', '30th'], answer: 1,
    steps: ['Position from right = 40 + 1 − 12.', '= 29th.'] },
  ['q-ar-1'], { generators: ['g-r-rank'] }),

C('r-cl-1', 'classification', 'Classification — Odd One Out',
  'Three share a property; one does not. Name the property.',
  [
    h('1. What is this?'),
    p('Four items are given. Three belong to one family; you find the outsider.'),
    h('2. The pattern families'),
    T(['Family', 'Example'], [
      ['Category', 'Apple, Mango, Banana, Potato → potato (vegetable)'],
      ['Number property', '3, 5, 7, 9 → 9 (not prime)'],
      ['Letters', 'ABE, MNO, PQS, VWY → check vowel positions'],
      ['Structure', 'some words have double letters, others not'],
    ]),
    h('3. Solving method'),
    st(['Try to name the group that fits THREE items.', 'The leftover is the answer.', 'If two splits look possible, pick the strongest (category beats spelling).']),
    trap('Finding a property that fits only TWO items. A valid classification must group exactly three.'),
    mem('Three-plus-one', 'The odd-one-out question is really “find the group of three”. Name the trio, the odd one exposes itself.'),
    rec('Group three, expose one.'),
  ],
  { text: 'Find the odd one out: Earth, Moon, Mars, Venus', options: ['Earth', 'Moon', 'Mars', 'Venus'], answer: 1,
    steps: ['Earth, Mars, Venus are planets.', 'The Moon is a satellite → odd one.'] },
  ['q-cl-1'], { generators: ['g-r-odd'] }),

C('r-di2-1', 'directions', 'Direction Sense',
  'Face the direction, apply turns, track net movement.',
  [
    h('1. What is this?'),
    p('Someone walks and turns; you must find the final direction or distance from the start.'),
    h('2. The compass'),
    T(['Facing…', 'Right turn →', 'Left turn →'], [
      ['North', 'East', 'West'],
      ['East', 'South', 'North'],
      ['South', 'West', 'East'],
      ['West', 'North', 'South'],
    ]),
    li(['Right turn (clockwise): N→E→S→W→N', 'Left turn (anti-clockwise): N→W→S→E→N']),
    h('3. Solving method'),
    st(['Draw axes: North up, East right. ALWAYS.', 'Plot each move as an arrow.', 'Opposite moves cancel (3 km N + 3 km S = 0).', 'Final position: join start to end — compare the two leftover distances.']),
    E('Solved example — walk 5 km North, turn right, walk 3 km, turn right, walk 5 km', [
      '5 km North, then 3 km East, then 5 km South.',
      'North and South cancel → 5 − 5 = 0.',
      'Leftover: 3 km East of start.',
    ], '3 km East'),
    trap('Left/right depends on the CURRENT facing, not on the page. After facing South, “right” means West.'),
    mem('Clock face', 'Turns are a clock: right = clockwise, left = anti-clockwise. Rotate your pencil, not your head.'),
    rec('Draw axes, plot arrows, cancel opposites, join ends.'),
  ],
  { text: 'A man walks 4 km North, turns right and walks 4 km, then turns right and walks 4 km. How far is he from the start?', options: ['12 km', '4 km', '8 km', '0 km'], answer: 1,
    steps: ['4 km N, then 4 km E, then 4 km S.', 'N and S cancel (4 − 4 = 0).', 'He is 4 km East of the start.'] },
  ['q-dir-1'], { generators: ['g-r-dir'] }),

C('r-sa-1', 'statement-arguments', 'Statement-Arguments — Strong vs Weak',
  'Strong = directly connected and important. Weak = off-topic or extreme.',
  [
    h('1. What is this?'),
    p('A proposal is given with arguments for/against. You judge which argument is STRONG.'),
    h('2. The pattern'),
    T(['Strong argument', 'Weak argument'], [
      ['Directly related to the proposal', 'Off-topic / only example'],
      ['Covers the real impact on people', 'Emotional opinion only'],
      ['Balanced and evidenced', 'Extreme words (always, never, all)'],
    ]),
    E('Example — “Should education be free for all?”', [
      'STRONG: “Yes — it would raise literacy and reduce poverty.” (direct + impactful)',
      'WEAK: “No — my cousin had to pay fees.” (personal example)',
    ]),
    h('3. Solving method'),
    st(['Restate the proposal in one line.', 'Check: does the argument address THAT line?', 'Check: does it matter at large scale?', 'Both yes → strong.']),
    trap('Agreeing with an argument because it sounds passionate. Passion ≠ strength; connection + impact = strength.'),
    mem('Two gates', 'Gate 1: Is it about the topic? Gate 2: Does it matter to many? Both gates open = strong.'),
    rec('Related + real impact = strong; off-topic/extreme = weak.'),
  ],
  { text: 'Statement: “Should speed breakers be built near schools?”\nWhich argument is STRONG?', options: ['Yes — they reduce accidents involving children', 'Yes — my street also needs one', 'No — drivers do not like them', 'No — speed breakers are old technology'], answer: 0,
    steps: ['Option 1 is directly related and protects children at large scale → strong.', 'Others are personal, about preference, or about fashion.'] },
  ['q-sa-1']),

C('r-as-1', 'assumptions', 'Assumptions — What Is Taken for Granted',
  'An assumption is the hidden belief the speaker MUST hold.',
  [
    h('1. What is this?'),
    p('A statement/advice is given. You find what the speaker is silently assuming to be true.'),
    NR('No formula needed — use this rule: an assumption is VALID only if, without it, the statement would make no sense.'),
    E('Example — “Please use the staircase during a fire.”', [
      'Assumption: lifts are unsafe during a fire ✓ (without this, the advice is pointless).',
      'Not an assumption: “stairs are good exercise” ✗ (not needed for the advice).',
    ]),
    h('2. Solving method'),
    st(['Ask: what MUST be true for this statement to be worth saying?', 'Test each option by NEGATING it — if negation makes the statement collapse, it is an assumption.', 'Reject options that merely add extra facts.']),
    trap('Marking “probably true” extras as assumptions. The test is NECESSITY, not plausibility.'),
    mem('Negation bomb', 'Negate the option. If the statement explodes, it was an assumption. If the statement survives, it was decoration.'),
    rec('Must-be-true → assumption. Negate to test.'),
  ],
  { text: 'Statement: “Drink boiled water during the monsoon.”\nWhich assumption is implicit?', options: ['Boiled water tastes better', 'Unboiled water may cause illness in the monsoon', 'People drink less water in the monsoon', 'Boiling is cheaper than filtering'], answer: 1,
    steps: ['Negate option 2: “unboiled water is safe” — then the advice collapses.', 'So the speaker must assume unboiled water may cause illness ✓.'] },
  ['q-as-1']),
];

export const reasoningQuestions = [
Q('q-an-1', 'analogies', { conceptId: 'r-an-1', text: '8 : 72 :: 6 : ?', options: ['36', '42', '48', '30'], answer: 1, difficulty: 2,
  tests: 'Number analogy — n × (n+1).', solution: ['8 × 9 = 72 (n × next number).', '6 × 7 = 42.'],
  wrongWhy: ['6² = 36 — wrong rule.', 'Correct.', '6 × 8 — off rule.', '6 × 5 — reversed rule.'],
  trap: 'Test the rule on the first pair completely.', memory: { tech: 'Rule naming', x: 'Say the rule in words before applying.' }, recall: 'n × (n+1) family.' }),

Q('q-al-1', 'alphabetical-series', { conceptId: 'r-al-1', text: 'Find the next letter: A, D, G, J, ?', options: ['K', 'L', 'M', 'N'], answer: 2, difficulty: 1,
  tests: 'Constant letter jump.', solution: ['Positions 1, 4, 7, 10 (+3).', 'Next = 13 → M.'],
  wrongWhy: ['11 = K — jump of 1.', '12 = L — jump of 2.', 'Correct.', '14 = N — jump of 4.'],
  trap: 'Miscounting positions — use EJOTY anchors.', memory: { tech: 'EJOTY', x: 'E5 J10 O15 T20 Y25.' }, recall: 'Letters→numbers, +3 → 13 = M.' }),

Q('q-nsr-1', 'number-series', { conceptId: 'r-ns-1', text: 'Find the wrong number: 1, 4, 9, 16, 24, 36', options: ['4', '9', '24', '36'], answer: 2, difficulty: 2,
  tests: 'Squares series with an error.', solution: ['The series is perfect squares: 1², 2², 3², 4², 5², 6².', 'The 5th term should be 25, but 24 is given.'],
  wrongWhy: ['2² = 4 is correct.', '3² = 9 is correct.', 'Correct — 24 is wrong; it should be 25.', '6² = 36 is correct.'],
  trap: 'Check the whole series; find the single break.', memory: { tech: 'Square radar', x: '1,4,9,16 → instantly think squares.' }, recall: 'Perfect squares: 1,4,9,16,25,36.' }),

Q('q-nsr-2', 'number-series', { conceptId: 'r-ns-1', text: 'Find the next number: 3, 9, 27, 81, ?', options: ['162', '216', '243', '108'], answer: 2, difficulty: 1,
  tests: 'Geometric series ×3.', solution: ['Each term × 3.', '81 × 3 = 243.'],
  wrongWhy: ['×2 mistake.', '6³ confusion.', 'Correct.', '+27 mistake.'],
  trap: 'Fast growth → check ratio.', memory: { tech: 'D-R-S ladder', x: 'Fast growth means ratio check.' }, recall: '×3 series → 243.' }),

Q('q-cd-1', 'coding-decoding', { conceptId: 'r-cd-1', text: 'If MADAM is coded as NZWZN, how will BOOK be coded?', options: ['YLP', 'CPPL', 'YLLB', 'QPPL'], answer: 0, difficulty: 3,
  tests: 'Mirror (reverse) alphabet coding.', solution: ['Check the rule: M(13) → N(14)? No — M→N is +1, but A(1) → Z(26) is the mirror. Use the mirror rule n → 27−n: M(13) → 27−13 = 14 = N ✓, A(1) → Z ✓, D(4) → W ✓.', 'So every letter becomes its mirror (A↔Z).', 'B(2) → Y, O(15) → L, K(11) → P → YLP.'],
  wrongWhy: ['Correct: B→Y, O→L, K→P.', 'That is a +1 shift — wrong rule.', 'Inconsistent.', 'Wrong shift.'],
  trap: 'Verify the rule on EVERY letter of the example word.', memory: { tech: 'Mirror between M and N', x: 'Position n becomes 27−n.' }, recall: 'Mirror alphabet: A↔Z, B↔Y, C↔X.' }),

Q('q-mo-1', 'mathematical-operations', { conceptId: 'r-mo-1', text: 'If “×” means “+” and “÷” means “−”, evaluate: 6 × 4 ÷ 2', options: ['10', '8', '26', '12'], answer: 1, difficulty: 1,
  tests: 'Symbol swapping.', solution: ['Swap: the line becomes 6 + 4 − 2.', '6 + 4 = 10, 10 − 2 = 8.'],
  wrongWhy: ['You stopped after adding — remember the −2.', 'Correct: 6 + 4 − 2 = 8.', 'You multiplied without swapping.', 'Mixed up the swap.'],
  trap: 'Rewrite the whole expression first.', memory: { tech: 'Two-pass rule', x: 'Swap first, solve second.' }, recall: 'Swap → BODMAS.' }),

Q('q-br-1', 'relationships', { conceptId: 'r-br-1', text: 'A + B means A is the mother of B; A − B means A is the brother of B. In P + Q − R, how is P related to R?', options: ['Mother', 'Aunt', 'Sister', 'Grandmother'], answer: 0, difficulty: 2,
  tests: 'Symbolic blood relations.', solution: ['P + Q → P is mother of Q.', 'Q − R → Q is brother of R.', 'So R is also P’s child → P is R’s MOTHER.'],
  wrongWhy: ['Correct.', 'Not implied.', 'P is female parent, not sister.', 'No generation jump.'],
  trap: 'Brother of R means R is in the same generation as Q — both children of P.', memory: { tech: 'Only-son lock analog', x: 'Translate each symbol into a full sentence before combining.' }, recall: 'Mother of Q; Q brother of R → mother of R.' }),

Q('q-sy-1', 'syllogism', { conceptId: 'r-sy-1', text: 'Statements: All roses are flowers. Some flowers fade quickly.\nConclusion: Some roses fade quickly.', options: ['Definitely follows', 'Does not definitely follow', 'Follows only in summer', 'Both A and C'], answer: 1, difficulty: 2,
  tests: 'Syllogism with “some”.', solution: ['Roses ⊂ flowers; “fade quickly” overlaps flowers somewhere.', 'The overlap might avoid the roses circle entirely.', 'So the conclusion is NOT certain.'],
  wrongWhy: ['Trap — attractive but not necessary.', 'Correct.', 'Joke option — logic never depends on season.', 'Nonsense combo.'],
  trap: '“Some flowers fade” does not tell WHERE inside flowers that part sits.', memory: { tech: 'MUST rule', x: 'Follows only if true in EVERY possible diagram.' }, recall: 'Overlap position unknown → not certain.' }),

Q('q-ju-1', 'jumbling', { conceptId: 'r-ju-1', text: 'Arrange in meaningful order: 1. Travel 2. Plan 3. Return 4. Pack', options: ['2, 4, 1, 3', '2, 1, 4, 3', '4, 2, 1, 3', '1, 2, 3, 4'], answer: 0, difficulty: 1,
  tests: 'Process ordering.', solution: ['Plan → Pack → Travel → Return.', '2, 4, 1, 3.'],
  wrongWhy: ['Correct.', 'Pack before plan is odd.', 'Plan must precede pack.', 'Given order is already jumbled.'],
  trap: 'Check the full chain, not just the first item.', memory: { tech: 'Chain test', x: 'Every neighbour must be forced.' }, recall: 'Plan first, return last.' }),

Q('q-vd-1', 'venn-diagram', { conceptId: 'r-vd-1', text: 'Which diagram suits: Teachers, Women, Doctors?', options: ['Three separate circles', 'Three mutually overlapping circles', 'Doctors inside Women', 'One big circle only'], answer: 1, difficulty: 2,
  tests: 'Venn region thinking.', solution: ['Some teachers are women; some women are doctors; some doctors are teachers.', 'All three pairs can overlap → three mutually overlapping circles.'],
  wrongWhy: ['They do share members.', 'Correct.', 'Not all doctors are women.', 'They are not identical sets.'],
  trap: 'Do not assume one set contains another without an “all” statement.', memory: { tech: 'Nesting doll', x: 'Only “all/none” statements force nesting/separation.' }, recall: 'No “all” → allow overlap.' }),

Q('q-di-1', 'data-interpretation', { conceptId: 'r-di-1', text: 'A train carried 240 passengers on Monday, 300 on Tuesday and 360 on Wednesday. On which day was the increase over the previous day exactly 25%?', options: ['Tuesday', 'Wednesday', 'Both days', 'Neither day'], answer: 0, difficulty: 2,
  tests: 'Percentage from table data.', solution: ['Tuesday: increase = 300 − 240 = 60; 60 ÷ 240 = 25% ✓.', 'Wednesday: increase = 360 − 300 = 60; 60 ÷ 300 = 20% ✗.', 'Only Tuesday is exactly 25%.'],
  wrongWhy: ['Correct — Tuesday’s increase is 25%.', 'Wednesday is 20%, not 25%.', 'Wednesday is 20%.', 'Tuesday qualifies.'],
  trap: 'Divide by the PREVIOUS day’s value.', memory: { tech: 'If X then Y', x: 'If asking % increase, denominator = earlier value.' }, recall: 'Δ ÷ previous × 100.' }),

Q('q-ds-1', 'data-sufficiency', { conceptId: 'r-ds-1', text: 'Is x greater than 10?\nI. x + 5 > 15   II. x − 2 > 9', options: ['I alone is sufficient', 'II alone is sufficient', 'Each alone is sufficient', 'Both together are needed'], answer: 2, difficulty: 2,
  tests: 'Inequality sufficiency.', solution: ['I: x > 10 ✓ sufficient.', 'II: x > 11 ✓ sufficient (also implies x > 10).', 'Each alone is sufficient.'],
  wrongWhy: ['True, but so is II.', 'True, but so is I.', 'Correct.', 'Not needed.'],
  trap: 'Test each statement separately before combining.', memory: { tech: 'Blindfold test', x: 'Cover one statement at a time.' }, recall: 'Each alone works here.' }),

Q('q-cd2-1', 'conclusions-decision', { conceptId: 'r-cd2-1', text: 'Rule: Scholarship needs family income < ₹2 lakh AND marks > 75%. Suresh: income ₹1.8 lakh, marks 74%. Decision?', options: ['Scholarship given', 'Scholarship refused', 'Refer to principal', 'Wait for next exam'], answer: 1, difficulty: 1,
  tests: 'AND-rule decision.', solution: ['Income 1.8 < 2 ✓.', 'Marks 74 is NOT > 75 ✗.', 'One condition fails → refused.'],
  wrongWhy: ['Marks condition failed.', 'Correct.', 'Rules do not allow referral.', 'Not in the rule.'],
  trap: 'AND requires every condition.', memory: { tech: 'AND-gate', x: 'Series circuit — one break stops all.' }, recall: 'All ticks or no.' }),

Q('q-sd-1', 'similarities-differences', { conceptId: 'r-sd-1', text: 'Which pair is similar to Petrol : Car?', options: ['Ink : Pen', 'Water : River', 'Fuel price : Pump', 'Driver : Car'], answer: 0, difficulty: 2,
  tests: 'Relation matching.', solution: ['Petrol is the consumable that runs a car.', 'Ink is the consumable that runs a pen ✓.'],
  wrongWhy: ['Correct.', 'Rivers are not run by water in the same consumable sense.', 'Not a consumable relation.', 'That is operator : machine, different relation.'],
  trap: 'Same relation, not same topic.', memory: { tech: 'Relation lock', x: '“Consumable : machine it runs”.' }, recall: 'Lock the sentence.' }),

Q('q-ar-1', 'analytical-reasoning', { conceptId: 'r-ar-1', text: 'Five friends sit in a row. P is to the immediate right of Q. R is at the extreme left. S is between Q and R. Who sits in the middle?', options: ['P', 'Q', 'S', 'T'], answer: 1, difficulty: 3,
  tests: 'Linear arrangement.', solution: ['Order from left: R, S, Q, P, and the fifth (T) at the extreme right.', 'Positions: 1 R, 2 S, 3 Q, 4 P, 5 T.', 'Middle (3rd) = Q.'],
  wrongWhy: ['P is 4th.', 'Correct — Q is 3rd.', 'S is 2nd.', 'T is 5th.'],
  trap: 'Draw the row; “between Q and R” fixes S next to R.', memory: { tech: 'Fixed-first', x: 'Place extreme-left R first, then chain.' }, recall: 'R S Q P T → middle Q.' }),

Q('q-cl-1', 'classification', { conceptId: 'r-cl-1', text: 'Find the odd one: 3, 5, 7, 9, 11', options: ['3', '5', '9', '11'], answer: 2, difficulty: 1,
  tests: 'Number classification.', solution: ['3, 5, 7, 11 are primes.', '9 = 3 × 3 → not prime.'],
  wrongWhy: ['Prime.', 'Prime.', 'Correct — 9 is composite.', 'Prime.'],
  trap: 'All are odd — go one level deeper to primality.', memory: { tech: 'Three-plus-one', x: 'Group three primes; 9 stands out.' }, recall: '9 = 3².' }),

Q('q-dir-1', 'directions', { conceptId: 'r-di2-1', text: 'Facing North, Ravi turns 90° right, walks 2 km, turns 90° right again, walks 2 km. Which direction is he from his starting point?', options: ['North', 'South', 'East', 'West'], answer: 2, difficulty: 2,
  tests: 'Direction sense with turns.', solution: ['Facing North, right → faces East. Walk 2 km E.', 'Right again → faces South. Walk 2 km S.', 'He is 2 km EAST of the start.'],
  wrongWhy: ['No northward move remains.', 'He moved south but the net displacement from start is east — compare the endpoint, not the facing.', 'Correct.', 'No westward move.'],
  trap: '“Direction from start” = direction of the displacement vector, not where he faces.', memory: { tech: 'Plot arrows', x: 'Draw E and S arrows; the endpoint sits east.' }, recall: 'Displacement, not facing.' }),

Q('q-sa-1', 'statement-arguments', { conceptId: 'r-sa-1', text: 'Statement: “Should mobile phones be banned in classrooms?”\nWhich is the STRONG argument?', options: ['Yes — students check messages instead of listening', 'Yes — phones are costly', 'No — companies will sell fewer phones', 'No — I like phones'], answer: 0, difficulty: 1,
  tests: 'Strong vs weak argument.', solution: ['Option 1 directly links phones to the classroom purpose (learning).', 'Others are about money or personal taste — weak.'],
  wrongWhy: ['Correct — direct classroom impact.', 'Cost is not about the classroom goal.', 'Sales impact is off-topic.', 'Personal preference is weak.'],
  trap: 'Strength = connection to the issue + scale of impact.', memory: { tech: 'Two gates', x: 'On-topic? Matters at scale?' }, recall: 'Related + impactful = strong.' }),

Q('q-as-1', 'assumptions', { conceptId: 'r-as-1', text: 'Statement: “Please switch off lights when leaving the room.”\nWhich assumption is implicit?', options: ['People sometimes forget to switch off lights', 'Electricity is expensive', 'Rooms have white lights', 'Switching off saves the bulb'], answer: 0, difficulty: 2,
  tests: 'Implicit assumption.', solution: ['The advice only makes sense if forgetting happens.', 'Negate it: “nobody ever forgets” → the notice is useless → so it is assumed.'],
  wrongWhy: ['Correct.', 'Plausible extra, not necessary.', 'Irrelevant.', 'Not necessary for the advice.'],
  trap: 'Plausible ≠ assumed. Use the negation test.', memory: { tech: 'Negation bomb', x: 'Negate; if the statement dies, it is an assumption.' }, recall: 'Necessary belief = assumption.' }),
];
