/* Starter Pack — GENERAL SCIENCE (10th-standard level).
   Teaching style (spec §26): Basic concept → Simple explanation → Real-life
   example → Important rule/fact → Application → Questions → Revision. */
import { h, p, li, F, NR, E, T, trap, mem, rec, st, note, sub, STARTER_REF } from './_shared.js';
const C = sub('SCIENCE').concept;
const Q = sub('SCIENCE').q;

export const scienceConcepts = [

/* ================= PHYSICS ================= */
C('s-ph-motion', 'physics', 'Motion — Speed and Velocity',
  'Speed = distance ÷ time; velocity adds direction.',
  [
    h('1. Basic concept'),
    p('An object is in MOTION when its position changes with time. Distance is the total path covered. Displacement is the straight-line gap between start and end, with direction.'),
    F('Speed = Distance ÷ Time      Velocity = Displacement ÷ Time', [
      ['Distance', 'total path travelled (scalar — no direction)'],
      ['Displacement', 'shortest path from start to end, with direction (vector)'],
    ], 'Speed never decreases in a trip; displacement can be zero (a full circle).'),
    h('2. Simple explanation'),
    p('You walk 3 km to a shop and 3 km back home. Distance = 6 km. Displacement = 0 (you are back where you started).'),
    h('3. Real-life example'),
    p('An auto meter measures DISTANCE (it charges for the path). A GPS “as the crow flies” arrow shows DISPLACEMENT.'),
    h('4. Important facts'),
    li(['SI unit of speed/velocity: m/s.', 'Uniform motion = equal distances in equal times.', 'Velocity = speed + direction. 60 km/h north is a velocity.']),
    E('Example — a cyclist covers 300 m in 60 seconds', ['Speed = 300 ÷ 60 = 5 m/s.'], '5 m/s'),
    h('5. Application'),
    li(['Train timetables use average speed.', 'One full lap of a circular track: distance = 2πr, displacement = 0.']),
    trap('Speed and velocity have the same unit but velocity needs a direction. Zero displacement with non-zero distance is possible.'),
    mem('Contrast pair', 'Auto meter = distance. Crow’s flight = displacement.'),
    rec('Speed = path/time; velocity = displacement/time + direction.'),
  ],
  { text: 'A man walks 4 km east, then 4 km west. His displacement is:', options: ['8 km', '4 km', '0 km', '8 km east'], answer: 2,
    steps: ['He is back at the start.', 'Displacement (straight-line start→end) = 0.'] },
  ['q-ph-1']),

C('s-ph-force', 'physics', 'Force and Newton’s Three Laws',
  'Force changes motion. Inertia, F = ma, action–reaction.',
  [
    h('1. Basic concept'),
    p('A force is a push or a pull. It can start motion, stop motion, change direction, or change the shape of an object.'),
    h('2. Simple explanation + real-life example'),
    li([
      'First law (inertia): objects resist change. When a bus starts, you fall BACKWARD (your body wants to stay). When it brakes, you fall FORWARD.',
      'Second law: F = m × a. Heavier objects need more force for the same acceleration.',
      'Third law: every action has an equal and opposite reaction. A gun recoils; a rocket pushes gas down and rises up.',
    ]),
    F('F = m × a', [['F', 'force in newtons (N)'], ['m', 'mass in kg'], ['a', 'acceleration in m/s²']]),
    h('3. Important facts'),
    li(['SI unit of force: newton (N).', 'Inertia depends on MASS — more mass, more laziness.', 'Action–reaction pairs act on DIFFERENT bodies — that is why they do not cancel.']),
    h('4. Application'),
    li(['Seat belts fight inertia during sudden braking.', 'Recoil of a gun = third law.', 'Crumple zones increase time of impact, reducing force.']),
    trap('Thinking action and reaction cancel out. They act on different objects, so each object still feels one force.'),
    mem('Bus story', 'Bus starts → you fall back (1st law). Bus brakes → you fly forward (1st law again). You push the seat, seat pushes you (3rd law).'),
    rec('1st inertia · 2nd F=ma · 3rd action–reaction.'),
  ],
  { text: 'When a running bus suddenly brakes, passengers lean forward. This is explained by:', options: ['Newton’s first law (inertia)', 'Newton’s second law', 'Newton’s third law', 'Law of gravitation'], answer: 0,
    steps: ['The bus stops but the passengers’ bodies keep moving — inertia.', 'That is Newton’s first law.'] },
  ['q-ph-2']),

C('s-ph-work', 'physics', 'Work, Energy and Power',
  'Work = force × distance; energy is the capacity to do work.',
  [
    h('1. Basic concept'),
    p('In science, WORK happens only when a force actually MOVES something. Holding a heavy bag while standing is NOT work in physics (no displacement).'),
    F('Work = Force × displacement = F × d\nPower = Work ÷ time\nKE = ½ m v²      PE = m g h', [
      ['Work', 'joule (J)'], ['Power', 'watt (W) = joule/second'],
      ['KE', 'kinetic energy — energy of motion'],
      ['PE', 'potential energy — stored energy of height'],
      ['g', '≈ 9.8 m/s²'],
    ]),
    h('2. Simple explanation'),
    p('Energy cannot be created or destroyed — only changed from one form to another (law of conservation of energy). A falling ball swaps PE for KE.'),
    h('3. Real-life example'),
    p('A hydro dam stores water high up (PE). Falling water spins turbines (KE → electrical energy).'),
    h('4. Important facts'),
    li(['1 kilowatt-hour (unit of electricity) = 3.6 × 10⁶ J.', 'KE depends on v² — double the speed, FOUR times the energy.', 'Power measures HOW FAST work is done.']),
    E('Example — a 60 W bulb', ['It uses 60 joules of energy every second.'], '60 J/s'),
    h('5. Application'),
    li(['Electricity bills are in kWh (units).', 'Vehicle speed limits exist because braking distance grows with KE.']),
    trap('“Working hard” while holding a wall is zero PHYSICAL work — no displacement.'),
    mem('Twin formulas', 'KE = ½mv² (motion), PE = mgh (height). Speed doubles → KE ×4 (the v² is the trap).'),
    rec('W = Fd (J); P = W/t (W); KE ½mv²; PE mgh; 1 kWh = 3.6 MJ.'),
  ],
  { text: 'The kinetic energy of a moving body becomes 4 times when its speed:', options: ['doubles', 'triples', 'becomes 4 times', 'halves'], answer: 0,
    steps: ['KE = ½mv².', 'v → 2v gives (2v)² = 4v² → KE × 4.'] },
  ['q-ph-3']),

C('s-ph-gravity', 'physics', 'Gravitation — Why Things Fall',
  'Every mass attracts every other mass; g ≈ 9.8 m/s².',
  [
    h('1. Basic concept'),
    p('Earth pulls every object toward its centre. This pull gives objects weight and makes them fall with an acceleration g.'),
    F('Weight W = m × g      (g ≈ 9.8 m/s² on Earth)', [
      ['W', 'weight in newtons — a FORCE'],
      ['m', 'mass in kg — the amount of matter'],
      ['g', 'acceleration due to gravity'],
    ], 'Mass never changes; weight changes with g.'),
    h('2. Simple explanation'),
    p('Mass is “how much stuff”. Weight is “how hard gravity pulls the stuff”. Same person: mass 60 kg everywhere; weight less on the Moon (g is 1/6).'),
    h('3. Real-life example'),
    p('Astronauts float in orbit not because gravity vanished, but because they are in continuous free fall around Earth.'),
    h('4. Important facts'),
    li(['Value of g on Earth ≈ 9.8 m/s² (about 10 in quick sums).', 'Moon’s g ≈ 1/6 of Earth’s.', 'A coin and a feather in vacuum fall together (no air resistance).']),
    trap('Confusing mass (kg, constant) with weight (N, changes with g). “My weight is 60 kg” is everyday talk, not physics.'),
    mem('Mass vs weight pair', 'Mass = luggage content. Weight = how hard the porter must pull. On the Moon the porter relaxes.'),
    rec('W = mg; g_Earth 9.8; g_moon = g/6.'),
  ],
  { text: 'An object weighs 60 N on Earth. On the Moon (g = 1/6 of Earth’s), its weight is about:', options: ['60 N', '10 N', '360 N', '0 N'], answer: 1,
    steps: ['Weight ∝ g.', 'g_moon = g/6 → weight = 60/6 = 10 N.'] },
  ['q-ph-4']),

C('s-ph-pressure', 'physics', 'Pressure — Force Spread Over Area',
  'Same force, smaller area → more pressure.',
  [
    h('1. Basic concept'),
    p('Pressure tells you how concentrated a force is on a surface.'),
    F('Pressure = Force ÷ Area', [['Pressure', 'pascal (Pa) = N/m²'], ['Force', 'newtons'], ['Area', 'm²']]),
    h('2. Simple explanation'),
    p('A sharp nail goes into wood because all your push is concentrated on a tiny area. The same push with your thumb tip does nothing.'),
    h('3. Real-life example'),
    li(['Camel feet are wide → low pressure → no sinking in sand.', 'A knife is sharpened → small area → high pressure → cuts.', 'Skis are long and wide → spread weight on snow.']),
    h('4. Important facts'),
    li(['Liquids and gases also exert pressure, in ALL directions.', 'Atmospheric pressure ~101,325 Pa (1 atm).', 'In liquids, pressure increases with DEPTH.']),
    h('5. Application'),
    li(['Dams are thicker at the bottom (water pressure is higher there).', 'Suction cups work by removing air → atmospheric pressure pushes them on.']),
    trap('Pressure is force PER AREA — a heavy elephant on a wide board can exert less pressure than a thin heel.'),
    mem('Heel vs snowshoe', 'High heel = tiny area = pain. Snowshoe = big area = float on snow. Same idea both ways.'),
    rec('P = F/A. Small area → big pressure.'),
  ],
  { text: 'Why are the feet of camels broad and flat?', options: ['To run faster', 'To reduce pressure on sand', 'To increase force', 'To keep balance while sitting'], answer: 1,
    steps: ['Broad feet = large area.', 'P = F/A → larger area → smaller pressure → they do not sink.'] },
  ['q-ph-5']),

C('s-ph-float', 'physics', 'Floating and Sinking — Archimedes',
  'Objects lighter than water (by volume) float.',
  [
    h('1. Basic concept'),
    p('When an object sits in water, water pushes it UP with a force equal to the weight of water pushed aside. That is Archimedes’ principle.'),
    NR('No formula needed — use this rule: density less than water → floats; density more than water → sinks. A ship floats because its HOLLOW shape makes its average density low.'),
    h('2. Simple explanation'),
    p('A solid steel cube sinks (steel is ~8× denser than water). A steel SHIP is mostly air inside — its average density drops below water → it floats.'),
    h('3. Real-life example'),
    li(['An egg floats in salty water (salt raises water density).', 'A hot-air balloon floats in air — same principle in gases.', 'Submarines fill tanks with water to sink, push it out to rise.']),
    h('4. Important facts'),
    li(['Density of water = 1000 kg/m³ = 1 g/cm³.', 'Ice floats — it is about 9% less dense than water.', 'Buoyant force acts vertically UPWARD.']),
    trap('“Heavy things sink” is false. A 200,000-tonne ship floats; a small iron nail sinks. DENSITY decides, not weight.'),
    mem('Ship of steel, heart of air', 'The ship is steel outside, air inside — light at heart, so it floats.'),
    rec('Compare densities, not weights. Ship = hollow = low average density.'),
  ],
  { text: 'A ship made of steel floats on water because:', options: ['steel is lighter than water', 'its average density is less than water due to the hollow shape', 'sea water pushes all ships up', 'ships are painted to resist water'], answer: 1,
    steps: ['The hollow hull traps air.', 'Average density = total mass ÷ total volume drops below water.', 'Lower density → floats.'] },
  ['q-ph-6']),

C('s-ph-heat', 'physics', 'Heat and Temperature',
  'Heat is energy in flow; temperature is how hot something is.',
  [
    h('1. Basic concept'),
    p('HEAT is thermal energy moving from a hot body to a cold body. TEMPERATURE is the measure of hotness — the average energy of particles.'),
    h('2. Simple explanation'),
    p('A cup of tea and a bucket of hot water may have the SAME temperature, but the bucket holds far more HEAT (more particles).'),
    h('3. Real-life example'),
    li(['A metal spoon in hot tea heats faster than a plastic one — metals conduct heat.', 'Gaps in railway tracks: metals EXPAND when heated.', 'Sea breeze: land heats faster, air rises, sea air moves in.']),
    h('4. Important facts'),
    li(['Heat flows: conduction (solids, contact), convection (liquids/gases, currents), radiation (no medium — sunlight).', 'SI unit of temperature: kelvin (K). 0 K = −273.15 °C (absolute zero).', '0 °C = 273.15 K; to convert: K = °C + 273.']),
    E('Example — convert 27 °C to kelvin', ['K = 27 + 273 = 300 K.'], '300 K'),
    h('5. Application'),
    li(['Thermos flask blocks all three heat transfers.', 'Dark clothes absorb more radiant heat — why summer white is cooler.']),
    trap('Temperature ≠ heat. A spark (high temperature, tiny heat) cannot warm a room; a bucket of warm water (low temperature, lots of heat) can.'),
    mem('Cup vs bucket', 'Cup of tea = hot-tempered but small. Bucket of warm water = mild but massive. Temperature is temper; heat is total muscle.'),
    rec('K = °C + 273. Heat flows hot → cold, three ways.'),
  ],
  { text: 'The SI unit of temperature is:', options: ['degree Celsius', 'kelvin', 'joule', 'calorie'], answer: 1,
    steps: ['SI base unit of temperature = kelvin (K).', 'Celsius is common but not the SI unit.'] },
  ['q-ph-7']),

C('s-ph-light', 'physics', 'Light — Reflection and Refraction',
  'Mirrors bounce light; lenses bend light.',
  [
    h('1. Basic concept'),
    p('REFLECTION is light bouncing off a surface (mirror). REFRACTION is light BENDING when it passes from one transparent material to another (air → glass).'),
    h('2. Simple explanation'),
    li(['Plane mirror image: same size, upright, laterally inverted (left-right swapped), virtual (behind the mirror).', 'Refraction happens because light changes SPEED in the new material.']),
    h('3. Real-life example'),
    li(['A straw looks broken at the water line — refraction.', 'A pencil appears bent in a glass of water.', 'Mirages on hot roads — refraction through layers of air.', 'Rainbows — refraction + dispersion inside raindrops.']),
    h('4. Important facts'),
    li(['Angle of incidence = angle of reflection.', 'White light = 7 colours (VIBGYOR); dispersion splits them.', 'Convex lens converges (used in magnifiers); concave lens diverges.', 'The human eye uses a convex lens to focus.']),
    h('5. Application'),
    li(['Rear-view mirrors: convex (wide field of view).', 'Dentists use concave mirrors to see enlarged teeth.']),
    trap('Mirror image is laterally inverted — LEFT↔RIGHT, not upside down.'),
    mem('Lateral swap', 'Your mirror twin raises the LEFT hand when you raise your right — the mirror swaps sides, not top/bottom.'),
    rec('Bounce = reflection; bend = refraction; split = dispersion.'),
  ],
  { text: 'The image formed by a PLANE mirror is:', options: ['real and inverted', 'virtual and laterally inverted', 'real and magnified', 'virtual and upside down'], answer: 1,
    steps: ['Plane mirror → virtual image, same size.', 'Left and right are swapped → laterally inverted.'] },
  ['q-ph-8']),

C('s-ph-elec', 'physics', 'Electricity — Current, Voltage, Resistance',
  'Ohm’s law: V = I × R.',
  [
    h('1. Basic concept'),
    p('CURRENT is the flow of electric charge. VOLTAGE is the push that drives it. RESISTANCE is the obstacle that slows it.'),
    F('V = I × R', [
      ['V', 'voltage (volt) — the push'],
      ['I', 'current (ampere) — the flow'],
      ['R', 'resistance (ohm, Ω) — the obstacle'],
    ]),
    h('2. Simple explanation'),
    p('Think of water: voltage = water pressure, current = the flow rate, resistance = a narrow pipe. More pressure → more flow. Narrower pipe → less flow.'),
    E('Example — a 5 V battery drives current through a 10 Ω resistor', ['I = V ÷ R = 5 ÷ 10 = 0.5 A.'], '0.5 A'),
    h('3. Real-life example'),
    li(['A fuse melts and breaks the circuit when current is too high — a safety sacrifice.', 'Thick wires have low resistance → less heating.', 'The heating element of an iron has HIGH resistance → becomes hot.']),
    h('4. Important facts'),
    li(['Series: same current, resistances ADD (R = R₁+R₂).', 'Parallel: same voltage, total resistance DROPS.', 'Electric power P = V × I; unit watt.', 'Household circuits are in PARALLEL.']),
    h('5. Application'),
    li(['Fuse in series protects appliances.', 'LED bulbs: low power, same light.']),
    trap('In parallel, adding MORE devices LOWERS total resistance and RAISES total current — that is how overload happens.'),
    mem('Water pipe trio', 'Volt = pressure. Ampere = flow. Ohm = narrowness. One picture covers all three.'),
    rec('V = IR; series R adds; parallel R drops; P = VI.'),
  ],
  { text: 'A potential difference of 12 V drives a current of 3 A. The resistance is:', options: ['36 Ω', '4 Ω', '0.25 Ω', '15 Ω'], answer: 1,
    steps: ['R = V ÷ I = 12 ÷ 3 = 4 Ω.'] },
  ['q-ph-9']),

C('s-ph-sound', 'physics', 'Sound — Vibrations That Travel',
  'Sound needs a medium; it cannot travel through vacuum.',
  [
    h('1. Basic concept'),
    p('Sound is produced by VIBRATIONS and travels as a wave through a medium — solid, liquid or gas.'),
    h('2. Simple explanation'),
    p('Particles of the medium vibrate and pass the push along, like a shoulder-to-shoulder crowd doing a wave. No particles (vacuum) → no sound.'),
    h('3. Real-life example'),
    li(['You see lightning before you hear thunder — light is faster.', 'Press your ear to a railway track and you hear a train early — sound travels faster in solids.']),
    h('4. Important facts'),
    li(['Speed of sound in air ≈ 343 m/s (≈ 340) at room temperature.', 'Sound travels fastest in SOLIDS, slowest in GASES.', 'Echo = reflected sound; needs a hard surface ≥ ~17 m away (for humans).', 'Human hearing range: 20 Hz to 20,000 Hz.', 'Loudness ← amplitude; pitch ← frequency.']),
    h('5. Application'),
    li(['SONAR uses echoes to measure sea depth.', 'Stethoscope: sound through solid/liquid paths.']),
    trap('Light needs no medium; sound does. Space battles are silent — explosions in vacuum cannot be heard.'),
    mem('Railway trick', 'Ear on the track hears the train first — solids beat air as sound couriers: solid > liquid > gas.'),
    rec('Sound = vibration; needs a medium; ~340 m/s in air; echo = reflection.'),
  ],
  { text: 'Sound cannot travel through:', options: ['steel', 'water', 'air', 'vacuum'], answer: 3,
    steps: ['Sound needs particles to vibrate.', 'Vacuum has no particles → no sound.'] },
  ['q-ph-10']),

/* ================= CHEMISTRY ================= */
C('s-ch-matter', 'chemistry', 'States of Matter and Their Changes',
  'Solid, liquid, gas — and the names of the changes between them.',
  [
    h('1. Basic concept'),
    p('Matter exists mainly as solid (fixed shape), liquid (flows, fixed volume) and gas (fills any space). Heat gives particles more energy and loosens them.'),
    T(['Change', 'Name', 'Example'], [
      ['Solid → liquid', 'Melting', 'Ice → water'],
      ['Liquid → gas', 'Boiling/evaporation', 'Water → steam'],
      ['Gas → liquid', 'Condensation', 'Dew on a cold glass'],
      ['Liquid → solid', 'Freezing', 'Water → ice'],
      ['Solid → gas (direct)', 'Sublimation', 'Camphor, naphthalene balls, dry ice'],
    ]),
    h('2. Simple explanation'),
    p('Naphthalene balls disappear without wetting anything — they sublime: solid straight to gas.'),
    h('3. Real-life example'),
    li(['Cooling of a cold drink can → water drops from air (condensation).', 'Drying wet clothes = evaporation (faster with wind, heat, more surface).']),
    h('4. Important facts'),
    li(['Melting point of ice = 0 °C; boiling point of water = 100 °C (at sea level).', 'Evaporation happens at ANY temperature from the surface; boiling happens at one temperature throughout.', 'Plasma is a fourth state (in stars, neon signs).']),
    trap('Melting (solid→liquid) vs dissolving (solid mixed INTO liquid) are different. Sugar dissolving is not melting.'),
    mem('Sublimation squad', 'Camphor, naphthalene, dry ice, iodine — the disappear-without-wetting squad.'),
    rec('Melt S→L, freeze L→S, boil L→G, condense G→L, sublime S→G.'),
  ],
  { text: 'Naphthalene balls kept in clothes slowly disappear. This change is:', options: ['melting', 'evaporation', 'sublimation', 'condensation'], answer: 2,
    steps: ['Solid naphthalene turns directly into gas.', 'Solid → gas directly = sublimation.'] },
  ['q-ch-1']),

C('s-ch-atom', 'chemistry', 'Atoms, Molecules, Elements and Compounds',
  'Atom = smallest reacting particle; element = one kind of atom.',
  [
    h('1. Basic concept'),
    li([
      'ATOM — smallest particle of an element that takes part in a chemical reaction.',
      'MOLECULE — two or more atoms joined together (O₂, H₂O).',
      'ELEMENT — made of ONE kind of atom (iron, oxygen, gold).',
      'COMPOUND — two or more elements chemically joined in a FIXED ratio (H₂O is always 2:1).',
      'MIXTURE — substances just placed together, any ratio, easily separated (air, salt water).',
    ]),
    h('2. Simple explanation'),
    p('A compound is like a marriage (fixed, needs chemical effort to break). A mixture is like roommates (any ratio, easy to separate).'),
    h('3. Real-life example'),
    li(['Air = mixture (N₂ 78%, O₂ 21%).', 'Water = compound (H and O chemically bonded).', 'Brass = mixture (copper + zinc).']),
    h('4. Important facts'),
    li(['Smallest particle of a compound that keeps its properties = molecule.', 'Elements: ~118 known; first 20 are exam favourites.', 'Symbols: Na (sodium, from natrium), K (potassium, from kalium), Fe (iron, ferrum).']),
    trap('Water (H₂O) is a COMPOUND, not a mixture — the H and O cannot be filtered apart.'),
    mem('Marriage vs roommates', 'Compound = marriage (chemical bond, fixed ratio). Mixture = roommates (any ratio, easy split).'),
    rec('Atom→element; molecule→compound; mixture = no bond.'),
  ],
  { text: 'Which of the following is a COMPOUND?', options: ['Air', 'Brass', 'Water', 'Brine'], answer: 2,
    steps: ['Air, brass, brine are mixtures.', 'Water = H and O chemically bonded in fixed 2:1 ratio → compound.'] },
  ['q-ch-2']),

C('s-ch-acid', 'chemistry', 'Acids, Bases and Salts',
  'Acids sour, bases bitter-slippery; pH below 7 = acid.',
  [
    h('1. Basic concept'),
    p('Acids release H⁺ ions in water (lemon, curd, vinegar). Bases release OH⁻ ions (soap, lime water, milk of magnesia). Acid + base → salt + water (neutralisation).'),
    h('2. Simple explanation'),
    p('pH is a 0–14 scale of acidity. 7 = neutral. Below 7 = acid; above 7 = base. Stomach acid ≈ 1.5–2; soap ≈ 9–10.'),
    h('3. Real-life example'),
    li(['Antacid (milk of magnesia, a base) cures acidity by neutralising HCl.', 'Lime is added to acidic soil to raise pH for crops.', 'A wasp sting can be soothed with vinegar (acid) — stings are alkaline.']),
    h('4. Important facts'),
    li(['Litmus: acid → blue turns red; base → red turns blue.', 'Turmeric, red cabbage = natural indicators.', 'Common salts: NaCl (table), baking soda NaHCO₃, washing soda Na₂CO₃, bleaching powder Ca(OCl)Cl.']),
    T(['Substance', 'pH idea'], [['Lemon juice', '~2 (acid)'], ['Pure water', '7 (neutral)'], ['Blood', '~7.4 (slightly basic)'], ['Soap solution', '~9–10 (basic)']]),
    trap('All acids are not dangerous (vitamin C is an acid) and all bases are not soaps. Judge by pH, not by look.'),
    mem('Sour vs bitter', 'Acid = ANbinu (sour) — A for Acid. Base = bitter + slippery like soap. pH 7 = perfect water.'),
    rec('Acid <7 < Base; litmus swap; antacid = neutralisation.'),
  ],
  { text: 'Milk of magnesia relieves indigestion because it:', options: ['adds acid to the stomach', 'neutralises excess stomach acid', 'kills bacteria', 'speeds digestion'], answer: 1,
    steps: ['It is a base (magnesium hydroxide).', 'Base + acid (HCl) → salt + water = neutralisation.'] },
  ['q-ch-3']),

C('s-ch-metal', 'chemistry', 'Metals and Non-metals',
  'Metals shine, conduct, ring; non-metals mostly break and insulate.',
  [
    h('1. Basic concept'),
    p('Metals are generally shiny, malleable (hammer into sheets), ductile (pull into wires), good conductors of heat and electricity, and sonorous (ring when struck).'),
    h('2. Simple explanation + examples'),
    li(['Exceptions the exam loves: MERCURY — the only liquid metal.', 'SODIUM and POTASSIUM are metals so soft you can cut them, and they react hard with water.', 'GRAPHITE — the only non-metal that conducts electricity.', 'IODINE — a non-metal that shines.']),
    h('3. Real-life example'),
    li(['Copper wires (conduct), aluminium foil (malleable), bells of bronze (sonorous).', 'Diamond and graphite are both carbon — hardest vs slippery.']),
    h('4. Important facts'),
    li(['Best conductors: silver > copper > gold > aluminium.', 'Rusting = iron + oxygen + moisture → hydrated iron oxide.', 'Galvanisation = zinc coating to stop rust.', 'Metals form BASIC oxides; non-metals form ACIDIC oxides (CO₂ → carbonic acid).']),
    trap('Graphite conducts despite being a non-metal — the favourite exception question.'),
    mem('Exception quartet', 'Liquid metal = mercury. Non-metal conductor = graphite. Shining non-metal = iodine. Metal cut with a knife = sodium.'),
    rec('Metals: malleable, ductile, sonorous, conductors. Exceptions: Hg liquid, graphite conducts.'),
  ],
  { text: 'Which non-metal is a good conductor of electricity?', options: ['Sulphur', 'Graphite', 'Phosphorus', 'Oxygen'], answer: 1,
    steps: ['Graphite (form of carbon) has free electrons between layers.', 'It conducts — the famous non-metal exception.'] },
  ['q-ch-4']),

C('s-ch-react', 'chemistry', 'Chemical Reactions and Their Types',
  'New substance = chemical change; learn the four classic types.',
  [
    h('1. Basic concept'),
    p('In a chemical reaction, bonds break and new substances form with new properties. Signs: gas bubbles, colour change, temperature change, precipitate.'),
    T(['Type', 'Pattern', 'Example'], [
      ['Combination', 'A + B → C', '2H₂ + O₂ → 2H₂O'],
      ['Decomposition', 'A → B + C', 'CaCO₃ →heat→ CaO + CO₂'],
      ['Displacement', 'A + BC → AC + B', 'Fe + CuSO₄ → FeSO₄ + Cu'],
      ['Double displacement', 'AB + CD → AD + CB', 'NaCl + AgNO₃ → AgCl↓ + NaNO₃'],
      ['Oxidation–reduction', 'oxygen gained / lost', 'rusting; ZnO + C → Zn + CO'],
    ]),
    h('2. Simple explanation'),
    p('Displacement needs a MORE reactive metal pushing out a less reactive one. Iron displaces copper from copper sulphate — that is why the nail turns brownish.'),
    h('3. Real-life example'),
    li(['Rusting = slow oxidation.', 'Browning of a cut apple = oxidation.', 'Digestion = decomposition of food.', 'Curding of milk = chemical change.']),
    h('4. Important facts'),
    li(['Reactivity series (high→low): K > Na > Ca > Mg > Al > Zn > Fe > Pb > H > Cu > Ag > Au.', 'Exothermic = heat released (respiration, burning); endothermic = heat absorbed (photosynthesis).']),
    trap('Melting ice is a PHYSICAL change (same substance). Burning paper is CHEMICAL (new substances).'),
    mem('Dance floor rule', 'Displacement = a stronger dancer cuts in and takes the partner (sulphate) away from the weaker one.'),
    rec('Combine, decompose, displace, double-displace; OIL RIG (Oxidation Is Loss of electrons, Reduction Is Gain).'),
  ],
  { text: 'Iron nails kept in copper sulphate solution become coated with copper. The reaction type is:', options: ['combination', 'decomposition', 'displacement', 'double displacement'], answer: 2,
    steps: ['Iron is more reactive than copper.', 'Fe pushes Cu out of CuSO₄: Fe + CuSO₄ → FeSO₄ + Cu.', 'One element replaces another = displacement.'] },
  ['q-ch-5']),

C('s-ch-fuel', 'chemistry', 'Combustion and Fuels',
  'Burning needs fuel + oxygen + heat; know the common fuel gases.',
  [
    h('1. Basic concept'),
    p('Combustion is a fast chemical reaction of a substance with oxygen, releasing heat and light. Fire needs all THREE: fuel, oxygen (air), heat — remove one and the fire dies.'),
    h('2. Simple explanation'),
    p('LPG, CNG and biogas are exam favourites: LPG is mainly butane/propane; CNG is mainly methane; biogas is mainly methane + CO₂.'),
    h('3. Real-life example'),
    li(['Smothering a frying-pan fire with a lid removes oxygen.', 'Water cools the heat away from burning paper.']),
    h('4. Important facts'),
    li(['Calorific value = heat per kg of fuel (kJ/kg). Hydrogen has the highest.', 'Complete combustion → CO₂; INCOMPLETE combustion → CO (poisonous) + soot.', 'Acid rain comes from burning coal with sulphur (SO₂).']),
    trap('Carbon monoxide is the SILENT killer — colourless, odourless, from incomplete burning. CO₂ gets the blame in gossip.'),
    mem('Fire triangle', 'Fuel + O₂ + heat = fire triangle. Break any side — smother (O₂), cool (heat), remove (fuel).'),
    rec('LPG butane; CNG methane; CO from incomplete burning is the poisonous one.'),
  ],
  { text: 'The main component of CNG is:', options: ['butane', 'methane', 'propane', 'ethane'], answer: 1,
    steps: ['CNG (compressed natural gas) is mainly methane (CH₄).', 'LPG is mainly butane/propane.'] },
  ['q-ch-6']),

C('s-ch-water', 'chemistry', 'Water, Solutions and Hardness',
  'Universal solvent; hard water refuses to lather.',
  [
    h('1. Basic concept'),
    p('Water dissolves more substances than any other liquid — the “universal solvent”. A SOLUTION = solute dissolved in solvent (salt in water).'),
    h('2. Simple explanation'),
    li(['Saturated solution: no more solute dissolves at that temperature.', 'Colloid: particles too small to settle but scatter light (Tyndall effect — milk, fog).', 'Suspension: particles settle (sand in water).']),
    h('3. Real-life example'),
    p('HARD water (dissolved calcium & magnesium salts) wastes soap — no lather, white scum in kettles and pressure cookers. SOFT water lathers easily.'),
    h('4. Important facts'),
    li(['Boiling removes temporary hardness.', 'Washing soda removes permanent hardness.', 'Heavy water D₂O is used in nuclear reactors.', 'Water expands on freezing — ice floats (rare behaviour!).']),
    trap('Distilled water is pure but NOT good drinking water — it lacks minerals. Rain water is naturally soft.'),
    mem('Scum detective', 'White scale in your kettle = hard water’s visiting card (Ca/Mg salts).'),
    rec('Hard = Ca/Mg salts, no lather; soft = easy lather; boiling kills temporary hardness.'),
  ],
  { text: 'Hardness of water is caused mainly by dissolved:', options: ['sodium and potassium salts', 'calcium and magnesium salts', 'iron and zinc salts', 'chlorine and iodine'], answer: 1,
    steps: ['Calcium and magnesium bicarbonates/chlorides/sulphates make water hard.', 'They stop soap from lathering.'] },
  ['q-ch-7']),

/* ================= LIFE SCIENCES ================= */
C('s-ls-cell', 'life-sciences', 'The Cell — Unit of Life',
  'All living things are made of cells; plant and animal cells differ.',
  [
    h('1. Basic concept'),
    p('The cell is the smallest structural and functional unit of life. Robert Hooke first saw “cells” in cork (1665).'),
    h('2. Simple explanation'),
    li(['Nucleus — control room (holds DNA).', 'Cell membrane — gatekeeper of the cell.', 'Cytoplasm — jelly where reactions happen.', 'Mitochondria — powerhouses (energy release).']),
    h('3. Plant vs animal cell (exam favourite)'),
    T(['Part', 'Plant', 'Animal'], [
      ['Cell wall', '✓ present', '✗ absent'],
      ['Chloroplast', '✓ present', '✗ absent'],
      ['Large vacuole', '✓', 'small or absent'],
      ['Centrosome', '✗', '✓'],
    ]),
    h('4. Real-life example'),
    p('The crispness of a fresh salad = water held in cell vacuoles. Wilted leaves = vacuoles lost water.'),
    h('5. Important facts'),
    li(['Largest cell organelle: nucleus (in animals). Largest cell: ostrich egg.', 'Smallest cells: bacteria (mycoplasma even smaller).', 'Largest single-celled organism: some algae like Amoeba are single cells.']),
    trap('The cell wall is OUTSIDE the cell membrane and only plants have it — it gives the box shape.'),
    mem('Room analogy', 'Nucleus = boss’s cabin. Membrane = security gate. Mitochondria = generator room. Cell wall = the compound wall (plants only).'),
    rec('Plant-only: cell wall + chloroplast + big vacuole.'),
  ],
  { text: 'Which of these is present in a plant cell but NOT in an animal cell?', options: ['Nucleus', 'Cell wall', 'Cell membrane', 'Mitochondria'], answer: 1,
    steps: ['Nucleus, membrane, mitochondria are in both.', 'Cell wall (and chloroplasts) are plant-only.'] },
  ['q-ls-1']),

C('s-ls-photo', 'life-sciences', 'Photosynthesis — Plants Make Food',
  'Leaves use sunlight + CO₂ + water to make glucose and oxygen.',
  [
    h('1. Basic concept'),
    p('Green plants make their own food using sunlight, water and carbon dioxide. Chlorophyll (the green pigment) traps the sunlight.'),
    F('6CO₂ + 6H₂O —sunlight/chlorophyll→ C₆H₁₂O₆ + 6O₂', [
      ['CO₂', 'carbon dioxide — enters through stomata (leaf pores)'],
      ['H₂O', 'water — from roots'],
      ['C₆H₁₂O₆', 'glucose — the food made'],
      ['O₂', 'oxygen — the by-product we breathe'],
    ]),
    h('2. Simple explanation'),
    p('Leaf = solar kitchen. Sun = stove, chlorophyll = the cook, CO₂ + water = ingredients, glucose = the dish, oxygen = kitchen exhaust.'),
    h('3. Real-life example'),
    p('Money plants kept in a dark room turn pale — without light the kitchen cannot run, chlorophyll fades.'),
    h('4. Important facts'),
    li(['Stomata: pores mostly on the leaf’s LOWER side; they also release water vapour (transpiration).', 'Plants respire ALL the time; they photosynthesise only in light.', 'Insectivorous plants (pitcher plant) trap insects for nitrogen in poor soil.']),
    trap('Plants do NOT photosynthesise at night — but they DO respire at night (that is why bedrooms full of plants at night reduce oxygen slightly).'),
    mem('Kitchen picture', 'Leaf kitchen: sunlight stove + chlorophyll cook + CO₂ & water ingredients → glucose thali + oxygen exhaust.'),
    rec('6CO₂ + 6H₂O → glucose + 6O₂; stomata = pores; chlorophyll = green catcher.'),
  ],
  { text: 'The gas used by plants during photosynthesis is:', options: ['oxygen', 'nitrogen', 'carbon dioxide', 'hydrogen'], answer: 2,
    steps: ['Plants take IN carbon dioxide.', 'Oxygen is released as a by-product.'] },
  ['q-ls-2']),

C('s-ls-circ', 'life-sciences', 'Circulatory System — Heart and Blood',
  'Heart = double pump; blood carries oxygen, food and waste.',
  [
    h('1. Basic concept'),
    p('The heart (a muscle, size of your fist) pumps blood through blood vessels. Humans have a 4-chambered heart: two atria (receive) + two ventricles (pump out).'),
    h('2. Simple explanation'),
    li(['Arteries carry blood AWAY from the heart (usually oxygen-rich, thick walls).', 'Veins carry blood TO the heart (usually oxygen-poor, have valves).', 'Capillaries — one-cell-thick exchange streets.']),
    h('3. Real-life example'),
    p('Why does the doctor check your pulse at the wrist? An artery runs close to the skin there and mirrors each heartbeat.'),
    h('4. Blood parts (exam favourites)'),
    T(['Part', 'Job'], [
      ['RBC', 'carries oxygen (haemoglobin — iron-rich, red)'],
      ['WBC', 'army — fights germs'],
      ['Platelets', 'clot blood at cuts'],
      ['Plasma', 'liquid carrier of nutrients, waste, hormones'],
    ]),
    li(['Universal donor: O negative. Universal recipient: AB positive.', 'Normal adult heart rate ≈ 72 beats/min.', 'Blood pressure measured in systolic/diastolic (≈120/80 mm Hg).']),
    trap('Haemoglobin is in RBCs, not floating free in plasma. And veins need valves because blood returns at LOW pressure.'),
    mem('Delivery trio', 'RBC = oxygen scooter. WBC = police jeep. Platelets = repair kit. Plasma = the road itself.'),
    rec('4 chambers; arteries away, veins to; RBC-O₂; universal donor O−.'),
  ],
  { text: 'Which blood cells help in clotting of blood?', options: ['RBC', 'WBC', 'Platelets', 'Plasma'], answer: 2,
    steps: ['Platelets gather at a cut and trigger clotting.', 'RBC carries oxygen; WBC fights infection.'] },
  ['q-ls-3']),

C('s-ls-digest', 'life-sciences', 'Digestive System — Food’s Journey',
  'Mouth → stomach → small intestine (absorption) → large intestine.',
  [
    h('1. Basic concept'),
    p('Digestion breaks food into tiny soluble particles the blood can absorb. It is both mechanical (chewing, churning) and chemical (enzymes).'),
    T(['Station', 'What happens'], [
      ['Mouth', 'saliva (amylase) starts starch digestion'],
      ['Stomach', 'acid (HCl) + pepsin digest proteins'],
      ['Small intestine', 'main absorption — villi increase surface area'],
      ['Large intestine', 'water absorption; waste forms'],
      ['Liver', 'largest gland; bile breaks fats'],
    ]),
    h('2. Simple explanation'),
    p('Villi are millions of tiny fingers inside the small intestine — they give a huge absorption area, like a towel’s fibres soaking water.'),
    h('3. Real-life example'),
    p('Bile from the liver is stored in the gall bladder. A fatty meal makes the gall bladder squeeze bile out — that is why heavy fried food can trigger gallbladder pain.'),
    h('4. Important facts'),
    li(['Largest gland: liver. Bile makes the food medium alkaline and emulsifies fat.', 'Small intestine is the LONGEST part of the alimentary canal.', 'Appendix: a vestigial organ.']),
    trap('Bile contains NO enzymes — it only emulsifies fat (breaks it into droplets) and makes medium alkaline.'),
    mem('Villi towel', 'Small intestine lined with villi like a towel’s fibres — maximum soak per swipe.'),
    rec('Mouth-amylase, stomach-HCl, liver-bile, small intestine-absorb.'),
  ],
  { text: 'The largest gland in the human body is the:', options: ['pancreas', 'liver', 'salivary gland', 'thyroid'], answer: 1,
    steps: ['Liver is the largest gland.', 'It makes bile and processes nutrients.'] },
  ['q-ls-4']),

C('s-ls-nerv', 'life-sciences', 'Nervous System — Control and Reflexes',
  'Brain + spinal cord + nerves; reflexes bypass thinking.',
  [
    h('1. Basic concept'),
    p('The nervous system receives signals, interprets them and commands responses. Neuron = nerve cell, its unit.'),
    li(['Brain: cerebrum (thinking), cerebellum (balance, posture), medulla (heartbeat, breathing).', 'Spinal cord: the main cable from brain.']),
    h('2. Simple explanation'),
    p('A REFLEX (touching a hot pan) travels: receptor → spinal cord → muscle. The brain is informed AFTERWARD — that speed saves your skin.'),
    h('3. Real-life example'),
    li(['Knee-jerk at the doctor’s tap = spinal reflex.', 'Salivating at the smell of food = reflex + brain (conditioned).']),
    h('4. Important facts'),
    li(['Reflex arc passes through the SPINAL CORD, not the brain.', 'Three types of nerves: sensory (to brain/CNS), motor (from CNS to muscles), mixed.', 'Brain is protected by the skull + cerebrospinal fluid.']),
    trap('Reflex actions are NOT decided by the brain — the spinal cord handles them to save time.'),
    mem('Fire alarm', 'Reflex = fire alarm that rings directly at the guard house (spinal cord); the head office (brain) gets the report later.'),
    rec('Cerebrum think, cerebellum balance, medulla heartbeat; reflex = spinal cord.'),
  ],
  { text: 'Reflex actions are controlled by the:', options: ['cerebrum', 'cerebellum', 'spinal cord', 'medulla'], answer: 2,
    steps: ['Reflex arcs short-circuit through the spinal cord.', 'This saves the time of going up to the brain.'] },
  ['q-ls-5']),

C('s-ls-vit', 'life-sciences', 'Vitamins and Deficiency Diseases',
  'Learn the vitamin table — one mark, every exam.',
  [
    h('1. Basic concept'),
    p('Vitamins are needed in tiny amounts but their absence causes specific deficiency diseases.'),
    T(['Vitamin', 'Deficiency disease'], [
      ['A', 'Night blindness'],
      ['B1', 'Beriberi'],
      ['B12', 'Anaemia (pernicious)'],
      ['C', 'Scurvy (bleeding gums)'],
      ['D', 'Rickets (children), soft bones'],
      ['E', 'fertility/skin issues (rare)'],
      ['K', 'Poor clotting of blood'],
    ]),
    h('2. Simple explanation'),
    p('Vitamins A, D, E, K are FAT-soluble (stored in the body); B and C are WATER-soluble (need daily refill).'),
    h('3. Real-life example'),
    li(['Sailors of old got scurvy — no fresh fruit on long voyages (vitamin C).', 'Sunlight on skin makes vitamin D — why sunlight is called the sunshine vitamin.']),
    h('4. Important facts'),
    li(['Iodine deficiency → goitre (use iodised salt).', 'Iron deficiency → anaemia.', 'Calcium + vitamin D → strong bones.']),
    trap('Rickets = vitamin D (bones), scurvy = vitamin C (gums) — the most-swapped pair.'),
    mem('“Ko milli K for Klotting”', 'Vitamin K = Klotting. Scurvy’s C: “Citrus for bleeding gums”. Night A: “A for Amazing eyes at night”.'),
    rec('A night-blind, B1 beriberi, C scurvy, D rickets, K clotting.'),
  ],
  { text: 'Scurvy is caused by the deficiency of vitamin:', options: ['A', 'B1', 'C', 'D'], answer: 2,
    steps: ['Scurvy = bleeding gums, weakness.', 'Cause: lack of vitamin C (ascorbic acid) — fresh fruits.'] },
  ['q-ls-6']),

C('s-ls-disease', 'life-sciences', 'Diseases and Their Germs',
  'Match the disease to its cause and carrier.',
  [
    h('1. Basic concept'),
    p('Infectious diseases are caused by pathogens: bacteria, viruses, fungi, protozoa. Each disease has a classic cause/carrier pair that exams love.'),
    T(['Disease', 'Cause', 'Spread by'], [
      ['Malaria', 'protozoa (Plasmodium)', 'female Anopheles mosquito'],
      ['Dengue', 'virus', 'Aedes mosquito'],
      ['Tuberculosis', 'bacteria', 'air droplets'],
      ['Cholera', 'bacteria', 'contaminated water'],
      ['AIDS', 'virus (HIV)', 'blood, unsafe contact'],
      ['Common cold', 'virus', 'air droplets'],
      ['Ringworm', 'fungus', 'skin contact'],
    ]),
    h('2. Simple explanation'),
    p('Bacteria are living cells — antibiotics kill them. Viruses hijack YOUR cells — antibiotics do NOT work on colds/flu.'),
    h('3. Real-life example'),
    p('Vaccination trains the immune system with a weakened germ “mugshot”, so the body reacts fast later (e.g., BCG for TB, polio drops).'),
    h('4. Important facts'),
    li(['Penicillin (Alexander Fleming) — first antibiotic.', 'Malaria parasite discovered by Ronald Ross.', 'AIDS virus attacks the immune system’s CD4 cells.']),
    trap('Antibiotics do nothing against viruses — finishing a cold course of antibiotics is a myth (follow doctor advice).'),
    mem('Carrier pairs', 'Malaria → female Anopheles. Dengue → Aedes (day-biter). Cholera → dirty water. TB → air.'),
    rec('Bacteria-living (antibiotics work); virus-hijacker (antibiotics fail).'),
  ],
  { text: 'Malaria is transmitted by the bite of:', options: ['male Anopheles mosquito', 'female Anopheles mosquito', 'Aedes mosquito', 'housefly'], answer: 1,
    steps: ['Malaria (Plasmodium protozoa) is spread by the FEMALE Anopheles mosquito.', 'Dengue is spread by Aedes.'] },
  ['q-ls-7']),

C('s-ls-hormone', 'life-sciences', 'Hormones — Chemical Messengers',
  'Slow but long-lasting signals from endocrine glands.',
  [
    h('1. Basic concept'),
    p('Hormones are chemical messages released directly into the blood by endocrine (ductless) glands. They act slowly but last long.'),
    T(['Gland / hormone', 'Job'], [
      ['Insulin (pancreas)', 'lowers blood sugar'],
      ['Thyroxine (thyroid)', 'needs iodine; controls metabolism'],
      ['Adrenaline (adrenal)', 'fight-or-flight'],
      ['Growth hormone (pituitary)', 'body growth'],
      ['Testosterone/oestrogen', 'male/female secondary characters'],
    ]),
    h('2. Simple explanation'),
    p('Nervous system = electric wires (fast, short-lived). Hormones = postal letters (slow, long-lasting).'),
    h('3. Real-life example'),
    li(['Exam fear → adrenaline → faster heartbeat, sweaty palms.', 'Goitre = swollen thyroid from iodine deficiency → use iodised salt.', 'Diabetes = insulin problem → blood sugar rises.']),
    h('4. Important facts'),
    li(['Pituitary = master gland (controls other glands).', 'Diabetes (insulin) — discovered treatment by Banting & Best; insulin from pancreas.', 'Too little growth hormone in childhood → dwarfism; too much → gigantism.']),
    trap('Insulin LOWERS sugar; it does not raise it. Glucagon (also pancreas) raises sugar.'),
    mem('Sugar see-saw', 'Insulin pushes sugar DOWN into cells; glucagon pushes it UP from stores. Two ends of one see-saw.'),
    rec('Insulin↓sugar (pancreas); thyroxine needs iodine; pituitary = master.'),
  ],
  { text: 'Insulin is secreted by the:', options: ['liver', 'pancreas', 'thyroid', 'pituitary'], answer: 1,
    steps: ['Insulin comes from the pancreas (islets of Langerhans).', 'It lowers blood glucose.'] },
  ['q-ls-8']),

C('s-ls-plants', 'life-sciences', 'Plant Transport — Xylem and Phloem',
  'Xylem up (water), phloem both ways (food).',
  [
    h('1. Basic concept'),
    p('Plants have two pipe systems inside the stem: xylem and phloem — together called vascular bundles.'),
    T(['Pipe', 'Carries', 'Direction'], [
      ['Xylem', 'water + minerals from roots', 'upward only'],
      ['Phloem', 'food (sucrose) made in leaves', 'both up and down'],
    ]),
    h('2. Simple explanation'),
    p('Think of a building: xylem = water pipes from the borewell (ground tank → roof), phloem = the tiffin delivery service carrying food wherever needed.'),
    h('3. Real-life example'),
    p('A ring of bark removed around a trunk (girdling) starves the roots — food cannot go down; the tree slowly dies.'),
    h('4. Important facts'),
    li(['Transpiration pull helps xylem water climb tall trees.', 'Root pressure also pushes water up.', 'Stomata control transpiration; guard cells open/close them.']),
    trap('Xylem carries water UP only; phloem carries food BOTH ways. Swap = the classic trap.'),
    mem('X-up, P-both', 'Xylem has an X like an up-arrow structure — water goes up. Phloem = Food pipe, delivers like a tiffin service (any direction).'),
    rec('Xylem water up; phloem food both ways.'),
  ],
  { text: 'Water and minerals are transported in plants through:', options: ['phloem', 'xylem', 'stomata', 'cambium'], answer: 1,
    steps: ['Xylem carries water + minerals upward from roots.', 'Phloem carries food.'] },
  ['q-ls-9']),
];

export const scienceQuestions = [
Q('q-ph-1', 'physics', { conceptId: 's-ph-motion', text: 'A car covers 150 km in 3 hours. Its average speed is:', options: ['45 km/h', '50 km/h', '55 km/h', '500 m/s'], answer: 1, difficulty: 1,
  tests: 'Average speed.', solution: ['Speed = 150 ÷ 3 = 50 km/h.'],
  wrongWhy: ['Arithmetic slip.', 'Correct.', 'Added wrongly.', 'Unit confusion.'],
  trap: 'Divide total distance by total time.', memory: { tech: 'Formula pattern', x: 's = d/t.' }, recall: 'Speed = distance ÷ time.' }),

Q('q-ph-2', 'physics', { conceptId: 's-ph-force', text: 'The recoil of a gun when fired is an example of:', options: ['inertia', 'Newton’s second law', 'Newton’s third law', 'gravitation'], answer: 2, difficulty: 1,
  tests: 'Newton’s third law.', solution: ['Gun pushes bullet forward; bullet pushes gun backward.', 'Equal and opposite = third law.'],
  wrongWhy: ['Inertia is resistance to change, not recoil.', 'F=ma is about magnitude.', 'Correct.', 'Gravity is unrelated.'],
  trap: 'Action and reaction act on different bodies.', memory: { tech: 'Push-back pair', x: 'Bullet forward, gun backward — one shot, two pushes.' }, recall: 'Recoil = 3rd law.' }),

Q('q-ph-3', 'physics', { conceptId: 's-ph-work', text: 'The commercial unit of electrical energy is:', options: ['watt', 'joule', 'kilowatt-hour', 'newton'], answer: 2, difficulty: 2,
  tests: 'Units of energy.', solution: ['Electricity bills use the “unit” = 1 kWh.', '1 kWh = 3.6 × 10⁶ J.'],
  wrongWhy: ['Watt is power.', 'Joule is SI energy but too small for billing.', 'Correct.', 'Newton is force.'],
  trap: 'Power (W) vs energy (kWh) — billing uses energy.', memory: { tech: 'Bill hook', x: 'Your electricity “unit” = 1 kWh.' }, recall: '1 unit = 1 kWh = 3.6 MJ.' }),

Q('q-ph-4', 'physics', { conceptId: 's-ph-gravity', text: 'The value of acceleration due to gravity (g) on Earth is approximately:', options: ['6.67 m/s²', '9.8 m/s²', '10.8 m/s²', '3.7 m/s²'], answer: 1, difficulty: 1,
  tests: 'Value of g.', solution: ['g ≈ 9.8 m/s² (≈10 for quick sums).', '6.67 is the gravitational CONSTANT G — a different quantity.'],
  wrongWhy: ['That is the constant G.', 'Correct.', 'Reversed digits.', 'That is Mars-ish.'],
  trap: 'g (local acceleration) ≠ G (universal constant).', memory: { tech: 'Contrast pair', x: 'Small g = 9.8 near Earth; Big G = 6.67 everywhere.' }, recall: 'g ≈ 9.8 m/s².' }),

Q('q-ph-5', 'physics', { conceptId: 's-ph-pressure', text: 'A sharp knife cuts better than a blunt one because:', options: ['it applies more force', 'it applies more pressure due to smaller area', 'it has more friction', 'it is made of better steel'], answer: 1, difficulty: 1,
  tests: 'P = F/A.', solution: ['Same force on a smaller edge area → higher pressure.', 'P = F/A.'],
  wrongWhy: ['Force comes from your arm, same either way.', 'Correct.', 'Friction is not the point.', 'Material is not the reason.'],
  trap: 'Sharpness = area, not force.', memory: { tech: 'Heel vs snowshoe', x: 'Tiny area → big pressure.' }, recall: 'P = F/A.' }),

Q('q-ph-6', 'physics', { conceptId: 's-ph-float', text: 'An iron nail sinks in water but a ship floats because:', options: ['iron ships are painted', 'the ship’s average density is less than water', 'sea waves push the ship', 'the ship is lighter than the nail'], answer: 1, difficulty: 2,
  tests: 'Archimedes / density.', solution: ['The hollow hull makes average density < water.', 'The nail’s density > water.'],
  wrongWhy: ['Paint is irrelevant.', 'Correct.', 'Waves are not the reason.', 'The ship is far heavier — density decides, not weight.'],
  trap: 'Weight never decides floating — density does.', memory: { tech: 'Ship of steel, heart of air', x: 'Hollow = low average density.' }, recall: 'Average density vs water decides.' }),

Q('q-ph-7', 'physics', { conceptId: 's-ph-heat', text: '0 °C equals how many kelvin?', options: ['0 K', '273 K', '100 K', '−273 K'], answer: 1, difficulty: 1,
  tests: 'Celsius↔kelvin.', solution: ['K = °C + 273.', '0 + 273 = 273 K.'],
  wrongWhy: ['Only at absolute zero.', 'Correct.', 'Not the boiling relation.', 'Sign error.'],
  trap: 'Add 273 — never subtract for °C→K.', memory: { tech: 'If X then Y', x: 'If going to kelvin, ADD 273.' }, recall: 'K = °C + 273.' }),

Q('q-ph-8', 'physics', { conceptId: 's-ph-light', text: 'A pencil partly in water looks bent at the surface. This is due to:', options: ['reflection', 'refraction', 'dispersion', 'diffraction'], answer: 1, difficulty: 1,
  tests: 'Refraction.', solution: ['Light slows and bends when entering water.', 'Bent look = refraction.'],
  wrongWhy: ['Bouncing is reflection.', 'Correct.', 'Splitting colours is dispersion.', 'Bending around edges is diffraction.'],
  trap: 'Bend at a boundary = refraction.', memory: { tech: 'Straw in glass', x: 'The straw’s “broken” look is refraction’s signature.' }, recall: 'Boundary bend = refraction.' }),

Q('q-ph-9', 'physics', { conceptId: 's-ph-elec', text: 'The unit of electrical resistance is:', options: ['volt', 'ampere', 'ohm', 'watt'], answer: 2, difficulty: 1,
  tests: 'Electrical units.', solution: ['Resistance → ohm (Ω).', 'V = I×R ties volt, ampere, ohm.'],
  wrongWhy: ['Volt = voltage.', 'Ampere = current.', 'Correct.', 'Watt = power.'],
  trap: 'V-A-Ω-W each have one job.', memory: { tech: 'VIR triangle', x: 'V on top, I R below — units follow the same triangle.' }, recall: 'Ω = ohm = resistance.' }),

Q('q-ph-10', 'physics', { conceptId: 's-ph-sound', text: 'Sound travels fastest in:', options: ['vacuum', 'air', 'water', 'steel'], answer: 3, difficulty: 1,
  tests: 'Sound speed vs medium.', solution: ['Particles are packed tightest in solids.', 'Steel > water > air > vacuum (no sound).'],
  wrongWhy: ['No medium, no sound.', 'Slowest of the three.', 'Middle speed.', 'Correct.'],
  trap: 'Sound is about particle vibration — solids win.', memory: { tech: 'Railway trick', x: 'Ear on the track hears the train first.' }, recall: 'Solid > liquid > gas > vacuum(none).' }),

Q('q-ch-1', 'chemistry', { conceptId: 's-ch-matter', text: 'Dew forming on a cold glass is an example of:', options: ['evaporation', 'condensation', 'sublimation', 'melting'], answer: 1, difficulty: 1,
  tests: 'Changes of state.', solution: ['Water vapour (gas) → liquid drops on the glass = condensation.'],
  wrongWhy: ['That is liquid → gas.', 'Correct.', 'That is solid → gas.', 'That is solid → liquid.'],
  trap: 'Condensation is the reverse of evaporation.', memory: { tech: 'Cold-glass visual', x: 'Cold glass “collects” air’s water as drops.' }, recall: 'Gas → liquid = condensation.' }),

Q('q-ch-2', 'chemistry', { conceptId: 's-ch-atom', text: 'The chemical symbol of sodium is:', options: ['So', 'Sd', 'Na', 'N'], answer: 2, difficulty: 1,
  tests: 'Element symbols.', solution: ['Na — from the Latin natrium.', 'Similarly K = potassium (kalium), Fe = iron (ferrum).'],
  wrongWhy: ['Not used.', 'Not used.', 'Correct.', 'N is nitrogen.'],
  trap: 'Latin-root symbols: Na, K, Fe, Cu (cuprum), Ag (argentum), Au (aurum), Pb (plumbum), Sn (stannum).', memory: { tech: 'Latin-root list', x: 'Na-Natrium, K-Kalium, Fe-Ferrum — old names, short symbols.' }, recall: 'Na = sodium.' }),

Q('q-ch-3', 'chemistry', { conceptId: 's-ch-acid', text: 'When blue litmus is dipped in a solution it turns red. The solution is:', options: ['basic', 'acidic', 'neutral', 'salty'], answer: 1, difficulty: 1,
  tests: 'Indicator behaviour.', solution: ['Blue litmus → red means ACID.', '(Red litmus → blue means base.)'],
  wrongWhy: ['Base would turn red litmus blue.', 'Correct.', 'Neutral changes nothing.', 'Salt solutions are often near neutral.'],
  trap: 'Memorise the direction: acid turns blue→red.', memory: { tech: 'Direction pair', x: 'Blue litmus blushes RED in acid.' }, recall: 'Acid: blue→red. Base: red→blue.' }),

Q('q-ch-4', 'chemistry', { conceptId: 's-ch-metal', text: 'The only liquid metal at room temperature is:', options: ['mercury', 'sodium', 'gallium', 'bromine'], answer: 0, difficulty: 1,
  tests: 'Metal exceptions.', solution: ['Mercury (Hg) is liquid at room temperature.', 'Bromine is liquid but a NON-metal.'],
  wrongWhy: ['Correct.', 'Sodium is a soft solid.', 'Gallium melts in your hand (~30 °C) but is solid at strict room temp.', 'Bromine is a non-metal liquid.'],
  trap: 'Liquid metal = mercury; liquid non-metal = bromine.', memory: { tech: 'Contrast pair', x: 'Hg = the liquid METAL; Br = the liquid NON-metal.' }, recall: 'Mercury = liquid metal.' }),

Q('q-ch-5', 'chemistry', { conceptId: 's-ch-react', text: 'Rusting of iron requires:', options: ['only oxygen', 'only water', 'oxygen and moisture', 'carbon dioxide'], answer: 2, difficulty: 1,
  tests: 'Rusting conditions.', solution: ['Iron + oxygen + moisture → hydrated iron oxide (rust).', 'Dry iron or oxygen-free water → no rust.'],
  wrongWhy: ['Water is also needed.', 'Oxygen is also needed.', 'Correct.', 'CO₂ is not the agent.'],
  trap: 'Both oxygen AND moisture — either alone fails.', memory: { tech: 'Rust recipe', x: 'Rust = Fe + O₂ + H₂O. Missing one ingredient = no rust.' }, recall: 'O₂ + moisture = rust.' }),

Q('q-ch-6', 'chemistry', { conceptId: 's-ch-fuel', text: 'Which gas is produced by INCOMPLETE combustion of fuels and is poisonous?', options: ['CO₂', 'CO', 'O₂', 'N₂'], answer: 1, difficulty: 2,
  tests: 'Combustion products.', solution: ['Incomplete burning gives carbon monoxide (CO).', 'CO binds haemoglobin and blocks oxygen transport.'],
  wrongWhy: ['CO₂ is the complete-burning product and is not the silent killer.', 'Correct.', 'O₂ supports burning.', 'N₂ is inert.'],
  trap: 'CO vs CO₂ — one letter, huge difference.', memory: { tech: 'One-letter killer', x: 'CO = Carbon “Only-one-O” = dangerous. CO₂ = complete = safer.' }, recall: 'Incomplete → CO (poisonous).' }),

Q('q-ch-7', 'chemistry', { conceptId: 's-ch-water', text: 'Which of the following is a colloid?', options: ['Salt solution', 'Milk', 'Sand in water', 'Pure water'], answer: 1, difficulty: 2,
  tests: 'Solutions vs colloids vs suspensions.', solution: ['Milk’s particles never settle and scatter light (Tyndall effect) → colloid.', 'Salt solution = true solution; sand = suspension.'],
  wrongWhy: ['True solution — particles fully dissolved.', 'Correct.', 'Suspension — settles down.', 'Pure solvent.'],
  trap: 'Colloid = middle size: too small to settle, too big to dissolve.', memory: { tech: 'Tyndall torch', x: 'Shine a torch through milk — the beam glows. That is a colloid.' }, recall: 'Milk, fog, smoke = colloids.' }),

Q('q-ls-1', 'life-sciences', { conceptId: 's-ls-cell', text: 'The “powerhouse of the cell” is the:', options: ['nucleus', 'mitochondria', 'ribosome', 'vacuole'], answer: 1, difficulty: 1,
  tests: 'Cell organelles.', solution: ['Mitochondria release energy (ATP) from food.'],
  wrongWhy: ['Nucleus is the control room.', 'Correct.', 'Ribosomes make proteins.', 'Vacuoles store water.'],
  trap: 'Nucleus = boss; mitochondria = generator.', memory: { tech: 'Generator room', x: 'M for Mitochondria = M for “Mains power”.' }, recall: 'Mitochondria = powerhouse.' }),

Q('q-ls-2', 'life-sciences', { conceptId: 's-ls-photo', text: 'Photosynthesis mainly takes place in the:', options: ['roots', 'stem', 'leaves', 'flowers'], answer: 2, difficulty: 1,
  tests: 'Site of photosynthesis.', solution: ['Leaves hold chlorophyll and stomata.', 'Chloroplasts inside leaf cells do the work.'],
  wrongWhy: ['Roots absorb water.', 'Stem transports.', 'Correct.', 'Flowers reproduce.'],
  trap: 'Chloroplast + sunlight = leaves only.', memory: { tech: 'Solar kitchen', x: 'Leaf = kitchen with solar panels (chloroplasts).' }, recall: 'Leaves = photosynthesis site.' }),

Q('q-ls-3', 'life-sciences', { conceptId: 's-ls-circ', text: 'Blood is pumped FROM the heart to the lungs by the:', options: ['right ventricle', 'left ventricle', 'right atrium', 'left atrium'], answer: 0, difficulty: 3,
  tests: 'Heart chambers.', solution: ['Right ventricle pumps deoxygenated blood to the lungs.', 'Left ventricle pumps oxygenated blood to the whole body (thickest wall).'],
  wrongWhy: ['Correct.', 'Left ventricle pumps to the BODY.', 'Right atrium receives blood.', 'Left atrium receives from lungs.'],
  trap: 'Right → lungs; Left → body. Remember: “Right goes to the Respiratory side”.', memory: { tech: 'R-L pair', x: 'R-side → Respiratory (lungs). L-side → Long trip (whole body).' }, recall: 'Right ventricle → lungs.' }),

Q('q-ls-4', 'life-sciences', { conceptId: 's-ls-digest', text: 'Bile juice helps in digestion of:', options: ['proteins', 'fats', 'starch', 'vitamins'], answer: 1, difficulty: 1,
  tests: 'Function of bile.', solution: ['Bile emulsifies fats — breaks them into tiny droplets.', 'It contains no enzymes.'],
  wrongWhy: ['Pepsin digests protein.', 'Correct.', 'Amylase digests starch.', 'Vitamins need no digestion.'],
  trap: 'Bile EMULSIFES (breaks up) fat; it does not chemically digest it.', memory: { tech: 'Detergent picture', x: 'Bile works like dish soap on grease — splits the blob into droplets.' }, recall: 'Bile = fat emulsifier.' }),

Q('q-ls-5', 'life-sciences', { conceptId: 's-ls-nerv', text: 'The part of the brain that maintains body balance is the:', options: ['cerebrum', 'cerebellum', 'medulla', 'thalamus'], answer: 1, difficulty: 1,
  tests: 'Brain parts.', solution: ['Cerebellum = balance, posture, coordination.', 'Cerebrum = thinking; medulla = heartbeat/breathing.'],
  wrongWhy: ['Cerebrum thinks.', 'Correct.', 'Medulla runs autonomic jobs.', 'Thalamus relays signals.'],
  trap: 'Cerebellum — “little brain” at the back — is the gymnast.', memory: { tech: 'B for Balance', x: 'CereBellum = Balance (both start with B).' }, recall: 'Cerebellum = balance.' }),

Q('q-ls-6', 'life-sciences', { conceptId: 's-ls-vit', text: 'Night blindness is caused by the deficiency of:', options: ['vitamin A', 'vitamin B', 'vitamin C', 'vitamin D'], answer: 0, difficulty: 1,
  tests: 'Vitamin deficiency.', solution: ['Vitamin A keeps the retina healthy.', 'Found in carrot, papaya, green vegetables.'],
  wrongWhy: ['Correct.', 'B1 deficiency = beriberi.', 'C deficiency = scurvy.', 'D deficiency = rickets.'],
  trap: 'A = eyes at night; D = bones.', memory: { tech: 'A for Amazing night vision', x: 'Carrots (vitamin A) — the rabbit sees in the dark!' }, recall: 'A → night blindness.' }),

Q('q-ls-7', 'life-sciences', { conceptId: 's-ls-disease', text: 'Which of the following diseases is caused by a virus?', options: ['Tuberculosis', 'Cholera', 'Influenza (flu)', 'Malaria'], answer: 2, difficulty: 2,
  tests: 'Pathogen types.', solution: ['Flu = virus.', 'TB, cholera = bacteria; malaria = protozoa.'],
  wrongWhy: ['Bacteria.', 'Bacteria.', 'Correct.', 'Protozoa (Plasmodium).'],
  trap: 'Bacteria vs virus vs protozoa pairs must be memorised.', memory: { tech: 'Carrier pairs', x: 'TB/Cholera bacteria; Flu virus; Malaria protozoa.' }, recall: 'Flu = virus.' }),

Q('q-ls-8', 'life-sciences', { conceptId: 's-ls-hormone', text: 'Goitre is caused by the deficiency of:', options: ['iron', 'iodine', 'calcium', 'vitamin D'], answer: 1, difficulty: 1,
  tests: 'Iodine and thyroxine.', solution: ['Iodine is needed to make thyroxine.', 'Deficiency → thyroid swells → goitre.'],
  wrongWhy: ['Iron deficiency = anaemia.', 'Correct.', 'Calcium = bones.', 'Vitamin D = rickets.'],
  trap: 'Iodine ↔ thyroid, iron ↔ blood.', memory: { tech: 'Salt hook', x: 'Iodised salt prevents goitre — the packet says it.' }, recall: 'Iodine → thyroxine → goitre if missing.' }),

Q('q-ls-9', 'life-sciences', { conceptId: 's-ls-plants', text: 'Food made in leaves is transported to other parts through the:', options: ['xylem', 'phloem', 'stomata', 'root hair'], answer: 1, difficulty: 1,
  tests: 'Xylem vs phloem.', solution: ['Phloem carries food (translocation).', 'Xylem carries water upward.'],
  wrongWhy: ['Xylem = water.', 'Correct.', 'Stomata are pores for gas exchange.', 'Root hairs absorb water.'],
  trap: 'X-up (water), P-both (food).', memory: { tech: 'Phloem = Food', x: 'Both start with the same sound — F.' }, recall: 'Phloem food, xylem water.' }),
];
